#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel)"
while IFS= read -r variable; do
  if [[ -n "$variable" ]]; then
    unset "$variable"
  fi
done < <(git rev-parse --local-env-vars)
cd "$ROOT_DIR"
"$ROOT_DIR/scripts/git-hooks/pre-push.sh" "$@"
