export const yoyoosunImportConfig = Object.freeze({
  customerKey: "yoyoosun",
  label: "永绅 yoyoosun 导入与客户差异配置草案",
  status: "draft",
  runtimeEnabled: false,
  scope:
    "Customer Config and data-import review draft only. This file records configuration decisions from extracted evidence; it must not load raw rows, write runtime data, or approve real import.",
  sourcePolicy: Object.freeze({
    rawSourceRoot: "docs/customers/yoyoosun/raw-source-files",
    extractedEvidenceRoot: "output/customers/yoyoosun/source-extract",
    generatedCandidate:
      "output/customers/yoyoosun/source-extract/customer-import-config.candidate.json",
    noRawRowsInConfig: true,
    usesExtractedEvidenceOnly: true,
    requiresExistingV1SnapshotBeforeApproval: true,
    requiresHumanApprovalForRealImport: true,
    pdfImageOcrEnabled: false,
  }),
  boundaries: Object.freeze({
    createsTenant: false,
    changesSchema: false,
    changesMigration: false,
    changesBackendRbac: false,
    changesWorkflowFactRules: false,
    changesRuntimeLoader: false,
    executesImport: false,
    executesRealImport: false,
    canExecuteRealImport: false,
    writesBusinessRecords: false,
    writesFacts: false,
    writesInventoryFacts: false,
    writesShipmentFacts: false,
    writesFinanceFacts: false,
    createsProductSkus: false,
    createsPurchaseOrderRuntime: false,
  }),
  globalScan: Object.freeze({
    scanDate: "2026-06-11",
    evidenceInputs: Object.freeze([
      "docs/当前真源与交接顺序.md",
      "docs/product/产品能力进度台账.md",
      "docs/customers/yoyoosun/客户配置草案.md",
      "docs/customers/yoyoosun/客户交付矩阵.md",
      "docs/customers/yoyoosun/客户差异台账.md",
      "config/customers/yoyoosun/menuConfig.mjs",
      "config/customers/yoyoosun/fieldNumberingConfig.mjs",
      "config/industry-templates/plush/templateConfig.mjs",
      "config/private-deployment-template/templateConfig.mjs",
      "output/customers/yoyoosun/source-extract/source-snapshot.extracted.json",
      "output/customers/yoyoosun/source-extract/dry-run-preview/validation-summary.json",
      "output/customers/yoyoosun/source-extract/freeze-check/freeze-check-summary.json",
    ]),
    extractedSourceStats: Object.freeze({
      workbooks: 5,
      sheets: 20,
      sourceRows: 5800,
      sourceTypes: Object.freeze({
        dataImportSource: 5794,
        printTemplateInput: 6,
      }),
      countsByDomain: Object.freeze({
        products: 369,
        units: 11,
        materials: 438,
        bom: 91,
        purchase_orders: 1971,
        suppliers: 970,
        outsourcing: 1266,
        contacts: 684,
      }),
    }),
    dryRunPreview: Object.freeze({
      totalSources: 5800,
      normalizedRows: 5800,
      candidateCountsByAction: Object.freeze({
        create: 818,
        review: 1751,
        defer: 3231,
        update: 0,
        skip: 0,
        forbidden: 0,
      }),
      unresolvedCountsBySeverity: Object.freeze({
        block: 963,
        defer: 3231,
        review: 976,
        warning: 0,
      }),
      forbiddenCount: 6,
      blockerCount: 969,
      canProceedToManualReview: true,
      canExecuteRealImport: false,
    }),
    freezeCheck: Object.freeze({
      valid: true,
      sourceCount: 5800,
      blockerCount: 0,
      warningCount: 4417,
      sensitiveFieldCount: 4417,
      duplicateSourceIdCount: 0,
    }),
  }),
  configItems: Object.freeze([
    {
      id: "YOYOOSUN-CFG-001",
      group: "brand_menu",
      label: "品牌与桌面菜单展示",
      classification: "runtime_active_display_config",
      decision: "runtime_active",
      source: "config/customers/yoyoosun/menuConfig.mjs",
      appliesTo: Object.freeze(["web_brand", "desktop_menu"]),
      productCoreImpact: "none",
      guardrail:
        "只影响前端品牌和菜单展示；菜单隐藏不是安全边界，后端仍以 RBAC 和 usecase 校验为准。",
    },
    {
      id: "YOYOOSUN-CFG-002",
      group: "field_display",
      label: "字段显示配置草案",
      classification: "draft_customer_config",
      decision: "review_required",
      source: "config/customers/yoyoosun/fieldNumberingConfig.mjs",
      appliesTo: Object.freeze([
        "customers",
        "suppliers",
        "sales_orders",
        "sales_order_items",
      ]),
      productCoreImpact: "none",
      guardrail:
        "客户样本字段不能自动升级为 Product Core 必填字段；客户确认前不接 runtime。",
    },
    {
      id: "YOYOOSUN-CFG-003",
      group: "numbering_rules",
      label: "编号规则配置草案",
      classification: "draft_customer_config",
      decision: "review_required",
      source: "config/customers/yoyoosun/fieldNumberingConfig.mjs",
      appliesTo: Object.freeze([
        "customers",
        "suppliers",
        "products",
        "sales_orders",
        "purchase_orders",
      ]),
      productCoreImpact: "none",
      guardrail:
        "编号缺失不得伪造；采购订单号仍是 deferred，不生成 purchase order runtime。",
    },
    {
      id: "YOYOOSUN-CFG-004",
      group: "source_extract_adapter",
      label: "Excel 来源提取与字段映射适配",
      classification: "data_import_adapter",
      decision: "draft_only",
      source:
        "output/customers/yoyoosun/source-extract/customer-import-config.candidate.json",
      appliesTo: Object.freeze([
        "units",
        "products",
        "materials",
        "suppliers",
        "contacts",
        "bom",
      ]),
      productCoreImpact: "none",
      guardrail:
        "只记录映射、统计和评审顺序；配置文件不嵌入 raw rows，不读取 DB，也不是 import approval。",
    },
    {
      id: "YOYOOSUN-CFG-005",
      group: "master_data_import_defaults",
      label: "主数据导入顺序与默认评审规则",
      classification: "data_import_adapter",
      decision: "review_required",
      source:
        "output/customers/yoyoosun/source-extract/source-snapshot.extracted.json",
      appliesTo: Object.freeze([
        "units",
        "products",
        "materials",
        "suppliers",
        "contacts",
        "bom",
      ]),
      productCoreImpact: "none",
      guardrail:
        "单位先标准化；联系人必须先匹配 owner；BOM 必须在 product/material/unit 唯一匹配后才可进入后续候选。",
    },
    {
      id: "YOYOOSUN-CFG-006",
      group: "purchase_outsourcing_source_documents",
      label: "采购与委外源单据配置线索",
      classification: "deferred_runtime",
      decision: "deferred",
      source: "docs/customers/yoyoosun/导入试跑工具说明.md",
      appliesTo: Object.freeze(["purchase_orders", "outsourcing"]),
      productCoreImpact: "none",
      guardrail:
        "采购订单和委外源单据当前只保留 source snapshot 和字段映射，不创建采购订单 runtime，不写库存、委外或应付事实。",
    },
    {
      id: "YOYOOSUN-CFG-007",
      group: "print_template_inputs",
      label: "采购合同与加工合同打印样本输入",
      classification: "print_template_input",
      decision: "deferred",
      source: "docs/customers/yoyoosun/原始客户文件归档评审.md",
      appliesTo: Object.freeze(["purchase_contract", "processing_contract"]),
      productCoreImpact: "none",
      guardrail:
        "只作为客户打印样本和字段来源线索；不建立通用模板引擎，不反向决定 schema、fact、workflow 或 API。",
    },
    {
      id: "YOYOOSUN-CFG-008",
      group: "role_permission_template",
      label: "角色、权限和岗位任务模板候选",
      classification: "draft_customer_config",
      decision: "review_required",
      source: "docs/customers/yoyoosun/试用账号角色菜单核对清单.md",
      appliesTo: Object.freeze([
        "roles",
        "permissions",
        "mobile_task_entry",
      ]),
      productCoreImpact: "none",
      guardrail:
        "只作为客户账号和培训核对清单；不改变后端 RBAC 真源，不把移动端任务完成写成事实过账。",
    },
    {
      id: "YOYOOSUN-CFG-009",
      group: "forbidden_auto_import",
      label: "禁止自动导入目标",
      classification: "forbidden_auto_import",
      decision: "forbidden_auto_import",
      source:
        "output/customers/yoyoosun/source-extract/dry-run-preview/forbidden-auto-import.json",
      appliesTo: Object.freeze([
        "tenant_id",
        "business_records",
        "product_skus",
        "purchase_orders",
        "shipments",
        "stock_reservations",
        "inventory_facts",
        "finance_facts",
      ]),
      productCoreImpact: "none",
      guardrail:
        "任何自动写入 schema、business_records、库存、出货、预留、财务或 workflow/fact 混淆都必须保持禁止。",
    },
  ]),
  sourceSheetGroups: Object.freeze([
    {
      key: "material_bom_analysis",
      label: "材料分析明细 / BOM 线索",
      domains: Object.freeze(["bom", "materials", "units", "products"]),
      mappedFields: Object.freeze([
        "产品编号",
        "产品名称",
        "物料名称",
        "厂商料号",
        "规格",
        "单位",
        "组装部位",
        "单位用量",
        "损耗%",
        "总用量",
        "加工方式",
      ]),
      decision: "review_required",
      guardrail: "BOM 不写库存事实；必须先完成产品、材料和单位唯一匹配。",
    },
    {
      key: "purchase_material_summary",
      label: "辅材 / 包材 / 原辅料采购汇总线索",
      domains: Object.freeze(["purchase_orders", "materials", "suppliers", "units"]),
      mappedFields: Object.freeze([
        "产品订单编号",
        "产品编号",
        "产品名称",
        "材料品名",
        "厂商料号",
        "规格",
        "单位",
        "单价",
        "采购数量",
        "采购金额",
        "厂商简称",
        "回货日期",
      ]),
      decision: "deferred",
      guardrail: "采购数量和金额不能自动生成采购订单、采购入库、库存或应付事实。",
    },
    {
      key: "supplier_contact_directory",
      label: "材料厂商 / 加工厂商资料线索",
      domains: Object.freeze(["suppliers", "contacts"]),
      mappedFields: Object.freeze([
        "厂商简称",
        "厂商编号",
        "厂商名称",
        "厂家全称",
        "加工工序",
        "联系人",
        "联系电话",
        "地址",
        "类别",
        "银行卡号",
      ]),
      decision: "review_required",
      guardrail: "联系电话、地址、银行卡号属于敏感字段线索；联系人 owner_id 不能按名称猜测。",
    },
    {
      key: "outsourcing_summary",
      label: "委外加工汇总线索",
      domains: Object.freeze(["outsourcing", "suppliers", "products", "units"]),
      mappedFields: Object.freeze([
        "委外加工订单号",
        "产品订单编号",
        "产品编号",
        "产品名称",
        "加工项目",
        "厂家名称",
        "工序类别",
        "单位",
        "单价",
        "加工数量",
        "加工金额",
        "回货日期",
      ]),
      decision: "deferred",
      guardrail: "委外汇总当前只做源单据线索，不写 outsourcing_facts 或 finance_facts。",
    },
    {
      key: "contract_print_samples",
      label: "C 类辅料合同 / B 类加工合同打印样本",
      domains: Object.freeze(["purchase_orders", "outsourcing", "print_template_input"]),
      mappedFields: Object.freeze([
        "采购订单号",
        "委外加工订单号",
        "产品订单编号",
        "产品编号",
        "产品名称",
        "材料品名",
        "工序名称",
        "单位",
        "单价",
        "采购数量",
        "委托加工数量",
        "采购金额",
        "委托加工金额",
      ]),
      decision: "deferred",
      guardrail: "合同样本不反向定义产品核心字段或通用打印模板内核。",
    },
  ]),
  recommendedImportSequence: Object.freeze([
    {
      step: 1,
      domains: Object.freeze(["units"]),
      decision: "review_required",
      reason: "BOM、采购和委外行都依赖单位；单位文本必须先人工标准化。",
    },
    {
      step: 2,
      domains: Object.freeze(["products", "materials", "suppliers"]),
      decision: "review_required",
      reason: "产品、材料和供应商可进入主数据候选，但重复名称、厂商简称和加工厂角色必须人工确认。",
    },
    {
      step: 3,
      domains: Object.freeze(["contacts"]),
      decision: "review_required",
      reason: "联系人必须先确认 owner_type + owner_id；不能按供应商名称猜 owner_id。",
    },
    {
      step: 4,
      domains: Object.freeze(["bom"]),
      decision: "review_required",
      reason: "BOM 只在产品、材料、单位均唯一匹配后才能作为后续导入候选；不写库存事实。",
    },
    {
      step: 5,
      domains: Object.freeze(["purchase_orders", "outsourcing"]),
      decision: "deferred",
      reason: "采购订单和委外源单据当前仍是 deferred domain；本提取只保留来源快照和字段映射。",
    },
  ]),
  reviewQueues: Object.freeze([
    {
      key: "unit_normalization",
      severity: "block",
      domains: Object.freeze(["units"]),
      evidenceCount: 11,
      decision: "review_required",
      owner: "data_governance",
      note: "单位必须映射到既有 units 或经批准的新单位；不能按文本自动创建正式单位。",
    },
    {
      key: "supplier_role_split",
      severity: "review",
      domains: Object.freeze(["suppliers"]),
      evidenceCount: 970,
      decision: "review_required",
      owner: "masterdata",
      note: "材料供应商、加工厂和临时文本必须区分；supplier_type 不能由表名直接决定。",
    },
    {
      key: "contact_owner_match",
      severity: "block",
      domains: Object.freeze(["contacts", "suppliers"]),
      evidenceCount: 684,
      decision: "review_required",
      owner: "masterdata",
      note: "联系人必须确认 owner_type + owner_id；不能按厂商简称猜测 owner_id。",
    },
    {
      key: "bom_product_material_unit_match",
      severity: "block",
      domains: Object.freeze(["bom", "products", "materials", "units"]),
      evidenceCount: 91,
      decision: "review_required",
      owner: "masterdata",
      note: "BOM 需要产品、材料和单位唯一匹配；不写 inventory_txns 或 balances。",
    },
    {
      key: "sensitive_contact_bank_fields",
      severity: "review",
      domains: Object.freeze(["suppliers", "contacts", "purchase_orders"]),
      evidenceCount: 4417,
      decision: "review_required",
      owner: "data_governance",
      note: "地址、联系电话、银行卡号、请求人电话等敏感字段只能进入人工 review，不能进入公开配置或日志。",
    },
    {
      key: "existing_v1_snapshot",
      severity: "block",
      domains: Object.freeze(["customers", "suppliers", "contacts", "sales_orders"]),
      evidenceCount: 1,
      decision: "review_required",
      owner: "data_governance",
      note: "当前 existing-v1.empty-preview.json 只是预览占位；真实 sign-off 前必须替换为已 review 的 existing V1 snapshot。",
    },
  ]),
  forbiddenAutoImportTargets: Object.freeze([
    "tenant_id",
    "business_records",
    "product_skus",
    "purchase_orders",
    "outsourcing_facts",
    "shipments",
    "shipment_items",
    "stock_reservations",
    "inventory_txns",
    "inventory_balances",
    "inventory_lots",
    "finance_facts",
    "workflow_facts",
    "shipping_released_to_shipped",
    "workflow_done_to_fact_posted",
  ]),
  deferredRuntimeTargets: Object.freeze([
    "purchase_order_runtime",
    "outsourcing_order_runtime",
    "print_template_engine",
    "sku_color_size_model",
    "real_customer_data_import",
    "reporting_dashboard",
    "attachment_service",
    "scan_barcode_pda",
  ]),
});
