export const yoyoosunRawSourceFormMap = Object.freeze({
  customerKey: "yoyoosun",
  status: "dry_run_mapping",
  boundary:
    "Raw source files are evidence and dry-run mapping inputs only. They must not write runtime data, Workflow, inventory, shipment or finance Facts without explicit import approval and release evidence.",
  entries: Object.freeze([
    Object.freeze({
      sourceId: "yoyoosun-raw-material-purchase-summary-20260602",
      targetForms: Object.freeze(["SupplierForm", "MaterialForm", "PurchaseOrderForm", "MaterialPurchaseContractPrintDraft"]),
      targetEntities: Object.freeze(["suppliers", "materials", "units", "purchase_orders", "purchase_order_items"]),
      status: "dry_run_ready",
      fieldCoverage: Object.freeze([
        "supplier.display_name",
        "supplier.contact_snapshot",
        "material.material_name",
        "material.spec",
        "material.unit",
        "purchase_order.purchase_order_no",
        "purchase_order.supplier_snapshot",
        "purchase_order_items.material_snapshot",
        "purchase_order_items.quantity",
        "purchase_order_items.unit_price",
        "purchase_order_items.amount",
      ]),
      printCoverage: Object.freeze(["material-purchase-contract.detail_lines", "material-purchase-contract.supplier_snapshot"]),
      boundary: "辅材 / 包材来源只生成候选主数据和采购源单 dry-run；不自动生成采购入库、库存或应付事实。",
    }),
    Object.freeze({
      sourceId: "yoyoosun-raw-outsourcing-summary-20260602",
      targetForms: Object.freeze(["SupplierForm", "ContactForm", "OutsourcingOrderForm", "ProcessingContractPrintDraft"]),
      targetEntities: Object.freeze(["suppliers", "contacts", "outsourcing_orders", "outsourcing_order_items"]),
      status: "dry_run_ready",
      fieldCoverage: Object.freeze([
        "supplier.display_name",
        "contact.name",
        "contact.phone",
        "outsourcing_order.outsourcing_order_no",
        "outsourcing_order.processor_snapshot",
        "outsourcing_order_items.product_order_no",
        "outsourcing_order_items.product_no",
        "outsourcing_order_items.product_name",
        "outsourcing_order_items.process_name",
        "outsourcing_order_items.quantity",
        "outsourcing_order_items.unit_price",
        "outsourcing_order_items.amount",
      ]),
      printCoverage: Object.freeze(["processing-contract.header", "processing-contract.detail_lines"]),
      boundary: "加工汇总只生成委外源单和加工合同草稿候选；不自动写委外回货、应付、付款或库存事实。",
    }),
    Object.freeze({
      sourceId: "yoyoosun-raw-bom-26029-20260119",
      targetForms: Object.freeze(["ProductForm", "ProductSKUForm", "MaterialForm", "BOMVersionForm"]),
      targetEntities: Object.freeze(["products", "product_skus", "materials", "units", "bom_versions", "bom_items"]),
      status: "dry_run_ready",
      fieldCoverage: Object.freeze([
        "product.product_no",
        "product.display_name",
        "product_sku.sku_no",
        "material.material_name",
        "material.spec",
        "material.unit",
        "bom_version.version_no",
        "bom_items.material_snapshot",
        "bom_items.usage_qty",
      ]),
      printCoverage: Object.freeze([]),
      boundary: "BOM 来源只形成产品、SKU、材料和 BOM 候选；不自动写采购、库存、生产或成本事实。",
    }),
    Object.freeze({
      sourceId: "yoyoosun-raw-bom-26204-20260410",
      targetForms: Object.freeze(["ProductForm", "ProductSKUForm", "MaterialForm", "BOMVersionForm"]),
      targetEntities: Object.freeze(["products", "product_skus", "materials", "units", "bom_versions", "bom_items"]),
      status: "dry_run_ready",
      fieldCoverage: Object.freeze([
        "product.product_no",
        "product.display_name",
        "product_sku.sku_no",
        "material.material_name",
        "material.spec",
        "material.unit",
        "bom_version.version_no",
        "bom_items.material_snapshot",
        "bom_items.usage_qty",
      ]),
      printCoverage: Object.freeze([]),
      boundary: "BOM 来源只形成产品、SKU、材料和 BOM 候选；不自动写采购、库存、生产或成本事实。",
    }),
    Object.freeze({
      sourceId: "yoyoosun-raw-contract-template-material-outsourcing",
      targetForms: Object.freeze(["MaterialPurchaseContractPrintDraft", "ProcessingContractPrintDraft"]),
      targetEntities: Object.freeze(["print_template_defaults", "purchase_orders", "outsourcing_orders"]),
      status: "manual_reference",
      fieldCoverage: Object.freeze([
        "print_template_defaults.buyerCompany",
        "material-purchase-contract.header_labels",
        "material-purchase-contract.detail_labels",
        "processing-contract.header_labels",
        "processing-contract.detail_labels",
        "contract.clauses",
      ]),
      printCoverage: Object.freeze(["material-purchase-contract", "processing-contract"]),
      boundary: "合同模板只作字段和纸面样式来源；不作为运行时 Excel 母版，不覆盖 Product Core 默认模板。",
    }),
    Object.freeze({
      sourceId: "yoyoosun-raw-outsourcing-contract-pdf-zichun",
      targetForms: Object.freeze(["ProcessingContractPrintDraft", "OutsourcingOrderForm"]),
      targetEntities: Object.freeze(["outsourcing_orders", "outsourcing_order_items", "print_template_defaults"]),
      status: "manual_reference",
      fieldCoverage: Object.freeze([
        "processing-contract.header",
        "processing-contract.detail_lines",
        "processing-contract.clauses",
        "processing-contract.attachments",
      ]),
      printCoverage: Object.freeze(["processing-contract"]),
      boundary: "PDF 只作人工核对来源，不做 OCR，不自动生成委外、应付、付款或库存事实。",
    }),
    Object.freeze({
      sourceId: "yoyoosun-raw-formal-mobile-report-v3",
      targetForms: Object.freeze(["MobileRoleTasksPage", "WorkflowTaskActionDrawer"]),
      targetEntities: Object.freeze(["workflow_tasks", "workflow_task_events"]),
      status: "manual_reference",
      fieldCoverage: Object.freeze(["mobile.task_card", "mobile.task_detail", "workflow.action_labels"]),
      printCoverage: Object.freeze([]),
      boundary: "移动端汇报 PDF 只作页面观感和交付线索，不生成结构化导入行或 Workflow runtime 状态。",
    }),
    Object.freeze({
      sourceId: "yoyoosun-raw-mobile-report-screenshot-20260420",
      targetForms: Object.freeze(["MobileRoleTasksPage"]),
      targetEntities: Object.freeze(["workflow_tasks"]),
      status: "manual_reference",
      fieldCoverage: Object.freeze(["mobile.task_list_visual", "mobile.task_status_labels"]),
      printCoverage: Object.freeze([]),
      boundary: "截图只作人工 UI 核对线索，不能作为唯一字段、流程或事实真源。",
    }),
    Object.freeze({
      sourceId: "yoyoosun-raw-role-workflow-v3-20260413",
      targetForms: Object.freeze(["CustomerConfigPreview", "WorkflowRuntimeLedger", "MobileRoleTasksPage"]),
      targetEntities: Object.freeze(["role_profiles", "work_pools", "workflow_tasks", "process_definitions"]),
      status: "manual_reference",
      fieldCoverage: Object.freeze(["role.owner_pool", "role.capabilities", "workflow.node_order", "workflow.fact_boundary"]),
      printCoverage: Object.freeze([]),
      boundary: "流程图截图只作角色与流程边界线索，不自动升级为 Product Core runtime 流程真源。",
    }),
    Object.freeze({
      sourceId: "yoyoosun-raw-purchase-contract-photo-20260421-jpeg",
      targetForms: Object.freeze(["MaterialPurchaseContractPrintDraft", "PurchaseOrderForm"]),
      targetEntities: Object.freeze(["purchase_orders", "purchase_order_items", "print_template_defaults"]),
      status: "manual_reference",
      fieldCoverage: Object.freeze([
        "material-purchase-contract.header",
        "material-purchase-contract.detail_lines",
        "material-purchase-contract.clauses",
        "purchase_order.supplier_snapshot",
      ]),
      printCoverage: Object.freeze(["material-purchase-contract"]),
      duplicateGroup: "yoyoosun-purchase-contract-order-photo-20260421",
      boundary: "采购合同照片只作人工字段和版式线索，不做 OCR，不重复计为独立业务单据。",
    }),
    Object.freeze({
      sourceId: "yoyoosun-raw-purchase-contract-photo-20260421-source-copy-jpg",
      targetForms: Object.freeze(["MaterialPurchaseContractPrintDraft", "PurchaseOrderForm"]),
      targetEntities: Object.freeze(["purchase_orders", "purchase_order_items", "print_template_defaults"]),
      status: "manual_reference",
      fieldCoverage: Object.freeze([
        "material-purchase-contract.header",
        "material-purchase-contract.detail_lines",
        "material-purchase-contract.clauses",
        "purchase_order.supplier_snapshot",
      ]),
      printCoverage: Object.freeze(["material-purchase-contract"]),
      duplicateGroup: "yoyoosun-purchase-contract-order-photo-20260421",
      boundary: "采购合同照片副本只作同组人工线索，不重复计为独立业务单据。",
    }),
  ]),
});
