export const yoyoosunRoleFlowMatrix = Object.freeze({
  customerKey: "yoyoosun",
  status: "preview_only",
  boundary:
    "Role matrix explains customer work pools, menu surfaces and allowed actions. It does not create backend RBAC, write Workflow tasks or post Facts.",
  roles: Object.freeze([
    Object.freeze({
      roleKey: "sales",
      displayName: "销售",
      productCoreRole: "sales",
      ownerPools: Object.freeze(["sales"]),
      menuSurfaces: Object.freeze(["customers", "sales_orders", "shipments", "workflow_tasks"]),
      capabilityKeys: Object.freeze([
        "customer.read",
        "contact.read",
        "sales_order.read",
        "sales_order.create",
        "sales_order.update",
        "sales_order.submit",
        "sales_order_item.read",
        "sales_order_item.create",
        "sales_order_item.update",
        "shipment.read",
        "workflow.task.read",
        "workflow.task.complete",
        "mobile.sales.access",
      ]),
      flowResponsibilities: Object.freeze([
        "sales_order_approval.sales_submit",
        "sales_to_production.source_review",
      ]),
      guardrail:
        "销售只能维护客户、销售源单和协同提交线索，不直接写库存、质检、出货、应收或发票事实。",
    }),
    Object.freeze({
      roleKey: "boss",
      displayName: "老板 / 管理审批",
      productCoreRole: "boss",
      ownerPools: Object.freeze(["boss"]),
      menuSurfaces: Object.freeze(["workflow_tasks", "business_dashboard"]),
      capabilityKeys: Object.freeze([
        "workflow.task.read",
        "workflow.task.approve",
        "workflow.task.reject",
        "mobile.boss.access",
      ]),
      flowResponsibilities: Object.freeze([
        "sales_order_approval.boss_approval",
        "purchase_order_approval.boss_review",
        "payment_approval.boss_approval",
      ]),
      guardrail:
        "老板角色只做审批 / 退回协同判断，不绕过具体业务 usecase 的状态、引用、幂等和事实写入校验。",
    }),
    Object.freeze({
      roleKey: "engineering",
      displayName: "工程",
      productCoreRole: "engineering",
      ownerPools: Object.freeze(["engineering"]),
      menuSurfaces: Object.freeze(["products", "materials", "processes", "bom", "workflow_tasks"]),
      capabilityKeys: Object.freeze([
        "material.read",
        "process.read",
        "process.create",
        "process.update",
        "product.read",
        "product.create",
        "product.update",
        "product_sku.read",
        "product_sku.create",
        "product_sku.update",
        "bom.read",
        "bom.create",
        "bom.update",
        "bom.activate",
        "workflow.task.read",
        "workflow.task.complete",
        "mobile.engineering.access",
      ]),
      flowResponsibilities: Object.freeze([
        "sales_order_approval.engineering_data",
        "sales_to_production.engineering_data_ready",
      ]),
      guardrail:
        "工程补齐产品、SKU、工序、BOM 等资料，不直接生成生产、库存、采购、质检、出货或财务事实。",
    }),
    Object.freeze({
      roleKey: "pmc",
      displayName: "PMC",
      productCoreRole: "pmc",
      ownerPools: Object.freeze(["pmc"]),
      menuSurfaces: Object.freeze(["products", "bom", "production", "workflow_tasks"]),
      capabilityKeys: Object.freeze([
        "product.read",
        "product_sku.read",
        "bom.read",
        "pmc.plan.read",
        "pmc.plan.create",
        "pmc.plan.update",
        "pmc.risk.read",
        "pmc.risk.handle",
        "workflow.task.read",
        "workflow.task.complete",
        "mobile.pmc.access",
      ]),
      flowResponsibilities: Object.freeze([
        "sales_order_approval.pmc_review",
        "sales_to_production.production_review",
      ]),
      guardrail:
        "PMC 负责排期、风险和生产评审，不把计划状态直接写成生产完工、成品入库或出货事实。",
    }),
    Object.freeze({
      roleKey: "purchasing",
      displayName: "采购",
      productCoreRole: "purchase",
      ownerPools: Object.freeze(["purchase"]),
      menuSurfaces: Object.freeze(["suppliers", "purchase_orders", "purchase_receipts", "workflow_tasks"]),
      capabilityKeys: Object.freeze([
        "supplier.read",
        "supplier.create",
        "supplier.update",
        "purchase.order.read",
        "purchase.order.create",
        "purchase.order.update",
        "purchase.receipt.read",
        "purchase.receipt.create",
        "workflow.task.read",
        "workflow.task.complete",
        "mobile.purchase.access",
      ]),
      flowResponsibilities: Object.freeze([
        "purchase_order_approval.purchase_submit",
        "purchase_to_inventory.purchase_source_ready",
      ]),
      printTemplates: Object.freeze(["material-purchase-contract"]),
      guardrail:
        "采购可维护采购承诺、供应商和采购合同打印草稿；只有采购入库 usecase 可写入库、库存或应付相关事实。",
    }),
    Object.freeze({
      roleKey: "warehouse",
      displayName: "仓库",
      productCoreRole: "warehouse",
      ownerPools: Object.freeze(["warehouse"]),
      menuSurfaces: Object.freeze(["inventory", "purchase_receipts", "shipments", "workflow_tasks"]),
      capabilityKeys: Object.freeze([
        "warehouse.inventory.read",
        "warehouse.inbound.read",
        "warehouse.inbound.confirm",
        "warehouse.outbound.read",
        "warehouse.outbound.confirm",
        "shipment.read",
        "shipment.ship",
        "workflow.task.read",
        "workflow.task.complete",
        "workflow.task.reject",
        "mobile.warehouse.access",
      ]),
      flowResponsibilities: Object.freeze([
        "purchase_order_approval.warehouse_prepare",
        "finished_goods_delivery.shipment_execution",
        "purchase_to_inventory.warehouse_inbound",
      ]),
      guardrail:
        "仓库执行入库 / 出货时必须走对应业务 usecase，不通过任务完成动作直接增减库存。",
    }),
    Object.freeze({
      roleKey: "quality",
      displayName: "品质",
      productCoreRole: "quality",
      ownerPools: Object.freeze(["quality"]),
      menuSurfaces: Object.freeze(["quality_inspections", "purchase_receipts", "workflow_tasks"]),
      capabilityKeys: Object.freeze([
        "quality.inspection.read",
        "quality.inspection.create",
        "quality.inspection.update",
        "quality.exception.handle",
        "workflow.task.read",
        "workflow.task.complete",
        "workflow.task.reject",
        "mobile.quality.access",
      ]),
      flowResponsibilities: Object.freeze([
        "purchase_order_approval.quality_prepare",
        "finished_goods_delivery.finished_goods_qc",
        "purchase_to_inventory.incoming_qc",
      ]),
      guardrail:
        "品质只做质检判定和异常处理，不能把质检任务完成自动写成库存、出货或财务事实。",
    }),
    Object.freeze({
      roleKey: "finance",
      displayName: "财务",
      productCoreRole: "finance",
      ownerPools: Object.freeze(["finance"]),
      menuSurfaces: Object.freeze(["finance", "shipments", "workflow_tasks"]),
      capabilityKeys: Object.freeze([
        "finance.payable.read",
        "finance.payable.confirm",
        "finance.receivable.read",
        "finance.receivable.confirm",
        "finance.report.read",
        "workflow.task.read",
        "workflow.task.complete",
        "workflow.task.reject",
        "mobile.finance.access",
      ]),
      flowResponsibilities: Object.freeze([
        "payment_approval.finance_submit",
        "finished_goods_delivery.finance_release",
        "finished_goods_delivery.receivable_lead",
        "delivery_to_settlement.receivable_review",
      ]),
      guardrail:
        "财务放行、应收 / 应付草稿和对账线索不等于税控、总账、收付款核销或完整财务系统。",
    }),
    Object.freeze({
      roleKey: "production",
      displayName: "生产 / 委外",
      productCoreRole: "production",
      ownerPools: Object.freeze(["production"]),
      menuSurfaces: Object.freeze(["outsourcing_orders", "production", "workflow_tasks"]),
      capabilityKeys: Object.freeze([
        "outsourcing.order.read",
        "outsourcing.order.create",
        "outsourcing.order.update",
        "pmc.plan.read",
        "pmc.plan.update",
        "workflow.task.read",
        "workflow.task.complete",
        "mobile.production.access",
      ]),
      flowResponsibilities: Object.freeze([
        "production_to_inventory.production_progress",
        "outsourcing_return.receipt_review",
      ]),
      printTemplates: Object.freeze(["processing-contract"]),
      guardrail:
        "生产 / 委外负责加工合同源单和生产进度线索，不直接写成品入库、质检通过、结算或付款事实。",
    }),
  ]),
});
