export const yoyoosunRoleFlowMatrix = Object.freeze({
  customerKey: "yoyoosun",
  status: "runtime_manifest_source",
  boundary:
    "角色矩阵会编译为客户配置 role_profiles / access_entitlements / work_pool_memberships；它只能收窄 Product Core RBAC，不能提升后端权限、上传代码或写入业务事实。",
  roleAssignmentProfiles: Object.freeze([
    Object.freeze({
      profileKey: "finance_purchase_contract_operator",
      displayName: "财务兼采购合同经办",
      roleKeys: Object.freeze(["finance", "purchase"]),
      responsibility:
        "永绅由财务人员根据已确认工程资料制作采购合同和维护采购源单时，为同一管理员账号同时分配财务与采购两个内置角色。",
      guardrail:
        "不把 purchase.order.* 权限并入 Product Core 的 finance 角色；采购任务仍归 purchase 责任池，采购订单审批仍由 boss 角色执行。",
    }),
  ]),
  roles: Object.freeze([
    Object.freeze({
      roleKey: "sales",
      displayName: "销售",
      productCoreRole: "sales",
      ownerPools: Object.freeze(["sales"]),
      menuSurfaces: Object.freeze([
        "global-dashboard",
        "customers",
        "sales-orders",
        "products",
        "production-orders",
        "inventory",
        "shipments",
        "task-board",
        "print-center",
      ]),
      capabilityKeys: Object.freeze([
        "erp.workbench.read",
        "erp.print_template.read",
        "field.party_private.read",
        "field.sales_commercial.read",
        "customer.read",
        "customer.create",
        "customer.update",
        "contact.read",
        "contact.create",
        "contact.update",
        "contact.disable",
        "contact.set_primary",
        "material.read",
        "product.read",
        "product_sku.read",
        "sales_order.read",
        "sales_order.create",
        "sales_order.update",
        "sales_order.submit",
        "sales_order.cancel",
        "sales_order_item.read",
        "production.wip.read",
        "production.packaging_material.confirm",
        "warehouse.inventory.read",
        "stock.reservation.create",
        "shipment.read",
        "workflow.task.read",
        "workflow.task.update",
        "workflow.task.complete",
        "mobile.sales.access",
      ]),
      flowResponsibilities: Object.freeze([
        "sales_order_approval.sales_submit",
        "sales_to_production.source_review",
        "production_to_inventory.packaging_material_confirmation",
      ]),
      guardrail:
        "销售可只读核对生产路线并确认包材版面 / 包装版本；不能安排、执行或返工 WIP，库存、质检、出货、应收和发票事实仍由对应领域 usecase 处理。",
    }),
    Object.freeze({
      roleKey: "boss",
      displayName: "老板 / 管理审批",
      productCoreRole: "boss",
      ownerPools: Object.freeze(["boss"]),
      menuSurfaces: Object.freeze([
        "global-dashboard",
        "business-dashboard",
        "task-board",
        "sales-orders",
        "accessories-purchase",
        "processing-contracts",
        "inbound",
        "quality-inspections",
        "inventory",
        "production-orders",
        "production-scheduling",
        "production-progress",
        "production-exceptions",
        "shipments",
        "reconciliation",
        "payables",
        "receivables",
        "invoices",
        "print-center",
      ]),
      capabilityKeys: Object.freeze([
        "erp.workbench.read",
        "erp.business_dashboard.read",
        "erp.print_template.read",
        "field.party_private.read",
        "field.sales_commercial.read",
        "field.procurement_commercial.read",
        "field.finance_settlement.read",
        "customer.read",
        "supplier.read",
        "contact.read",
        "material.read",
        "process.read",
        "product.read",
        "product_sku.read",
        "sales_order.read",
        "sales_order_item.read",
        "outsourcing.order.read",
        "outsourcing.fact.read",
        "warehouse.inventory.read",
        "purchase.order.read",
        "purchase.order.approve",
        "purchase.receipt.read",
        "quality.inspection.read",
        "pmc.plan.read",
        "pmc.risk.read",
        "production.fact.read",
        "shipment.read",
        "finance.reconciliation.read",
        "finance.payable.read",
        "finance.receivable.read",
        "finance.invoice.read",
        "workflow.task.read",
        "workflow.task.supervise",
        "workflow.task.update",
        "workflow.task.approve",
        "workflow.task.reject",
        "mobile.boss.access",
      ]),
      flowResponsibilities: Object.freeze([
        "sales_order_approval.boss_approval",
        "purchase_order_approval.boss_review",
        "payment_approval.boss_approval",
      ]),
      guardrail:
        "老板角色只做审批 / 退回协同判断，不绕过具体业务 usecase 的状态、引用、幂等和事实写入校验。",
    }),
    Object.freeze({
      roleKey: "engineering",
      displayName: "工程",
      productCoreRole: "engineering",
      ownerPools: Object.freeze(["engineering"]),
      menuSurfaces: Object.freeze([
        "global-dashboard",
        "products",
        "materials",
        "processes",
        "material-bom",
        "task-board",
        "print-center",
      ]),
      capabilityKeys: Object.freeze([
        "erp.workbench.read",
        "erp.print_template.read",
        "material.read",
        "material.create",
        "material.update",
        "material.disable",
        "process.read",
        "process.create",
        "process.update",
        "product.read",
        "product.create",
        "product.update",
        "product_sku.read",
        "product_sku.create",
        "product_sku.update",
        "bom.read",
        "bom.create",
        "bom.update",
        "bom.activate",
        "workflow.task.read",
        "workflow.task.update",
        "workflow.task.complete",
        "mobile.engineering.access",
      ]),
      flowResponsibilities: Object.freeze([
        "sales_order_approval.engineering_data",
        "sales_to_production.engineering_data_ready",
      ]),
      guardrail:
        "工程补齐产品、SKU、材料、工序、BOM 等资料，不直接生成生产、库存、采购、质检、出货或财务事实。",
    }),
    Object.freeze({
      roleKey: "pmc",
      displayName: "PMC",
      productCoreRole: "pmc",
      ownerPools: Object.freeze(["pmc"]),
      menuSurfaces: Object.freeze([
        "global-dashboard",
        "business-dashboard",
        "products",
        "materials",
        "processes",
        "material-bom",
        "production-orders",
        "production-scheduling",
        "production-progress",
        "production-exceptions",
        "task-board",
      ]),
      capabilityKeys: Object.freeze([
        "erp.workbench.read",
        "erp.business_dashboard.read",
        "material.read",
        "process.read",
        "product.read",
        "product_sku.read",
        "bom.read",
        "production.fact.read",
        "production.wip.read",
        "pmc.plan.read",
        "pmc.plan.create",
        "pmc.plan.update",
        "pmc.risk.read",
        "pmc.risk.handle",
        "workflow.task.read",
        "workflow.task.supervise",
        "workflow.task.create",
        "workflow.task.update",
        "workflow.task.complete",
        "workflow.task.reject",
        "mobile.pmc.access",
      ]),
      flowResponsibilities: Object.freeze([
        "sales_order_approval.pmc_review",
        "sales_to_production.production_review",
        "production_to_inventory.wip_progress_review",
      ]),
      guardrail:
        "PMC 负责排期、风险和生产评审，不把计划状态直接写成生产完工、成品入库或出货事实。",
    }),
    Object.freeze({
      roleKey: "purchase",
      displayName: "采购",
      productCoreRole: "purchase",
      ownerPools: Object.freeze(["purchase"]),
      menuSurfaces: Object.freeze([
        "global-dashboard",
        "suppliers",
        "materials",
        "products",
        "processes",
        "material-bom",
        "inventory",
        "accessories-purchase",
        "processing-contracts",
        "inbound",
        "task-board",
        "print-center",
      ]),
      capabilityKeys: Object.freeze([
        "erp.workbench.read",
        "erp.print_template.read",
        "field.party_private.read",
        "field.procurement_commercial.read",
        "supplier.read",
        "supplier.create",
        "supplier.update",
        "contact.read",
        "contact.create",
        "contact.update",
        "contact.disable",
        "contact.set_primary",
        "material.read",
        "product.read",
        "product_sku.read",
        "process.read",
        "bom.read",
        "outsourcing.order.read",
        "outsourcing.fact.read",
        "warehouse.inventory.read",
        "purchase.order.read",
        "purchase.order.create",
        "purchase.order.update",
        "purchase.receipt.read",
        "purchase.receipt.create",
        "purchase.receipt.adjustment.read",
        "purchase.receipt.adjustment.create",
        "purchase.receipt.adjustment.post",
        "purchase.receipt.adjustment.cancel",
        "purchase.return.read",
        "purchase.return.create",
        "purchase.return.post",
        "purchase.return.cancel",
        "workflow.task.read",
        "workflow.task.update",
        "workflow.task.complete",
        "mobile.purchase.access",
      ]),
      flowResponsibilities: Object.freeze([
        "purchase_order_approval.purchase_submit",
        "purchase_to_inventory.purchase_source_ready",
      ]),
      printTemplates: Object.freeze(["material-purchase-contract"]),
      guardrail:
        "采购可维护采购承诺、供应商和采购合同打印草稿；采购退货与入库调整必须走对应 usecase 的创建、确认、取消生命周期，不能通过任务完成动作直接改库存。",
    }),
    Object.freeze({
      roleKey: "warehouse",
      displayName: "仓库",
      productCoreRole: "warehouse",
      ownerPools: Object.freeze(["warehouse"]),
      menuSurfaces: Object.freeze([
        "global-dashboard",
        "materials",
        "products",
        "inventory",
        "inbound",
        "shipping-release",
        "outbound",
        "shipments",
        "task-board",
      ]),
      capabilityKeys: Object.freeze([
        "erp.workbench.read",
        "customer.read",
        "supplier.read",
        "material.read",
        "product.read",
        "product_sku.read",
        "sales_order.read",
        "sales_order_item.read",
        "purchase.receipt.read",
        "purchase.return.read",
        "purchase.return.create",
        "purchase.return.post",
        "purchase.return.cancel",
        "purchase.receipt.adjustment.read",
        "purchase.receipt.adjustment.create",
        "purchase.receipt.adjustment.post",
        "purchase.receipt.adjustment.cancel",
        "warehouse.inventory.read",
        "warehouse.inbound.read",
        "warehouse.inbound.confirm",
        "warehouse.outbound.read",
        "warehouse.outbound.confirm",
        "shipment.read",
        "shipment.create",
        "shipment.ship",
        "shipment.cancel",
        "workflow.task.read",
        "workflow.task.update",
        "workflow.task.complete",
        "workflow.task.reject",
        "mobile.warehouse.access",
      ]),
      flowResponsibilities: Object.freeze([
        "purchase_order_approval.warehouse_prepare",
        "finished_goods_delivery.shipment_execution",
        "purchase_to_inventory.warehouse_inbound",
      ]),
      guardrail:
        "仓库执行入库、退货、入库调整与出货时必须走对应业务 usecase，不通过任务完成动作直接增减库存。当前 entitlement 仍不能办理 WIP / 委外回货登记。",
    }),
    Object.freeze({
      roleKey: "quality",
      displayName: "品质",
      productCoreRole: "quality",
      ownerPools: Object.freeze(["quality"]),
      menuSurfaces: Object.freeze([
        "global-dashboard",
        "materials",
        "products",
        "processes",
        "quality-inspections",
        "production-orders",
        "production-exceptions",
        "inventory",
        "shipments",
        "inbound",
        "processing-contracts",
        "task-board",
      ]),
      capabilityKeys: Object.freeze([
        "erp.workbench.read",
        "customer.read",
        "supplier.read",
        "contact.read",
        "material.read",
        "product.read",
        "product_sku.read",
        "process.read",
        "sales_order.read",
        "sales_order_item.read",
        "outsourcing.order.read",
        "outsourcing.fact.read",
        "purchase.receipt.read",
        "purchase.return.read",
        "purchase.return.create",
        "warehouse.inventory.read",
        "shipment.read",
        "production.wip.read",
        "quality.inspection.read",
        "quality.inspection.create",
        "quality.inspection.update",
        "quality.exception.handle",
        "workflow.task.read",
        "workflow.task.update",
        "workflow.task.complete",
        "workflow.task.reject",
        "mobile.quality.access",
      ]),
      flowResponsibilities: Object.freeze([
        "purchase_order_approval.quality_prepare",
        "finished_goods_delivery.finished_goods_qc",
        "purchase_to_inventory.incoming_qc",
        "production_to_inventory.stage_quality_gate",
      ]),
      guardrail:
        "品质可查看 WIP 来源并分别办理生产分段质检；不能安排或执行 WIP，也不能把质检任务完成自动写成库存、出货或财务事实。",
    }),
    Object.freeze({
      roleKey: "finance",
      displayName: "财务",
      productCoreRole: "finance",
      ownerPools: Object.freeze(["finance"]),
      menuSurfaces: Object.freeze([
        "global-dashboard",
        "customers",
        "suppliers",
        "reconciliation",
        "payables",
        "receivables",
        "invoices",
        "processing-contracts",
        "sales-orders",
        "quality-inspections",
        "inventory",
        "inbound",
        "shipments",
        "task-board",
        "print-center",
      ]),
      capabilityKeys: Object.freeze([
        "erp.workbench.read",
        "erp.print_template.read",
        "field.party_private.read",
        "field.sales_commercial.read",
        "field.procurement_commercial.read",
        "field.finance_settlement.read",
        "customer.read",
        "supplier.read",
        "contact.read",
        "material.read",
        "product.read",
        "product_sku.read",
        "process.read",
        "outsourcing.order.read",
        "outsourcing.fact.read",
        "purchase.receipt.read",
        "quality.inspection.read",
        "sales_order.read",
        "sales_order_item.read",
        "warehouse.inventory.read",
        "shipment.read",
        "finance.payable.read",
        "finance.payable.confirm",
        "finance.receivable.read",
        "finance.receivable.confirm",
        "finance.invoice.read",
        "finance.invoice.confirm",
        "finance.reconciliation.read",
        "finance.reconciliation.confirm",
        "finance.report.read",
        "workflow.task.read",
        "workflow.task.update",
        "workflow.task.complete",
        "workflow.task.reject",
        "mobile.finance.access",
      ]),
      flowResponsibilities: Object.freeze([
        "payment_approval.finance_submit",
        "finished_goods_delivery.finance_release",
        "finished_goods_delivery.receivable_lead",
        "delivery_to_settlement.receivable_review",
      ]),
      guardrail:
        "入库页只用于核对采购入库来源，财务不能创建、调整、确认入库或办理采购退货；财务放行、应收 / 应付草稿和对账线索不等于收付款事实，也不等于银行直连、税控、总账或完整财务系统。收付款及多单核销必须走独立 PAYMENT 动作。",
    }),
    Object.freeze({
      roleKey: "production",
      displayName: "生产 / 委外",
      productCoreRole: "production",
      ownerPools: Object.freeze(["production"]),
      menuSurfaces: Object.freeze([
        "global-dashboard",
        "suppliers",
        "materials",
        "products",
        "processes",
        "production-orders",
        "production-scheduling",
        "inventory",
        "processing-contracts",
        "production-exceptions",
        "production-progress",
        "task-board",
        "print-center",
      ]),
      capabilityKeys: Object.freeze([
        "erp.workbench.read",
        "erp.print_template.read",
        "field.party_private.read",
        "field.procurement_commercial.read",
        "supplier.read",
        "contact.read",
        "material.read",
        "process.read",
        "product.read",
        "product_sku.read",
        "outsourcing.order.read",
        "outsourcing.order.create",
        "outsourcing.order.update",
        "outsourcing.order.confirm",
        "outsourcing.fact.read",
        "outsourcing.material_issue.create",
        "outsourcing.return_receipt.create",
        "outsourcing.fact.post",
        "outsourcing.fact.cancel",
        "warehouse.inventory.read",
        "production.fact.read",
        "production.wip.read",
        "production.wip.assign",
        "production.wip.execute",
        "production.wip.rework",
        "production.completion.create",
        "production.material_issue.create",
        "production.rework.create",
        "production.fact.post",
        "production.fact.cancel",
        "pmc.plan.read",
        "pmc.plan.update",
        "pmc.risk.read",
        "pmc.risk.handle",
        "workflow.task.read",
        "workflow.task.update",
        "workflow.task.complete",
        "workflow.task.reject",
        "mobile.production.access",
      ]),
      flowResponsibilities: Object.freeze([
        "production_to_inventory.production_progress",
        "production_to_inventory.wip_execution",
        "outsourcing_return.receipt_review",
      ]),
      printTemplates: Object.freeze(["processing-contract"]),
      guardrail:
        "生产 / 委外负责加工合同源单和 WIP 安排、执行、移交及返工；不能代替品质判定、包材业务确认、成品入库、结算或付款事实。",
    }),
  ]),
});
