export const yoyoosunTrialDataFixture = Object.freeze({
  customerKey: "yoyoosun",
  fixtureKey: "yoyoosun-trial-data-fixture-v1",
  status: "preview_only",
  boundary:
    "Trial fixture is deterministic dry-run seed data for UI, print and flow tests. It must not be applied to customer production data without import approval, idempotency keys and release evidence.",
  units: Object.freeze([
    Object.freeze({ unitCode: "PCS", unitName: "个", sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]) }),
    Object.freeze({ unitCode: "M", unitName: "米", sourceIds: Object.freeze(["yoyoosun-raw-material-purchase-summary-20260602"]) }),
    Object.freeze({ unitCode: "KG", unitName: "千克", sourceIds: Object.freeze(["yoyoosun-raw-bom-26029-20260119"]) }),
    Object.freeze({ unitCode: "BOX", unitName: "箱", sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]) }),
  ]),
  customers: Object.freeze([
    Object.freeze({
      customerCode: "YOYOO-TRIAL-CUSTOMER",
      displayName: "永绅试用客户",
      contactName: "客户联系人",
      contactPhone: "13800000000",
      paymentCondition: "monthly_statement_30_days",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
    Object.freeze({
      customerCode: "YOYOO-TRIAL-EXPORT",
      displayName: "永绅试用外贸客户",
      contactName: "外贸联系人",
      contactPhone: "13800000001",
      paymentCondition: "deposit_30_balance_before_shipment",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
  ]),
  suppliers: Object.freeze([
    Object.freeze({
      supplierCode: "SUP-FABRIC-TRIAL",
      displayName: "试用辅材供应商",
      supplierType: "material",
      contactName: "成慧怡",
      contactPhone: "13900000001",
      sourceIds: Object.freeze(["yoyoosun-raw-material-purchase-summary-20260602"]),
    }),
    Object.freeze({
      supplierCode: "SUP-PROCESS-TRIAL",
      displayName: "试用加工厂",
      supplierType: "outsourcing",
      contactName: "子淳",
      contactPhone: "13900000002",
      sourceIds: Object.freeze(["yoyoosun-raw-outsourcing-summary-20260602", "yoyoosun-raw-outsourcing-contract-pdf-zichun"]),
    }),
    Object.freeze({
      supplierCode: "SUP-PACKING-TRIAL",
      displayName: "试用包材供应商",
      supplierType: "material",
      contactName: "包材联系人",
      contactPhone: "13900000003",
      sourceIds: Object.freeze(["yoyoosun-raw-material-purchase-summary-20260602"]),
    }),
  ]),
  materials: Object.freeze([
    Object.freeze({
      materialCode: "MAT-26029-FABRIC",
      materialName: "夜樱烬色主面料",
      spec: "26029#",
      unitCode: "M",
      sourceIds: Object.freeze(["yoyoosun-raw-bom-26029-20260119"]),
    }),
    Object.freeze({
      materialCode: "MAT-26204-FILLING",
      materialName: "抱抱猴子填充棉",
      spec: "26204#",
      unitCode: "KG",
      sourceIds: Object.freeze(["yoyoosun-raw-bom-26204-20260410"]),
    }),
    Object.freeze({
      materialCode: "MAT-26029-EYE",
      materialName: "夜樱烬色安全眼",
      spec: "12mm",
      unitCode: "PCS",
      sourceIds: Object.freeze(["yoyoosun-raw-bom-26029-20260119"]),
    }),
    Object.freeze({
      materialCode: "MAT-26204-CARTON",
      materialName: "抱抱猴子外箱",
      spec: "12只装",
      unitCode: "BOX",
      sourceIds: Object.freeze(["yoyoosun-raw-bom-26204-20260410"]),
    }),
    Object.freeze({
      materialCode: "MAT-COMMON-LABEL",
      materialName: "通用洗水标",
      spec: "双语",
      unitCode: "PCS",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
  ]),
  products: Object.freeze([
    Object.freeze({
      productNo: "26029",
      productName: "夜樱烬色玩偶",
      skuNo: "26029-STD",
      sourceIds: Object.freeze(["yoyoosun-raw-bom-26029-20260119"]),
    }),
    Object.freeze({
      productNo: "26204",
      productName: "抱抱猴子玩偶",
      skuNo: "26204-STD",
      sourceIds: Object.freeze(["yoyoosun-raw-bom-26204-20260410"]),
    }),
    Object.freeze({
      productNo: "26029-L",
      productName: "夜樱烬色大号玩偶",
      skuNo: "26029-LARGE",
      sourceIds: Object.freeze(["yoyoosun-raw-bom-26029-20260119"]),
    }),
  ]),
  warehouses: Object.freeze([
    Object.freeze({ warehouseCode: "YOYOO-MAIN", warehouseName: "永绅试用仓", sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]) }),
    Object.freeze({ warehouseCode: "YOYOO-QC-HOLD", warehouseName: "永绅试用待检仓", sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]) }),
    Object.freeze({ warehouseCode: "YOYOO-FINISHED", warehouseName: "永绅试用成品仓", sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]) }),
  ]),
  bomVersions: Object.freeze([
    Object.freeze({
      bomNo: "BOM-26029-TRIAL",
      productNo: "26029",
      skuNo: "26029-STD",
      versionNo: "2026-01-19",
      lines: Object.freeze([
        Object.freeze({ materialCode: "MAT-26029-FABRIC", usageQty: "0.80", unitCode: "M" }),
        Object.freeze({ materialCode: "MAT-26029-EYE", usageQty: "2", unitCode: "PCS" }),
        Object.freeze({ materialCode: "MAT-COMMON-LABEL", usageQty: "1", unitCode: "PCS" }),
      ]),
      sourceIds: Object.freeze(["yoyoosun-raw-bom-26029-20260119"]),
    }),
    Object.freeze({
      bomNo: "BOM-26204-TRIAL",
      productNo: "26204",
      skuNo: "26204-STD",
      versionNo: "2026-04-10",
      lines: Object.freeze([
        Object.freeze({ materialCode: "MAT-26204-FILLING", usageQty: "0.35", unitCode: "KG" }),
        Object.freeze({ materialCode: "MAT-26204-CARTON", usageQty: "0.083333", unitCode: "BOX" }),
        Object.freeze({ materialCode: "MAT-COMMON-LABEL", usageQty: "1", unitCode: "PCS" }),
      ]),
      sourceIds: Object.freeze(["yoyoosun-raw-bom-26204-20260410"]),
    }),
  ]),
  salesOrders: Object.freeze([
    Object.freeze({
      orderNo: "SO-YOYO-TRIAL-001",
      customerCode: "YOYOO-TRIAL-CUSTOMER",
      productNo: "26029",
      skuNo: "26029-STD",
      quantity: "120",
      lifecycleStatus: "draft",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
    Object.freeze({
      orderNo: "SO-YOYO-TRIAL-002",
      customerCode: "YOYOO-TRIAL-EXPORT",
      productNo: "26204",
      skuNo: "26204-STD",
      quantity: "240",
      lifecycleStatus: "active",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
    Object.freeze({
      orderNo: "SO-YOYO-TRIAL-003",
      customerCode: "YOYOO-TRIAL-CUSTOMER",
      productNo: "26029-L",
      skuNo: "26029-LARGE",
      quantity: "36",
      lifecycleStatus: "cancelled",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
  ]),
  purchaseOrders: Object.freeze([
    Object.freeze({
      purchaseOrderNo: "PO-YOYO-TRIAL-001",
      supplierCode: "SUP-FABRIC-TRIAL",
      expectedArrivalDate: "2026-07-15",
      printTemplateKey: "material-purchase-contract",
      lines: Object.freeze([
        Object.freeze({
          productOrderNo: "SO-YOYO-TRIAL-001",
          productNo: "26029",
          productName: "夜樱烬色玩偶",
          materialCode: "MAT-26029-FABRIC",
          materialName: "夜樱烬色主面料",
          unitCode: "M",
          quantity: "96",
          unitPrice: "8.500",
          amount: "816.00",
        }),
        Object.freeze({
          productOrderNo: "SO-YOYO-TRIAL-002",
          productNo: "26204",
          productName: "抱抱猴子玩偶",
          materialCode: "MAT-26204-CARTON",
          materialName: "抱抱猴子外箱",
          unitCode: "BOX",
          quantity: "20",
          unitPrice: "4.200",
          amount: "84.00",
        }),
      ]),
      sourceIds: Object.freeze(["yoyoosun-raw-material-purchase-summary-20260602", "yoyoosun-raw-purchase-contract-photo-20260421-jpeg"]),
    }),
    Object.freeze({
      purchaseOrderNo: "PO-YOYO-TRIAL-002",
      supplierCode: "SUP-PACKING-TRIAL",
      expectedArrivalDate: "2026-07-18",
      printTemplateKey: "material-purchase-contract",
      lines: Object.freeze([
        Object.freeze({
          productOrderNo: "SO-YOYO-TRIAL-002",
          productNo: "26204",
          productName: "抱抱猴子玩偶",
          materialCode: "MAT-COMMON-LABEL",
          materialName: "通用洗水标",
          unitCode: "PCS",
          quantity: "260",
          unitPrice: "0.120",
          amount: "31.20",
        }),
      ]),
      sourceIds: Object.freeze(["yoyoosun-raw-material-purchase-summary-20260602"]),
    }),
  ]),
  outsourcingOrders: Object.freeze([
    Object.freeze({
      outsourcingOrderNo: "OS-YOYO-TRIAL-001",
      processorCode: "SUP-PROCESS-TRIAL",
      returnDate: "2026-07-20",
      printTemplateKey: "processing-contract",
      lines: Object.freeze([
        Object.freeze({
          productOrderNo: "SO-YOYO-TRIAL-001",
          productNo: "26029",
          productName: "夜樱烬色玩偶",
          processName: "车缝加工",
          processCategory: "缝制",
          unitCode: "PCS",
          quantity: "120",
          unitPrice: "3.200",
          amount: "384.00",
        }),
      ]),
      sourceIds: Object.freeze(["yoyoosun-raw-outsourcing-summary-20260602", "yoyoosun-raw-outsourcing-contract-pdf-zichun"]),
    }),
    Object.freeze({
      outsourcingOrderNo: "OS-YOYO-TRIAL-002",
      processorCode: "SUP-PROCESS-TRIAL",
      returnDate: "2026-07-25",
      printTemplateKey: "processing-contract",
      lines: Object.freeze([
        Object.freeze({
          productOrderNo: "SO-YOYO-TRIAL-002",
          productNo: "26204",
          productName: "抱抱猴子玩偶",
          processName: "裁片IQC",
          processCategory: "裁片质检",
          unitCode: "PCS",
          quantity: "240",
          unitPrice: "0.850",
          amount: "204.00",
        }),
        Object.freeze({
          productOrderNo: "SO-YOYO-TRIAL-002",
          productNo: "26204",
          productName: "抱抱猴子玩偶",
          processName: "贴合",
          processCategory: "贴合",
          unitCode: "PCS",
          quantity: "240",
          unitPrice: "1.100",
          amount: "264.00",
        }),
      ]),
      sourceIds: Object.freeze(["yoyoosun-raw-outsourcing-summary-20260602"]),
    }),
  ]),
  purchaseReceipts: Object.freeze([
    Object.freeze({
      receiptNo: "PR-YOYO-TRIAL-001",
      purchaseOrderNo: "PO-YOYO-TRIAL-001",
      warehouseCode: "YOYOO-MAIN",
      status: "draft",
      sourceIds: Object.freeze(["yoyoosun-raw-material-purchase-summary-20260602"]),
    }),
    Object.freeze({
      receiptNo: "PR-YOYO-TRIAL-002",
      purchaseOrderNo: "PO-YOYO-TRIAL-002",
      warehouseCode: "YOYOO-QC-HOLD",
      status: "posted",
      sourceIds: Object.freeze(["yoyoosun-raw-material-purchase-summary-20260602"]),
    }),
  ]),
  qualityInspections: Object.freeze([
    Object.freeze({
      inspectionNo: "QI-YOYO-TRIAL-001",
      sourceNo: "PR-YOYO-TRIAL-001",
      result: "pending",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
    Object.freeze({
      inspectionNo: "QI-YOYO-TRIAL-002",
      sourceNo: "PR-YOYO-TRIAL-002",
      result: "passed",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
    Object.freeze({
      inspectionNo: "QI-YOYO-TRIAL-003",
      sourceNo: "OS-YOYO-TRIAL-002",
      result: "rejected",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
  ]),
  inventoryLots: Object.freeze([
    Object.freeze({
      lotNo: "LOT-YOYO-TRIAL-001",
      materialCode: "MAT-26029-FABRIC",
      warehouseCode: "YOYOO-MAIN",
      quantity: "0",
      status: "pending_inbound",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
    Object.freeze({
      lotNo: "LOT-YOYO-TRIAL-002",
      materialCode: "MAT-COMMON-LABEL",
      warehouseCode: "YOYOO-QC-HOLD",
      quantity: "260",
      status: "qc_hold",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
    Object.freeze({
      lotNo: "LOT-YOYO-TRIAL-003",
      materialCode: "MAT-26204-CARTON",
      warehouseCode: "YOYOO-MAIN",
      quantity: "20",
      status: "available",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
  ]),
  shipments: Object.freeze([
    Object.freeze({
      shipmentNo: "SH-YOYO-TRIAL-001",
      salesOrderNo: "SO-YOYO-TRIAL-001",
      warehouseCode: "YOYOO-MAIN",
      status: "draft",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
    Object.freeze({
      shipmentNo: "SH-YOYO-TRIAL-002",
      salesOrderNo: "SO-YOYO-TRIAL-002",
      warehouseCode: "YOYOO-FINISHED",
      status: "shipped",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
    Object.freeze({
      shipmentNo: "SH-YOYO-TRIAL-003",
      salesOrderNo: "SO-YOYO-TRIAL-003",
      warehouseCode: "YOYOO-FINISHED",
      status: "cancelled",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
  ]),
  financeDrafts: Object.freeze([
    Object.freeze({
      financeDraftNo: "AR-YOYO-TRIAL-001",
      sourceNo: "SH-YOYO-TRIAL-001",
      factType: "receivable_draft",
      status: "draft",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
    Object.freeze({
      financeDraftNo: "AR-YOYO-TRIAL-002",
      sourceNo: "SH-YOYO-TRIAL-002",
      factType: "receivable_posted",
      status: "posted",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
    Object.freeze({
      financeDraftNo: "AP-YOYO-TRIAL-001",
      sourceNo: "OS-YOYO-TRIAL-002",
      factType: "payable_draft",
      status: "draft",
      sourceIds: Object.freeze(["__synthetic_yoyoosun_trial__"]),
    }),
  ]),
  workflowTasks: Object.freeze([
    Object.freeze({
      taskCode: "WF-YOYO-TRIAL-SALES-001",
      taskGroup: "sales_order_approval",
      sourceNo: "SO-YOYO-TRIAL-001",
      ownerRoleKey: "sales",
      taskStatusKey: "ready",
      sourceIds: Object.freeze(["yoyoosun-raw-role-workflow-v3-20260413"]),
    }),
    Object.freeze({
      taskCode: "WF-YOYO-TRIAL-PURCHASE-001",
      taskGroup: "purchase_order_approval",
      sourceNo: "PO-YOYO-TRIAL-001",
      ownerRoleKey: "purchasing",
      taskStatusKey: "ready",
      sourceIds: Object.freeze(["yoyoosun-raw-role-workflow-v3-20260413"]),
    }),
    Object.freeze({
      taskCode: "WF-YOYO-TRIAL-BOSS-001",
      taskGroup: "order_approval",
      sourceNo: "SO-YOYO-TRIAL-002",
      ownerRoleKey: "boss",
      taskStatusKey: "ready",
      sourceIds: Object.freeze(["yoyoosun-raw-role-workflow-v3-20260413"]),
    }),
    Object.freeze({
      taskCode: "WF-YOYO-TRIAL-QC-001",
      taskGroup: "finished_goods_qc",
      sourceNo: "PR-YOYO-TRIAL-002",
      ownerRoleKey: "quality",
      taskStatusKey: "blocked",
      sourceIds: Object.freeze(["yoyoosun-raw-role-workflow-v3-20260413"]),
    }),
    Object.freeze({
      taskCode: "WF-YOYO-TRIAL-WH-001",
      taskGroup: "shipment_release",
      sourceNo: "SH-YOYO-TRIAL-002",
      ownerRoleKey: "warehouse",
      taskStatusKey: "done",
      sourceIds: Object.freeze(["yoyoosun-raw-role-workflow-v3-20260413"]),
    }),
  ]),
});
