const SYNTHETIC_SOURCE_IDS = Object.freeze(["__synthetic_yoyoosun_trial__"]);

export const yoyoosunTrialDataFixture = Object.freeze({
  customerKey: "yoyoosun",
  fixtureKey: "__synthetic_yoyoosun_trial__",
  status: "preview_only",
  boundary:
    "Every value in this deterministic fixture is synthetic dry-run seed data for UI, print and flow tests. It has no row-level link to private customer sources and must not be applied to customer production data.",
  units: Object.freeze([
    Object.freeze({ unitCode: "PCS", unitName: "个", sourceIds: SYNTHETIC_SOURCE_IDS }),
    Object.freeze({ unitCode: "M", unitName: "米", sourceIds: SYNTHETIC_SOURCE_IDS }),
    Object.freeze({ unitCode: "KG", unitName: "千克", sourceIds: SYNTHETIC_SOURCE_IDS }),
    Object.freeze({ unitCode: "BOX", unitName: "箱", sourceIds: SYNTHETIC_SOURCE_IDS }),
  ]),
  customers: Object.freeze([
    Object.freeze({
      customerCode: "SIM-CUSTOMER-001",
      displayName: "样例·美悦礼品",
      contactName: "业务小陈",
      contactPhone: "13800000000",
      paymentCondition: "monthly_statement_30_days",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      customerCode: "SIM-CUSTOMER-002",
      displayName: "样例·森野文创",
      contactName: "收货小李",
      contactPhone: "13800000001",
      paymentCondition: "deposit_30_balance_before_shipment",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  suppliers: Object.freeze([
    Object.freeze({
      supplierCode: "SIM-SUP-MATERIAL-001",
      displayName: "样例·嘉顺布行",
      supplierType: "material",
      contactName: "业务小周",
      contactPhone: "13900000001",
      address: "样例地址·主料区",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      supplierCode: "SIM-SUP-PROCESS-001",
      displayName: "样例·顺成车缝",
      supplierType: "outsourcing",
      contactName: "加工小吴",
      contactPhone: "13900000002",
      address: "样例地址·加工区",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      supplierCode: "SIM-SUP-MATERIAL-002",
      displayName: "样例·安达包装",
      supplierType: "material",
      contactName: "送货小林",
      contactPhone: "13900000003",
      address: "样例地址·包材区",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  materials: Object.freeze([
    Object.freeze({
      materialCode: "SIM-MAT-FABRIC-001",
      materialName: "粉色短毛绒",
      category: "面料",
      vendorCode: "SIM-VENDOR-FABRIC-001",
      spec: "150cm幅宽 / 320g",
      color: "粉色",
      unitCode: "M",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      materialCode: "SIM-MAT-FILLING-001",
      materialName: "白色填充棉",
      category: "填充",
      vendorCode: "SIM-VENDOR-FILLING-001",
      spec: "A级弹性棉",
      color: "本白",
      unitCode: "KG",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      materialCode: "SIM-MAT-EYE-001",
      materialName: "12mm黑色眼睛",
      category: "胶件",
      vendorCode: "SIM-VENDOR-EYE-001",
      spec: "12mm",
      color: "黑色",
      unitCode: "PCS",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      materialCode: "SIM-MAT-CARTON-001",
      materialName: "12只装外箱",
      category: "包材",
      vendorCode: "SIM-VENDOR-CARTON-001",
      spec: "12只装",
      color: "牛皮纸",
      unitCode: "BOX",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      materialCode: "SIM-MAT-LABEL-001",
      materialName: "白底洗水标",
      category: "辅料",
      vendorCode: "SIM-VENDOR-LABEL-001",
      spec: "双语",
      color: "白底黑字",
      unitCode: "PCS",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  products: Object.freeze([
    Object.freeze({
      productNo: "SIM-PROD-001",
      productName: "云朵小熊",
      skuNo: "SIM-SKU-001",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      productNo: "SIM-PROD-002",
      productName: "星星挂兔",
      skuNo: "SIM-SKU-002",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      productNo: "SIM-PROD-003",
      productName: "云朵小熊大号",
      skuNo: "SIM-SKU-003",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  warehouses: Object.freeze([
    Object.freeze({
      warehouseCode: "SIM-WH-RAW",
      warehouseName: "样例·主料仓",
      warehouseType: "RAW_MATERIAL",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      warehouseCode: "SIM-WH-FINISHED",
      warehouseName: "样例·成品仓",
      warehouseType: "FINISHED_GOODS",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      warehouseCode: "SIM-WH-OTHER",
      warehouseName: "样例·其他仓",
      warehouseType: "OTHER",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      warehouseCode: "SIM-WH-QC-HOLD",
      warehouseName: "样例·待检仓",
      warehouseType: "QC_HOLD",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  bomVersions: Object.freeze([
    Object.freeze({
      bomNo: "SIM-BOM-001",
      productNo: "SIM-PROD-001",
      skuNo: "SIM-SKU-001",
      versionNo: "SIM-V1",
      sourceOrderNo: "SIM-SOURCE-ORDER-001",
      quantityText: "100",
      spareText: "含损耗备品",
      printDate: "2026-01-01",
      designer: "工程小陈",
      maker: "制单小李",
      auditor: "工程审核",
      hairDirection: "单方向",
      lines: Object.freeze([
        Object.freeze({
          materialCode: "SIM-MAT-FABRIC-001",
          usageQty: "0.80",
          unitCode: "M",
          position: "脸*1",
          pieceCount: "1",
          lossRate: "10",
          totalUsage: "88.00",
          processBase: "贴12g纸朴",
          processMethod: "热裁",
          note: "按色卡方向裁片",
        }),
        Object.freeze({
          materialCode: "SIM-MAT-EYE-001",
          usageQty: "2",
          unitCode: "PCS",
          position: "眼*2",
          pieceCount: "2",
          lossRate: "0",
          totalUsage: "200",
          processBase: "常规配件",
          processMethod: "眼睛配套",
        }),
        Object.freeze({
          materialCode: "SIM-MAT-LABEL-001",
          usageQty: "1",
          unitCode: "PCS",
          position: "洗水标*1",
          pieceCount: "1",
          lossRate: "5",
          totalUsage: "105.00",
          processBase: "常规车缝",
          processMethod: "车缝",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      bomNo: "SIM-BOM-002",
      productNo: "SIM-PROD-002",
      skuNo: "SIM-SKU-002",
      versionNo: "SIM-V2",
      sourceOrderNo: "SIM-SOURCE-ORDER-002",
      quantityText: "200",
      spareText: "备品 10",
      printDate: "2026-01-02",
      designer: "工程小周",
      maker: "制单小李",
      auditor: "工程审核",
      hairDirection: "单方向",
      lines: Object.freeze([
        Object.freeze({
          materialCode: "SIM-MAT-FILLING-001",
          usageQty: "0.35",
          unitCode: "KG",
          position: "填充",
          pieceCount: "1",
          lossRate: "10",
          totalUsage: "77.00",
          processBase: "无特殊底料",
          processMethod: "充棉",
        }),
        Object.freeze({
          materialCode: "SIM-MAT-CARTON-001",
          usageQty: "0.083333",
          unitCode: "BOX",
          position: "包装",
          pieceCount: "1",
          lossRate: "0",
          totalUsage: "16.67",
          processBase: "常规包装",
          processMethod: "包装",
        }),
        Object.freeze({
          materialCode: "SIM-MAT-LABEL-001",
          usageQty: "1",
          unitCode: "PCS",
          position: "洗水标*1",
          pieceCount: "1",
          lossRate: "5",
          totalUsage: "210.00",
          processBase: "常规车缝",
          processMethod: "车缝",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  salesOrders: Object.freeze([
    Object.freeze({
      orderNo: "SIM-SO-001",
      customerCode: "SIM-CUSTOMER-001",
      productNo: "SIM-PROD-001",
      skuNo: "SIM-SKU-001",
      quantity: "120",
      lifecycleStatus: "draft",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      orderNo: "SIM-SO-002",
      customerCode: "SIM-CUSTOMER-002",
      productNo: "SIM-PROD-002",
      skuNo: "SIM-SKU-002",
      quantity: "240",
      lifecycleStatus: "active",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      orderNo: "SIM-SO-003",
      customerCode: "SIM-CUSTOMER-001",
      productNo: "SIM-PROD-003",
      skuNo: "SIM-SKU-003",
      quantity: "36",
      lifecycleStatus: "cancelled",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  purchaseOrders: Object.freeze([
    Object.freeze({
      purchaseOrderNo: "SIM-PO-001",
      supplierCode: "SIM-SUP-MATERIAL-001",
      orderDate: "2026-06-13",
      expectedArrivalDate: "2026-06-24",
      printTemplateKey: "material-purchase-contract",
      contractPartySnapshot: Object.freeze({
        buyerCompany: "样例玩具厂",
        buyerContact: "采购小周",
        buyerPhone: "0769-00000001",
        buyerAddress: "样例地址·采购部",
        buyerSigner: "采购小周",
      }),
      lines: Object.freeze([
        Object.freeze({
          subjectType: "PRODUCT",
          productOrderNo: "SIM-SO-001",
          productNo: "SIM-PROD-001",
          productName: "云朵小熊",
          materialCode: "SIM-MAT-FABRIC-001",
          materialName: "粉色短毛绒",
          unitCode: "M",
          quantity: "96",
          unitPrice: "8.500",
          amount: "816.00",
          note: "分批送货，标明款号。",
        }),
        Object.freeze({
          subjectType: "PRODUCT",
          productOrderNo: "SIM-SO-002",
          productNo: "SIM-PROD-002",
          productName: "星星挂兔",
          materialCode: "SIM-MAT-CARTON-001",
          materialName: "12只装外箱",
          unitCode: "BOX",
          quantity: "20",
          unitPrice: "4.200",
          amount: "84.00",
          note: "外箱按订单分开。",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      purchaseOrderNo: "SIM-PO-002",
      supplierCode: "SIM-SUP-MATERIAL-002",
      orderDate: "2026-06-13",
      expectedArrivalDate: "2026-06-24",
      printTemplateKey: "material-purchase-contract",
      contractPartySnapshot: Object.freeze({
        buyerCompany: "样例玩具厂",
        buyerContact: "采购小周",
        buyerPhone: "0769-00000001",
        buyerAddress: "样例地址·采购部",
        buyerSigner: "采购小周",
      }),
      lines: Object.freeze([
        Object.freeze({
          subjectType: "PRODUCT",
          productOrderNo: "SIM-SO-002",
          productNo: "SIM-PROD-002",
          productName: "星星挂兔",
          materialCode: "SIM-MAT-LABEL-001",
          materialName: "白底洗水标",
          unitCode: "PCS",
          quantity: "260",
          unitPrice: "0.120",
          amount: "31.20",
          note: "洗水标随货。",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  outsourcingOrders: Object.freeze([
    Object.freeze({
      outsourcingOrderNo: "SIM-OS-001",
      sourceOrderNo: "SIM-SO-001",
      processorCode: "SIM-SUP-PROCESS-001",
      orderDate: "2026-06-19",
      returnDate: "2026-06-26",
      printTemplateKey: "processing-contract",
      contractPartySnapshot: Object.freeze({
        buyerCompany: "样例玩具厂",
        buyerContact: "外发小吴",
        buyerPhone: "0769-00000002",
        buyerAddress: "样例地址·外发部",
        buyerSigner: "外发小吴",
      }),
      lines: Object.freeze([
        Object.freeze({
          productOrderNo: "SIM-SO-001",
          productNo: "SIM-PROD-001",
          productName: "云朵小熊",
          processingItem: "本体",
          processName: "本体车缝",
          processCategory: "车缝",
          unitCode: "PCS",
          quantity: "120",
          unitPrice: "3.200",
          amount: "384.00",
          note: "按订单分批回货，车缝回货检验合格后转手工。",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      outsourcingOrderNo: "SIM-OS-002",
      processorCode: "SIM-SUP-PROCESS-001",
      orderDate: "2026-06-19",
      returnDate: "2026-06-26",
      printTemplateKey: "processing-contract",
      contractPartySnapshot: Object.freeze({
        buyerCompany: "样例玩具厂",
        buyerContact: "外发小吴",
        buyerPhone: "0769-00000002",
        buyerAddress: "样例地址·外发部",
        buyerSigner: "外发小吴",
      }),
      lines: Object.freeze([
        Object.freeze({
          productOrderNo: "SIM-SO-002",
          productNo: "SIM-PROD-002",
          productName: "星星挂兔",
          processingItem: "裁片",
          processName: "裁片加工",
          processCategory: "机裁",
          unitCode: "PCS",
          quantity: "240",
          unitPrice: "0.850",
          amount: "204.00",
          note: "回货后交品质检验，合格后才可继续。",
        }),
        Object.freeze({
          productOrderNo: "SIM-SO-002",
          productNo: "SIM-PROD-002",
          productName: "星星挂兔",
          processingItem: "贴合部位",
          processName: "贴合",
          processCategory: "贴合",
          unitCode: "PCS",
          quantity: "240",
          unitPrice: "1.100",
          amount: "264.00",
          note: "回货时标明工序。",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      outsourcingOrderNo: "SIM-OS-003",
      sourceOrderNo: "SIM-PO-001",
      processorCode: "SIM-SUP-PROCESS-001",
      orderDate: "2026-06-20",
      returnDate: "2026-06-27",
      printTemplateKey: "processing-contract",
      contractPartySnapshot: Object.freeze({
        buyerCompany: "样例玩具厂",
        buyerContact: "外发小吴",
        buyerPhone: "0769-00000002",
        buyerAddress: "样例地址·外发部",
        buyerSigner: "外发小吴",
      }),
      lines: Object.freeze([
        Object.freeze({
          subjectType: "MATERIAL",
          materialCode: "SIM-MAT-FABRIC-001",
          materialName: "粉色短毛绒",
          processingItem: "复合面料",
          processName: "布料复合",
          processCategory: "布料加工",
          unitCode: "M",
          quantity: "180",
          unitPrice: "1.600",
          amount: "288.00",
          note: "按批次加工，回货后先检验。",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      outsourcingOrderNo: "SIM-OS-004",
      sourceOrderNo: "SIM-SO-001",
      processorCode: "SIM-SUP-PROCESS-001",
      orderDate: "2026-06-27",
      returnDate: "2026-07-03",
      printTemplateKey: "processing-contract",
      contractPartySnapshot: Object.freeze({
        buyerCompany: "样例玩具厂",
        buyerContact: "外发小吴",
        buyerPhone: "0769-00000002",
        buyerAddress: "样例地址·外发部",
        buyerSigner: "外发小吴",
      }),
      lines: Object.freeze([
        Object.freeze({
          subjectType: "PRODUCT",
          productOrderNo: "SIM-SO-001",
          productNo: "SIM-PROD-001",
          productName: "云朵小熊",
          processingItem: "收口部位",
          processName: "手工收口",
          processCategory: "手工",
          unitCode: "PCS",
          quantity: "120",
          unitPrice: "1.250",
          amount: "150.00",
          note: "车缝检验合格后开始手工，分批回货并标明款号。",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  purchaseReceipts: Object.freeze([
    Object.freeze({
      receiptNo: "SIM-PR-001",
      purchaseOrderNo: "SIM-PO-001",
      warehouseCode: "SIM-WH-RAW",
      status: "draft",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      receiptNo: "SIM-PR-002",
      purchaseOrderNo: "SIM-PO-002",
      warehouseCode: "SIM-WH-QC-HOLD",
      status: "posted",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  qualityInspections: Object.freeze([
    Object.freeze({
      inspectionNo: "SIM-QI-001",
      sourceNo: "SIM-PR-001",
      result: "pending",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      inspectionNo: "SIM-QI-002",
      sourceNo: "SIM-PR-002",
      result: "passed",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      inspectionNo: "SIM-QI-003",
      sourceNo: "SIM-OS-002",
      result: "rejected",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      inspectionNo: "SIM-QI-004",
      sourceNo: "SIM-OS-001",
      result: "passed",
      inspectedAt: "2026-06-26",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  inventoryLots: Object.freeze([
    Object.freeze({
      lotNo: "SIM-LOT-001",
      materialCode: "SIM-MAT-FABRIC-001",
      warehouseCode: "SIM-WH-RAW",
      quantity: "0",
      status: "pending_inbound",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      lotNo: "SIM-LOT-002",
      materialCode: "SIM-MAT-LABEL-001",
      warehouseCode: "SIM-WH-QC-HOLD",
      quantity: "260",
      status: "qc_hold",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      lotNo: "SIM-LOT-003",
      materialCode: "SIM-MAT-CARTON-001",
      warehouseCode: "SIM-WH-OTHER",
      quantity: "20",
      status: "available",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  shipments: Object.freeze([
    Object.freeze({
      shipmentNo: "SIM-SH-001",
      salesOrderNo: "SIM-SO-001",
      warehouseCode: "SIM-WH-FINISHED",
      status: "draft",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      shipmentNo: "SIM-SH-002",
      salesOrderNo: "SIM-SO-002",
      warehouseCode: "SIM-WH-FINISHED",
      status: "shipped",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      shipmentNo: "SIM-SH-003",
      salesOrderNo: "SIM-SO-003",
      warehouseCode: "SIM-WH-FINISHED",
      status: "cancelled",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  financeDrafts: Object.freeze([
    Object.freeze({
      financeDraftNo: "SIM-AR-001",
      sourceNo: "SIM-SH-001",
      factType: "receivable_draft",
      status: "draft",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      financeDraftNo: "SIM-AR-002",
      sourceNo: "SIM-SH-002",
      factType: "receivable_posted",
      status: "posted",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      financeDraftNo: "SIM-AP-001",
      sourceNo: "SIM-OS-001",
      factType: "payable_draft",
      status: "draft",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  productionWipScenarios: Object.freeze([
    Object.freeze({
      scenarioNo: "SIM-PWIP-001",
      scenarioType: "all_inhouse_customer_inspection_not_applicable",
      productionOrderNo: "SIM-MO-PWIP-001",
      productNo: "SIM-PROD-001",
      parentBatchNo: "SIM-WIP-BATCH-001",
      quantity: "120",
      stepExecutions: Object.freeze([
        Object.freeze({
          executionNo: "SIM-WIP-EXEC-001-SEW",
          stepCode: "sewing",
          sequenceNo: 3,
          executionMode: "in_house",
          movementType: "wip_transfer",
          status: "completed",
          sourceIds: SYNTHETIC_SOURCE_IDS,
        }),
        Object.freeze({
          executionNo: "SIM-WIP-EXEC-001-HAND",
          stepCode: "handwork",
          sequenceNo: 5,
          executionMode: "in_house",
          movementType: "wip_transfer",
          status: "completed",
          sourceIds: SYNTHETIC_SOURCE_IDS,
        }),
      ]),
      customerInspection: Object.freeze({
        conditionRecordNo: "SIM-CI-CONDITION-001",
        ruleSourceNo: "SIM-SO-001",
        required: false,
        status: "not_applicable",
        finalPackagingAllowed: true,
        sourceIds: SYNTHETIC_SOURCE_IDS,
      }),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      scenarioNo: "SIM-PWIP-002",
      scenarioType: "sewing_outsourced_handwork_inhouse",
      productionOrderNo: "SIM-MO-PWIP-002",
      productNo: "SIM-PROD-001",
      parentBatchNo: "SIM-WIP-BATCH-002",
      quantity: "120",
      stepExecutions: Object.freeze([
        Object.freeze({
          executionNo: "SIM-WIP-EXEC-002-SEW",
          stepCode: "sewing",
          sequenceNo: 3,
          executionMode: "outsourced",
          movementType: "outsourcing_return",
          status: "returned",
          sourceIds: SYNTHETIC_SOURCE_IDS,
        }),
        Object.freeze({
          executionNo: "SIM-WIP-EXEC-002-HAND",
          stepCode: "handwork",
          sequenceNo: 5,
          executionMode: "in_house",
          movementType: "wip_transfer",
          status: "ready",
          sourceIds: SYNTHETIC_SOURCE_IDS,
        }),
      ]),
      qualityGate: Object.freeze({
        inspectionNo: "SIM-WIP-QI-002",
        gateCode: "shell_inspection",
        batchNo: "SIM-WIP-BATCH-002",
        result: "passed",
        sourceIds: SYNTHETIC_SOURCE_IDS,
      }),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      scenarioNo: "SIM-PWIP-003",
      scenarioType: "sewing_inhouse_handwork_outsourced",
      productionOrderNo: "SIM-MO-PWIP-003",
      productNo: "SIM-PROD-002",
      parentBatchNo: "SIM-WIP-BATCH-003",
      quantity: "240",
      stepExecutions: Object.freeze([
        Object.freeze({
          executionNo: "SIM-WIP-EXEC-003-SEW",
          stepCode: "sewing",
          sequenceNo: 3,
          executionMode: "in_house",
          movementType: "wip_transfer",
          status: "completed",
          sourceIds: SYNTHETIC_SOURCE_IDS,
        }),
        Object.freeze({
          executionNo: "SIM-WIP-EXEC-003-HAND",
          stepCode: "handwork",
          sequenceNo: 5,
          executionMode: "outsourced",
          movementType: "outsourcing_return",
          status: "returned",
          sourceIds: SYNTHETIC_SOURCE_IDS,
        }),
      ]),
      qualityGate: Object.freeze({
        inspectionNo: "SIM-WIP-QI-003",
        gateCode: "shell_inspection",
        batchNo: "SIM-WIP-BATCH-003",
        result: "passed",
        sourceIds: SYNTHETIC_SOURCE_IDS,
      }),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      scenarioNo: "SIM-PWIP-004",
      scenarioType: "same_step_split",
      productionOrderNo: "SIM-MO-PWIP-004",
      productNo: "SIM-PROD-001",
      parentBatchNo: "SIM-WIP-BATCH-004",
      stepCode: "sewing",
      quantity: "120",
      allocations: Object.freeze([
        Object.freeze({
          allocationNo: "SIM-WIP-ALLOC-004-A",
          childBatchNo: "SIM-WIP-BATCH-004-A",
          executionMode: "in_house",
          quantity: "50",
          sourceIds: SYNTHETIC_SOURCE_IDS,
        }),
        Object.freeze({
          allocationNo: "SIM-WIP-ALLOC-004-B",
          childBatchNo: "SIM-WIP-BATCH-004-B",
          executionMode: "outsourced",
          quantity: "70",
          sourceIds: SYNTHETIC_SOURCE_IDS,
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      scenarioNo: "SIM-PWIP-005",
      scenarioType: "shell_inspection_rework",
      productionOrderNo: "SIM-MO-PWIP-005",
      productNo: "SIM-PROD-001",
      parentBatchNo: "SIM-WIP-BATCH-005",
      quantity: "120",
      qualityGate: Object.freeze({
        inspectionNo: "SIM-WIP-QI-005",
        gateCode: "shell_inspection",
        batchNo: "SIM-WIP-BATCH-005-A",
        result: "rejected",
        blockedStepCode: "handwork",
        sourceIds: SYNTHETIC_SOURCE_IDS,
      }),
      rework: Object.freeze({
        reworkNo: "SIM-WIP-REWORK-005",
        originalExecutionNo: "SIM-WIP-EXEC-005-SEW-ORIGINAL",
        newExecutionNo: "SIM-WIP-EXEC-005-SEW-REWORK",
        targetStepCode: "sewing",
        quantity: "20",
        reason: "针距不符，退回车缝返工。",
        sourceIds: SYNTHETIC_SOURCE_IDS,
      }),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      scenarioNo: "SIM-PWIP-006",
      scenarioType: "needle_inspection_rejected",
      productionOrderNo: "SIM-MO-PWIP-006",
      productNo: "SIM-PROD-002",
      parentBatchNo: "SIM-WIP-BATCH-006",
      quantity: "240",
      qualityGate: Object.freeze({
        inspectionNo: "SIM-WIP-QI-006",
        gateCode: "needle_inspection",
        batchNo: "SIM-WIP-BATCH-006-A",
        result: "rejected",
        blockedStepCode: "sampling_inspection",
        finalPackagingAllowed: false,
        disposition: "rework",
        sourceIds: SYNTHETIC_SOURCE_IDS,
      }),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      scenarioNo: "SIM-PWIP-007",
      scenarioType: "customer_inspection_passed",
      productionOrderNo: "SIM-MO-PWIP-007",
      productNo: "SIM-PROD-001",
      parentBatchNo: "SIM-WIP-BATCH-007",
      quantity: "120",
      customerInspection: Object.freeze({
        conditionRecordNo: "SIM-CI-CONDITION-007",
        inspectionNo: "SIM-CI-007",
        ruleSourceNo: "SIM-SO-001",
        required: true,
        status: "passed",
        finalPackagingAllowed: true,
        sourceIds: SYNTHETIC_SOURCE_IDS,
      }),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      scenarioNo: "SIM-PWIP-008",
      scenarioType: "customer_inspection_blocked",
      productionOrderNo: "SIM-MO-PWIP-008",
      productNo: "SIM-PROD-002",
      parentBatchNo: "SIM-WIP-BATCH-008",
      quantity: "240",
      customerInspection: Object.freeze({
        conditionRecordNo: "SIM-CI-CONDITION-008",
        inspectionNo: "SIM-CI-008",
        ruleSourceNo: "SIM-SO-002",
        required: true,
        status: "rejected",
        blockedStepCode: "final_packaging",
        finalPackagingAllowed: false,
        sourceIds: SYNTHETIC_SOURCE_IDS,
      }),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      scenarioNo: "SIM-PWIP-009",
      scenarioType: "packaging_business_quality_separated",
      productionOrderNo: "SIM-MO-PWIP-009",
      productNo: "SIM-PROD-001",
      parentBatchNo: "SIM-WIP-BATCH-009",
      quantity: "120",
      businessConfirmation: Object.freeze({
        confirmationNo: "SIM-PACK-BIZ-009",
        roleKey: "sales",
        packagingVersionNo: "SIM-PACK-V1",
        result: "confirmed",
        sourceIds: SYNTHETIC_SOURCE_IDS,
      }),
      qualityInspection: Object.freeze({
        inspectionNo: "SIM-PACK-QI-009",
        roleKey: "quality",
        packagingMaterialLotNo: "SIM-PACK-LOT-009",
        result: "rejected",
        sourceIds: SYNTHETIC_SOURCE_IDS,
      }),
      finalPackagingAllowed: false,
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      scenarioNo: "SIM-PWIP-010",
      scenarioType: "route_snapshot_immutable",
      productionOrderNo: "SIM-MO-PWIP-010",
      productNo: "SIM-PROD-001",
      parentBatchNo: "SIM-WIP-BATCH-010",
      quantity: "120",
      routeSnapshot: Object.freeze({
        snapshotNo: "SIM-ROUTE-SNAPSHOT-010",
        routeCode: "SIM-ROUTE-PLUSH-001",
        versionNo: "SIM-ROUTE-V1",
        orderedStepCodes: Object.freeze([
          "fabric_processing",
          "cut_piece_inspection",
          "sewing",
          "shell_inspection",
          "handwork",
          "finished_goods_inspection",
          "needle_inspection",
          "sampling_inspection",
          "customer_inspection",
          "final_packaging",
          "finished_goods_inbound",
        ]),
        sourceIds: SYNTHETIC_SOURCE_IDS,
      }),
      routeTemplateAfterRelease: Object.freeze({
        routeCode: "SIM-ROUTE-PLUSH-001",
        currentVersionNo: "SIM-ROUTE-V2",
        sourceIds: SYNTHETIC_SOURCE_IDS,
      }),
      executionRouteVersionNo: "SIM-ROUTE-V1",
      snapshotChanged: false,
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  workflowTasks: Object.freeze([
    Object.freeze({
      taskCode: "SIM-WF-SALES-001",
      taskGroup: "sales_order_approval",
      sourceNo: "SIM-SO-001",
      ownerRoleKey: "sales",
      taskStatusKey: "ready",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      taskCode: "SIM-WF-PURCHASE-001",
      taskGroup: "purchase_order_approval",
      sourceNo: "SIM-PO-001",
      ownerRoleKey: "purchase",
      taskStatusKey: "ready",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      taskCode: "SIM-WF-BOSS-001",
      taskGroup: "order_approval",
      sourceNo: "SIM-SO-002",
      ownerRoleKey: "boss",
      taskStatusKey: "ready",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      taskCode: "SIM-WF-QC-001",
      taskGroup: "finished_goods_qc",
      sourceNo: "SIM-PR-002",
      ownerRoleKey: "quality",
      taskStatusKey: "blocked",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      taskCode: "SIM-WF-WH-001",
      taskGroup: "trial_warehouse_work",
      sourceNo: "SIM-SH-002",
      ownerRoleKey: "warehouse",
      taskStatusKey: "done",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
});
