const SYNTHETIC_SOURCE_IDS = Object.freeze(["__synthetic_yoyoosun_trial__"]);

export const yoyoosunTrialDataFixture = Object.freeze({
  customerKey: "yoyoosun",
  fixtureKey: "__synthetic_yoyoosun_trial__",
  status: "preview_only",
  boundary:
    "Every value in this deterministic fixture is synthetic dry-run seed data for UI, print and flow tests. It has no row-level link to private customer sources and must not be applied to customer production data.",
  units: Object.freeze([
    Object.freeze({ unitCode: "PCS", unitName: "个", sourceIds: SYNTHETIC_SOURCE_IDS }),
    Object.freeze({ unitCode: "M", unitName: "米", sourceIds: SYNTHETIC_SOURCE_IDS }),
    Object.freeze({ unitCode: "KG", unitName: "千克", sourceIds: SYNTHETIC_SOURCE_IDS }),
    Object.freeze({ unitCode: "BOX", unitName: "箱", sourceIds: SYNTHETIC_SOURCE_IDS }),
  ]),
  customers: Object.freeze([
    Object.freeze({
      customerCode: "SIM-CUSTOMER-001",
      displayName: "合成试用客户甲",
      contactName: "合成客户联系人甲",
      contactPhone: "13800000000",
      paymentCondition: "monthly_statement_30_days",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      customerCode: "SIM-CUSTOMER-002",
      displayName: "合成试用客户乙",
      contactName: "合成客户联系人乙",
      contactPhone: "13800000001",
      paymentCondition: "deposit_30_balance_before_shipment",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  suppliers: Object.freeze([
    Object.freeze({
      supplierCode: "SIM-SUP-MATERIAL-001",
      displayName: "合成材料供应商甲",
      supplierType: "material",
      contactName: "合成供应商联系人甲",
      contactPhone: "13900000001",
      address: "合成地址-材料区A",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      supplierCode: "SIM-SUP-PROCESS-001",
      displayName: "合成委外加工商",
      supplierType: "outsourcing",
      contactName: "合成委外联系人",
      contactPhone: "13900000002",
      address: "合成地址-加工区B",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      supplierCode: "SIM-SUP-MATERIAL-002",
      displayName: "合成材料供应商乙",
      supplierType: "material",
      contactName: "合成供应商联系人乙",
      contactPhone: "13900000003",
      address: "合成地址-材料区C",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  materials: Object.freeze([
    Object.freeze({
      materialCode: "SIM-MAT-FABRIC-001",
      materialName: "合成玩偶甲主面料",
      category: "面料",
      vendorCode: "SIM-VENDOR-FABRIC-001",
      spec: "SIM-FABRIC-A",
      color: "粉色",
      unitCode: "M",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      materialCode: "SIM-MAT-FILLING-001",
      materialName: "合成玩偶乙填充棉",
      category: "填充",
      vendorCode: "SIM-VENDOR-FILLING-001",
      spec: "SIM-FILLING-A",
      color: "本白",
      unitCode: "KG",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      materialCode: "SIM-MAT-EYE-001",
      materialName: "合成玩偶甲安全眼",
      category: "胶件",
      vendorCode: "SIM-VENDOR-EYE-001",
      spec: "12mm",
      color: "黑色",
      unitCode: "PCS",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      materialCode: "SIM-MAT-CARTON-001",
      materialName: "合成玩偶乙外箱",
      category: "包材",
      vendorCode: "SIM-VENDOR-CARTON-001",
      spec: "12只装",
      color: "牛皮纸",
      unitCode: "BOX",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      materialCode: "SIM-MAT-LABEL-001",
      materialName: "通用洗水标",
      category: "辅料",
      vendorCode: "SIM-VENDOR-LABEL-001",
      spec: "双语",
      color: "白底黑字",
      unitCode: "PCS",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  products: Object.freeze([
    Object.freeze({
      productNo: "SIM-PROD-001",
      productName: "合成玩偶甲",
      skuNo: "SIM-SKU-001",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      productNo: "SIM-PROD-002",
      productName: "合成玩偶乙",
      skuNo: "SIM-SKU-002",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      productNo: "SIM-PROD-003",
      productName: "合成玩偶甲大号",
      skuNo: "SIM-SKU-003",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  warehouses: Object.freeze([
    Object.freeze({
      warehouseCode: "SIM-WH-RAW",
      warehouseName: "合成试用主料仓",
      warehouseType: "RAW_MATERIAL",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      warehouseCode: "SIM-WH-FINISHED",
      warehouseName: "合成试用成品仓",
      warehouseType: "FINISHED_GOODS",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      warehouseCode: "SIM-WH-OTHER",
      warehouseName: "合成试用其他仓",
      warehouseType: "OTHER",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      warehouseCode: "SIM-WH-QC-HOLD",
      warehouseName: "合成试用待检仓",
      warehouseType: "QC_HOLD",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  bomVersions: Object.freeze([
    Object.freeze({
      bomNo: "SIM-BOM-001",
      productNo: "SIM-PROD-001",
      skuNo: "SIM-SKU-001",
      versionNo: "SIM-V1",
      sourceOrderNo: "SIM-SOURCE-ORDER-001",
      quantityText: "100",
      spareText: "含损耗备品",
      printDate: "2026-01-01",
      designer: "合成设计员",
      maker: "合成制单员",
      auditor: "工程审核",
      hairDirection: "单方向",
      lines: Object.freeze([
        Object.freeze({
          materialCode: "SIM-MAT-FABRIC-001",
          usageQty: "0.80",
          unitCode: "M",
          position: "脸*1",
          pieceCount: "1",
          lossRate: "10",
          totalUsage: "88.00",
          processBase: "布底贴12g纸朴",
          processMethod: "热裁",
          note: "按色卡方向裁片",
        }),
        Object.freeze({
          materialCode: "SIM-MAT-EYE-001",
          usageQty: "2",
          unitCode: "PCS",
          position: "眼*2",
          pieceCount: "2",
          lossRate: "0",
          totalUsage: "200",
          processBase: "无特殊底料",
          processMethod: "眼 / 介子 / 贴纸配套",
        }),
        Object.freeze({
          materialCode: "SIM-MAT-LABEL-001",
          usageQty: "1",
          unitCode: "PCS",
          position: "洗水标*1",
          pieceCount: "1",
          lossRate: "5",
          totalUsage: "105.00",
          processBase: "常规车缝",
          processMethod: "车缝",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      bomNo: "SIM-BOM-002",
      productNo: "SIM-PROD-002",
      skuNo: "SIM-SKU-002",
      versionNo: "SIM-V2",
      sourceOrderNo: "SIM-SOURCE-ORDER-002",
      quantityText: "200",
      spareText: "备品 10",
      printDate: "2026-01-02",
      designer: "合成设计员乙",
      maker: "合成制单员",
      auditor: "工程审核",
      hairDirection: "单方向",
      lines: Object.freeze([
        Object.freeze({
          materialCode: "SIM-MAT-FILLING-001",
          usageQty: "0.35",
          unitCode: "KG",
          position: "填充",
          pieceCount: "1",
          lossRate: "10",
          totalUsage: "77.00",
          processBase: "无特殊底料",
          processMethod: "充棉",
        }),
        Object.freeze({
          materialCode: "SIM-MAT-CARTON-001",
          usageQty: "0.083333",
          unitCode: "BOX",
          position: "包装",
          pieceCount: "1",
          lossRate: "0",
          totalUsage: "16.67",
          processBase: "常规包装",
          processMethod: "包装",
        }),
        Object.freeze({
          materialCode: "SIM-MAT-LABEL-001",
          usageQty: "1",
          unitCode: "PCS",
          position: "洗水标*1",
          pieceCount: "1",
          lossRate: "5",
          totalUsage: "210.00",
          processBase: "常规车缝",
          processMethod: "车缝",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  salesOrders: Object.freeze([
    Object.freeze({
      orderNo: "SIM-SO-001",
      customerCode: "SIM-CUSTOMER-001",
      productNo: "SIM-PROD-001",
      skuNo: "SIM-SKU-001",
      quantity: "120",
      lifecycleStatus: "draft",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      orderNo: "SIM-SO-002",
      customerCode: "SIM-CUSTOMER-002",
      productNo: "SIM-PROD-002",
      skuNo: "SIM-SKU-002",
      quantity: "240",
      lifecycleStatus: "active",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      orderNo: "SIM-SO-003",
      customerCode: "SIM-CUSTOMER-001",
      productNo: "SIM-PROD-003",
      skuNo: "SIM-SKU-003",
      quantity: "36",
      lifecycleStatus: "cancelled",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  purchaseOrders: Object.freeze([
    Object.freeze({
      purchaseOrderNo: "SIM-PO-001",
      supplierCode: "SIM-SUP-MATERIAL-001",
      orderDate: "2026-06-13",
      expectedArrivalDate: "2026-06-24",
      printTemplateKey: "material-purchase-contract",
      contractPartySnapshot: Object.freeze({
        buyerCompany: "合成试用工厂",
        buyerContact: "合成采购负责人",
        buyerPhone: "0769-00000001",
        buyerAddress: "合成地址-采购部",
        buyerSigner: "合成采购负责人",
      }),
      lines: Object.freeze([
        Object.freeze({
          subjectType: "PRODUCT",
          productOrderNo: "SIM-SO-001",
          productNo: "SIM-PROD-001",
          productName: "合成玩偶甲",
          materialCode: "SIM-MAT-FABRIC-001",
          materialName: "合成玩偶甲主面料",
          unitCode: "M",
          quantity: "96",
          unitPrice: "8.500",
          amount: "816.00",
          note: "按批次分包并标明产品编号。",
        }),
        Object.freeze({
          subjectType: "PRODUCT",
          productOrderNo: "SIM-SO-002",
          productNo: "SIM-PROD-002",
          productName: "合成玩偶乙",
          materialCode: "SIM-MAT-CARTON-001",
          materialName: "合成玩偶乙外箱",
          unitCode: "BOX",
          quantity: "20",
          unitPrice: "4.200",
          amount: "84.00",
          note: "外箱按产品订单单独打包。",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      purchaseOrderNo: "SIM-PO-002",
      supplierCode: "SIM-SUP-MATERIAL-002",
      orderDate: "2026-06-13",
      expectedArrivalDate: "2026-06-24",
      printTemplateKey: "material-purchase-contract",
      contractPartySnapshot: Object.freeze({
        buyerCompany: "合成试用工厂",
        buyerContact: "合成采购负责人",
        buyerPhone: "0769-00000001",
        buyerAddress: "合成地址-采购部",
        buyerSigner: "合成采购负责人",
      }),
      lines: Object.freeze([
        Object.freeze({
          subjectType: "PRODUCT",
          productOrderNo: "SIM-SO-002",
          productNo: "SIM-PROD-002",
          productName: "合成玩偶乙",
          materialCode: "SIM-MAT-LABEL-001",
          materialName: "通用洗水标",
          unitCode: "PCS",
          quantity: "260",
          unitPrice: "0.120",
          amount: "31.20",
          note: "洗水标随主料分包交付。",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  outsourcingOrders: Object.freeze([
    Object.freeze({
      outsourcingOrderNo: "SIM-OS-001",
      processorCode: "SIM-SUP-PROCESS-001",
      orderDate: "2026-06-19",
      returnDate: "2026-06-26",
      printTemplateKey: "processing-contract",
      contractPartySnapshot: Object.freeze({
        buyerCompany: "合成试用工厂",
        buyerContact: "合成委外负责人",
        buyerPhone: "0769-00000002",
        buyerAddress: "合成地址-委外部",
        buyerSigner: "合成委外负责人",
      }),
      lines: Object.freeze([
        Object.freeze({
          productOrderNo: "SIM-SO-001",
          productNo: "SIM-PROD-001",
          productName: "合成玩偶甲",
          processName: "车缝加工",
          processCategory: "缝制",
          unitCode: "PCS",
          quantity: "120",
          unitPrice: "3.200",
          amount: "384.00",
          note: "按车缝工序分包回货。",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      outsourcingOrderNo: "SIM-OS-002",
      processorCode: "SIM-SUP-PROCESS-001",
      orderDate: "2026-06-19",
      returnDate: "2026-06-26",
      printTemplateKey: "processing-contract",
      contractPartySnapshot: Object.freeze({
        buyerCompany: "合成试用工厂",
        buyerContact: "合成委外负责人",
        buyerPhone: "0769-00000002",
        buyerAddress: "合成地址-委外部",
        buyerSigner: "合成委外负责人",
      }),
      lines: Object.freeze([
        Object.freeze({
          productOrderNo: "SIM-SO-002",
          productNo: "SIM-PROD-002",
          productName: "合成玩偶乙",
          processName: "裁片IQC",
          processCategory: "裁片质检",
          unitCode: "PCS",
          quantity: "240",
          unitPrice: "0.850",
          amount: "204.00",
          note: "裁片检验后按产品编号回传。",
        }),
        Object.freeze({
          productOrderNo: "SIM-SO-002",
          productNo: "SIM-PROD-002",
          productName: "合成玩偶乙",
          processName: "贴合",
          processCategory: "贴合",
          unitCode: "PCS",
          quantity: "240",
          unitPrice: "1.100",
          amount: "264.00",
          note: "贴合后单独标注工序名称。",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      outsourcingOrderNo: "SIM-OS-003",
      sourceOrderNo: "SIM-PO-001",
      processorCode: "SIM-SUP-PROCESS-001",
      orderDate: "2026-06-20",
      returnDate: "2026-06-27",
      printTemplateKey: "processing-contract",
      contractPartySnapshot: Object.freeze({
        buyerCompany: "合成试用工厂",
        buyerContact: "合成委外负责人",
        buyerPhone: "0769-00000002",
        buyerAddress: "合成地址-委外部",
        buyerSigner: "合成委外负责人",
      }),
      lines: Object.freeze([
        Object.freeze({
          subjectType: "MATERIAL",
          materialCode: "SIM-MAT-FABRIC-001",
          materialName: "合成玩偶甲主面料",
          processName: "布料复合加工",
          processCategory: "布料加工",
          unitCode: "M",
          quantity: "180",
          unitPrice: "1.600",
          amount: "288.00",
          note: "按面料批次加工，回货后进入来料质检。",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      outsourcingOrderNo: "SIM-OS-004",
      sourceOrderNo: "SIM-SO-002",
      processorCode: "SIM-SUP-PROCESS-001",
      orderDate: "2026-06-20",
      returnDate: "2026-06-28",
      printTemplateKey: "processing-contract",
      contractPartySnapshot: Object.freeze({
        buyerCompany: "合成试用工厂",
        buyerContact: "合成委外负责人",
        buyerPhone: "0769-00000002",
        buyerAddress: "合成地址-委外部",
        buyerSigner: "合成委外负责人",
      }),
      lines: Object.freeze([
        Object.freeze({
          subjectType: "PRODUCT",
          productOrderNo: "SIM-SO-002",
          productNo: "SIM-PROD-002",
          productName: "合成玩偶乙",
          processName: "手工缝制加工",
          processCategory: "手工加工",
          unitCode: "PCS",
          quantity: "240",
          unitPrice: "1.250",
          amount: "300.00",
          note: "手工收口与装饰件固定，按产品订单分批回货。",
        }),
      ]),
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  purchaseReceipts: Object.freeze([
    Object.freeze({
      receiptNo: "SIM-PR-001",
      purchaseOrderNo: "SIM-PO-001",
      warehouseCode: "SIM-WH-RAW",
      status: "draft",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      receiptNo: "SIM-PR-002",
      purchaseOrderNo: "SIM-PO-002",
      warehouseCode: "SIM-WH-QC-HOLD",
      status: "posted",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  qualityInspections: Object.freeze([
    Object.freeze({
      inspectionNo: "SIM-QI-001",
      sourceNo: "SIM-PR-001",
      result: "pending",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      inspectionNo: "SIM-QI-002",
      sourceNo: "SIM-PR-002",
      result: "passed",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      inspectionNo: "SIM-QI-003",
      sourceNo: "SIM-OS-002",
      result: "rejected",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  inventoryLots: Object.freeze([
    Object.freeze({
      lotNo: "SIM-LOT-001",
      materialCode: "SIM-MAT-FABRIC-001",
      warehouseCode: "SIM-WH-RAW",
      quantity: "0",
      status: "pending_inbound",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      lotNo: "SIM-LOT-002",
      materialCode: "SIM-MAT-LABEL-001",
      warehouseCode: "SIM-WH-QC-HOLD",
      quantity: "260",
      status: "qc_hold",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      lotNo: "SIM-LOT-003",
      materialCode: "SIM-MAT-CARTON-001",
      warehouseCode: "SIM-WH-OTHER",
      quantity: "20",
      status: "available",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  shipments: Object.freeze([
    Object.freeze({
      shipmentNo: "SIM-SH-001",
      salesOrderNo: "SIM-SO-001",
      warehouseCode: "SIM-WH-FINISHED",
      status: "draft",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      shipmentNo: "SIM-SH-002",
      salesOrderNo: "SIM-SO-002",
      warehouseCode: "SIM-WH-FINISHED",
      status: "shipped",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      shipmentNo: "SIM-SH-003",
      salesOrderNo: "SIM-SO-003",
      warehouseCode: "SIM-WH-FINISHED",
      status: "cancelled",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  financeDrafts: Object.freeze([
    Object.freeze({
      financeDraftNo: "SIM-AR-001",
      sourceNo: "SIM-SH-001",
      factType: "receivable_draft",
      status: "draft",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      financeDraftNo: "SIM-AR-002",
      sourceNo: "SIM-SH-002",
      factType: "receivable_posted",
      status: "posted",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      financeDraftNo: "SIM-AP-001",
      sourceNo: "SIM-OS-002",
      factType: "payable_draft",
      status: "draft",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
  workflowTasks: Object.freeze([
    Object.freeze({
      taskCode: "SIM-WF-SALES-001",
      taskGroup: "sales_order_approval",
      sourceNo: "SIM-SO-001",
      ownerRoleKey: "sales",
      taskStatusKey: "ready",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      taskCode: "SIM-WF-PURCHASE-001",
      taskGroup: "purchase_order_approval",
      sourceNo: "SIM-PO-001",
      ownerRoleKey: "purchase",
      taskStatusKey: "ready",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      taskCode: "SIM-WF-BOSS-001",
      taskGroup: "order_approval",
      sourceNo: "SIM-SO-002",
      ownerRoleKey: "boss",
      taskStatusKey: "ready",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      taskCode: "SIM-WF-QC-001",
      taskGroup: "finished_goods_qc",
      sourceNo: "SIM-PR-002",
      ownerRoleKey: "quality",
      taskStatusKey: "blocked",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
    Object.freeze({
      taskCode: "SIM-WF-WH-001",
      taskGroup: "shipment_release",
      sourceNo: "SIM-SH-002",
      ownerRoleKey: "warehouse",
      taskStatusKey: "done",
      sourceIds: SYNTHETIC_SOURCE_IDS,
    }),
  ]),
});
