// Code generated by ent, DO NOT EDIT.

package productionwipoutsourcingallocation

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the productionwipoutsourcingallocation type in the database.
	Label = "production_wip_outsourcing_allocation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProductionWipBatchID holds the string denoting the production_wip_batch_id field in the database.
	FieldProductionWipBatchID = "production_wip_batch_id"
	// FieldOutsourcingOrderItemID holds the string denoting the outsourcing_order_item_id field in the database.
	FieldOutsourcingOrderItemID = "outsourcing_order_item_id"
	// FieldProductionOrderMaterialRequirementID holds the string denoting the production_order_material_requirement_id field in the database.
	FieldProductionOrderMaterialRequirementID = "production_order_material_requirement_id"
	// FieldSubjectType holds the string denoting the subject_type field in the database.
	FieldSubjectType = "subject_type"
	// FieldAllocatedQuantity holds the string denoting the allocated_quantity field in the database.
	FieldAllocatedQuantity = "allocated_quantity"
	// FieldUnitID holds the string denoting the unit_id field in the database.
	FieldUnitID = "unit_id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeProductionWipBatch holds the string denoting the production_wip_batch edge name in mutations.
	EdgeProductionWipBatch = "production_wip_batch"
	// EdgeOutsourcingOrderItem holds the string denoting the outsourcing_order_item edge name in mutations.
	EdgeOutsourcingOrderItem = "outsourcing_order_item"
	// EdgeProductionOrderMaterialRequirement holds the string denoting the production_order_material_requirement edge name in mutations.
	EdgeProductionOrderMaterialRequirement = "production_order_material_requirement"
	// EdgeUnit holds the string denoting the unit edge name in mutations.
	EdgeUnit = "unit"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// Table holds the table name of the productionwipoutsourcingallocation in the database.
	Table = "production_wip_outsourcing_allocations"
	// ProductionWipBatchTable is the table that holds the production_wip_batch relation/edge.
	ProductionWipBatchTable = "production_wip_outsourcing_allocations"
	// ProductionWipBatchInverseTable is the table name for the ProductionWIPBatch entity.
	// It exists in this package in order to avoid circular dependency with the "productionwipbatch" package.
	ProductionWipBatchInverseTable = "production_wip_batches"
	// ProductionWipBatchColumn is the table column denoting the production_wip_batch relation/edge.
	ProductionWipBatchColumn = "production_wip_batch_id"
	// OutsourcingOrderItemTable is the table that holds the outsourcing_order_item relation/edge.
	OutsourcingOrderItemTable = "production_wip_outsourcing_allocations"
	// OutsourcingOrderItemInverseTable is the table name for the OutsourcingOrderItem entity.
	// It exists in this package in order to avoid circular dependency with the "outsourcingorderitem" package.
	OutsourcingOrderItemInverseTable = "outsourcing_order_items"
	// OutsourcingOrderItemColumn is the table column denoting the outsourcing_order_item relation/edge.
	OutsourcingOrderItemColumn = "outsourcing_order_item_id"
	// ProductionOrderMaterialRequirementTable is the table that holds the production_order_material_requirement relation/edge.
	ProductionOrderMaterialRequirementTable = "production_wip_outsourcing_allocations"
	// ProductionOrderMaterialRequirementInverseTable is the table name for the ProductionOrderMaterialRequirement entity.
	// It exists in this package in order to avoid circular dependency with the "productionordermaterialrequirement" package.
	ProductionOrderMaterialRequirementInverseTable = "production_order_material_requirements"
	// ProductionOrderMaterialRequirementColumn is the table column denoting the production_order_material_requirement relation/edge.
	ProductionOrderMaterialRequirementColumn = "production_order_material_requirement_id"
	// UnitTable is the table that holds the unit relation/edge.
	UnitTable = "production_wip_outsourcing_allocations"
	// UnitInverseTable is the table name for the Unit entity.
	// It exists in this package in order to avoid circular dependency with the "unit" package.
	UnitInverseTable = "units"
	// UnitColumn is the table column denoting the unit relation/edge.
	UnitColumn = "unit_id"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "production_wip_outsourcing_allocations"
	// CreatorInverseTable is the table name for the AdminUser entity.
	// It exists in this package in order to avoid circular dependency with the "adminuser" package.
	CreatorInverseTable = "admin_users"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "created_by"
)

// Columns holds all SQL columns for productionwipoutsourcingallocation fields.
var Columns = []string{
	FieldID,
	FieldProductionWipBatchID,
	FieldOutsourcingOrderItemID,
	FieldProductionOrderMaterialRequirementID,
	FieldSubjectType,
	FieldAllocatedQuantity,
	FieldUnitID,
	FieldCreatedBy,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "server/internal/data/model/ent/runtime"
var (
	Hooks [1]ent.Hook
	// ProductionWipBatchIDValidator is a validator for the "production_wip_batch_id" field. It is called by the builders before save.
	ProductionWipBatchIDValidator func(int) error
	// OutsourcingOrderItemIDValidator is a validator for the "outsourcing_order_item_id" field. It is called by the builders before save.
	OutsourcingOrderItemIDValidator func(int) error
	// ProductionOrderMaterialRequirementIDValidator is a validator for the "production_order_material_requirement_id" field. It is called by the builders before save.
	ProductionOrderMaterialRequirementIDValidator func(int) error
	// SubjectTypeValidator is a validator for the "subject_type" field. It is called by the builders before save.
	SubjectTypeValidator func(string) error
	// UnitIDValidator is a validator for the "unit_id" field. It is called by the builders before save.
	UnitIDValidator func(int) error
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ProductionWIPOutsourcingAllocation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProductionWipBatchID orders the results by the production_wip_batch_id field.
func ByProductionWipBatchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductionWipBatchID, opts...).ToFunc()
}

// ByOutsourcingOrderItemID orders the results by the outsourcing_order_item_id field.
func ByOutsourcingOrderItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutsourcingOrderItemID, opts...).ToFunc()
}

// ByProductionOrderMaterialRequirementID orders the results by the production_order_material_requirement_id field.
func ByProductionOrderMaterialRequirementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductionOrderMaterialRequirementID, opts...).ToFunc()
}

// BySubjectType orders the results by the subject_type field.
func BySubjectType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectType, opts...).ToFunc()
}

// ByAllocatedQuantity orders the results by the allocated_quantity field.
func ByAllocatedQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllocatedQuantity, opts...).ToFunc()
}

// ByUnitID orders the results by the unit_id field.
func ByUnitID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByProductionWipBatchField orders the results by production_wip_batch field.
func ByProductionWipBatchField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductionWipBatchStep(), sql.OrderByField(field, opts...))
	}
}

// ByOutsourcingOrderItemField orders the results by outsourcing_order_item field.
func ByOutsourcingOrderItemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOutsourcingOrderItemStep(), sql.OrderByField(field, opts...))
	}
}

// ByProductionOrderMaterialRequirementField orders the results by production_order_material_requirement field.
func ByProductionOrderMaterialRequirementField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductionOrderMaterialRequirementStep(), sql.OrderByField(field, opts...))
	}
}

// ByUnitField orders the results by unit field.
func ByUnitField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUnitStep(), sql.OrderByField(field, opts...))
	}
}

// ByCreatorField orders the results by creator field.
func ByCreatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorStep(), sql.OrderByField(field, opts...))
	}
}
func newProductionWipBatchStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductionWipBatchInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProductionWipBatchTable, ProductionWipBatchColumn),
	)
}
func newOutsourcingOrderItemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OutsourcingOrderItemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OutsourcingOrderItemTable, OutsourcingOrderItemColumn),
	)
}
func newProductionOrderMaterialRequirementStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductionOrderMaterialRequirementInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProductionOrderMaterialRequirementTable, ProductionOrderMaterialRequirementColumn),
	)
}
func newUnitStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UnitInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UnitTable, UnitColumn),
	)
}
func newCreatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, CreatorTable, CreatorColumn),
	)
}
