// Code generated by ent, DO NOT EDIT.

package productionorderevent

import (
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLTE(FieldID, id))
}

// ProductionOrderID applies equality check predicate on the "production_order_id" field. It's identical to ProductionOrderIDEQ.
func ProductionOrderID(v int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldProductionOrderID, v))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldActorID, v))
}

// CommandKey applies equality check predicate on the "command_key" field. It's identical to CommandKeyEQ.
func CommandKey(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldCommandKey, v))
}

// FromStatus applies equality check predicate on the "from_status" field. It's identical to FromStatusEQ.
func FromStatus(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldFromStatus, v))
}

// ToStatus applies equality check predicate on the "to_status" field. It's identical to ToStatusEQ.
func ToStatus(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldToStatus, v))
}

// OrderVersion applies equality check predicate on the "order_version" field. It's identical to OrderVersionEQ.
func OrderVersion(v int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldOrderVersion, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IntentHash applies equality check predicate on the "intent_hash" field. It's identical to IntentHashEQ.
func IntentHash(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldIntentHash, v))
}

// ResultContract applies equality check predicate on the "result_contract" field. It's identical to ResultContractEQ.
func ResultContract(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldResultContract, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// ProductionOrderIDEQ applies the EQ predicate on the "production_order_id" field.
func ProductionOrderIDEQ(v int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldProductionOrderID, v))
}

// ProductionOrderIDNEQ applies the NEQ predicate on the "production_order_id" field.
func ProductionOrderIDNEQ(v int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNEQ(FieldProductionOrderID, v))
}

// ProductionOrderIDIn applies the In predicate on the "production_order_id" field.
func ProductionOrderIDIn(vs ...int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldIn(FieldProductionOrderID, vs...))
}

// ProductionOrderIDNotIn applies the NotIn predicate on the "production_order_id" field.
func ProductionOrderIDNotIn(vs ...int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNotIn(FieldProductionOrderID, vs...))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNotIn(FieldActorID, vs...))
}

// CommandKeyEQ applies the EQ predicate on the "command_key" field.
func CommandKeyEQ(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldCommandKey, v))
}

// CommandKeyNEQ applies the NEQ predicate on the "command_key" field.
func CommandKeyNEQ(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNEQ(FieldCommandKey, v))
}

// CommandKeyIn applies the In predicate on the "command_key" field.
func CommandKeyIn(vs ...string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldIn(FieldCommandKey, vs...))
}

// CommandKeyNotIn applies the NotIn predicate on the "command_key" field.
func CommandKeyNotIn(vs ...string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNotIn(FieldCommandKey, vs...))
}

// CommandKeyGT applies the GT predicate on the "command_key" field.
func CommandKeyGT(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGT(FieldCommandKey, v))
}

// CommandKeyGTE applies the GTE predicate on the "command_key" field.
func CommandKeyGTE(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGTE(FieldCommandKey, v))
}

// CommandKeyLT applies the LT predicate on the "command_key" field.
func CommandKeyLT(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLT(FieldCommandKey, v))
}

// CommandKeyLTE applies the LTE predicate on the "command_key" field.
func CommandKeyLTE(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLTE(FieldCommandKey, v))
}

// CommandKeyContains applies the Contains predicate on the "command_key" field.
func CommandKeyContains(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldContains(FieldCommandKey, v))
}

// CommandKeyHasPrefix applies the HasPrefix predicate on the "command_key" field.
func CommandKeyHasPrefix(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldHasPrefix(FieldCommandKey, v))
}

// CommandKeyHasSuffix applies the HasSuffix predicate on the "command_key" field.
func CommandKeyHasSuffix(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldHasSuffix(FieldCommandKey, v))
}

// CommandKeyEqualFold applies the EqualFold predicate on the "command_key" field.
func CommandKeyEqualFold(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEqualFold(FieldCommandKey, v))
}

// CommandKeyContainsFold applies the ContainsFold predicate on the "command_key" field.
func CommandKeyContainsFold(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldContainsFold(FieldCommandKey, v))
}

// FromStatusEQ applies the EQ predicate on the "from_status" field.
func FromStatusEQ(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldFromStatus, v))
}

// FromStatusNEQ applies the NEQ predicate on the "from_status" field.
func FromStatusNEQ(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNEQ(FieldFromStatus, v))
}

// FromStatusIn applies the In predicate on the "from_status" field.
func FromStatusIn(vs ...string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldIn(FieldFromStatus, vs...))
}

// FromStatusNotIn applies the NotIn predicate on the "from_status" field.
func FromStatusNotIn(vs ...string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNotIn(FieldFromStatus, vs...))
}

// FromStatusGT applies the GT predicate on the "from_status" field.
func FromStatusGT(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGT(FieldFromStatus, v))
}

// FromStatusGTE applies the GTE predicate on the "from_status" field.
func FromStatusGTE(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGTE(FieldFromStatus, v))
}

// FromStatusLT applies the LT predicate on the "from_status" field.
func FromStatusLT(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLT(FieldFromStatus, v))
}

// FromStatusLTE applies the LTE predicate on the "from_status" field.
func FromStatusLTE(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLTE(FieldFromStatus, v))
}

// FromStatusContains applies the Contains predicate on the "from_status" field.
func FromStatusContains(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldContains(FieldFromStatus, v))
}

// FromStatusHasPrefix applies the HasPrefix predicate on the "from_status" field.
func FromStatusHasPrefix(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldHasPrefix(FieldFromStatus, v))
}

// FromStatusHasSuffix applies the HasSuffix predicate on the "from_status" field.
func FromStatusHasSuffix(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldHasSuffix(FieldFromStatus, v))
}

// FromStatusIsNil applies the IsNil predicate on the "from_status" field.
func FromStatusIsNil() predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldIsNull(FieldFromStatus))
}

// FromStatusNotNil applies the NotNil predicate on the "from_status" field.
func FromStatusNotNil() predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNotNull(FieldFromStatus))
}

// FromStatusEqualFold applies the EqualFold predicate on the "from_status" field.
func FromStatusEqualFold(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEqualFold(FieldFromStatus, v))
}

// FromStatusContainsFold applies the ContainsFold predicate on the "from_status" field.
func FromStatusContainsFold(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldContainsFold(FieldFromStatus, v))
}

// ToStatusEQ applies the EQ predicate on the "to_status" field.
func ToStatusEQ(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldToStatus, v))
}

// ToStatusNEQ applies the NEQ predicate on the "to_status" field.
func ToStatusNEQ(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNEQ(FieldToStatus, v))
}

// ToStatusIn applies the In predicate on the "to_status" field.
func ToStatusIn(vs ...string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldIn(FieldToStatus, vs...))
}

// ToStatusNotIn applies the NotIn predicate on the "to_status" field.
func ToStatusNotIn(vs ...string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNotIn(FieldToStatus, vs...))
}

// ToStatusGT applies the GT predicate on the "to_status" field.
func ToStatusGT(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGT(FieldToStatus, v))
}

// ToStatusGTE applies the GTE predicate on the "to_status" field.
func ToStatusGTE(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGTE(FieldToStatus, v))
}

// ToStatusLT applies the LT predicate on the "to_status" field.
func ToStatusLT(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLT(FieldToStatus, v))
}

// ToStatusLTE applies the LTE predicate on the "to_status" field.
func ToStatusLTE(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLTE(FieldToStatus, v))
}

// ToStatusContains applies the Contains predicate on the "to_status" field.
func ToStatusContains(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldContains(FieldToStatus, v))
}

// ToStatusHasPrefix applies the HasPrefix predicate on the "to_status" field.
func ToStatusHasPrefix(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldHasPrefix(FieldToStatus, v))
}

// ToStatusHasSuffix applies the HasSuffix predicate on the "to_status" field.
func ToStatusHasSuffix(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldHasSuffix(FieldToStatus, v))
}

// ToStatusEqualFold applies the EqualFold predicate on the "to_status" field.
func ToStatusEqualFold(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEqualFold(FieldToStatus, v))
}

// ToStatusContainsFold applies the ContainsFold predicate on the "to_status" field.
func ToStatusContainsFold(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldContainsFold(FieldToStatus, v))
}

// OrderVersionEQ applies the EQ predicate on the "order_version" field.
func OrderVersionEQ(v int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldOrderVersion, v))
}

// OrderVersionNEQ applies the NEQ predicate on the "order_version" field.
func OrderVersionNEQ(v int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNEQ(FieldOrderVersion, v))
}

// OrderVersionIn applies the In predicate on the "order_version" field.
func OrderVersionIn(vs ...int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldIn(FieldOrderVersion, vs...))
}

// OrderVersionNotIn applies the NotIn predicate on the "order_version" field.
func OrderVersionNotIn(vs ...int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNotIn(FieldOrderVersion, vs...))
}

// OrderVersionGT applies the GT predicate on the "order_version" field.
func OrderVersionGT(v int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGT(FieldOrderVersion, v))
}

// OrderVersionGTE applies the GTE predicate on the "order_version" field.
func OrderVersionGTE(v int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGTE(FieldOrderVersion, v))
}

// OrderVersionLT applies the LT predicate on the "order_version" field.
func OrderVersionLT(v int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLT(FieldOrderVersion, v))
}

// OrderVersionLTE applies the LTE predicate on the "order_version" field.
func OrderVersionLTE(v int) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLTE(FieldOrderVersion, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// IntentHashEQ applies the EQ predicate on the "intent_hash" field.
func IntentHashEQ(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldIntentHash, v))
}

// IntentHashNEQ applies the NEQ predicate on the "intent_hash" field.
func IntentHashNEQ(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNEQ(FieldIntentHash, v))
}

// IntentHashIn applies the In predicate on the "intent_hash" field.
func IntentHashIn(vs ...string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldIn(FieldIntentHash, vs...))
}

// IntentHashNotIn applies the NotIn predicate on the "intent_hash" field.
func IntentHashNotIn(vs ...string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNotIn(FieldIntentHash, vs...))
}

// IntentHashGT applies the GT predicate on the "intent_hash" field.
func IntentHashGT(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGT(FieldIntentHash, v))
}

// IntentHashGTE applies the GTE predicate on the "intent_hash" field.
func IntentHashGTE(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGTE(FieldIntentHash, v))
}

// IntentHashLT applies the LT predicate on the "intent_hash" field.
func IntentHashLT(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLT(FieldIntentHash, v))
}

// IntentHashLTE applies the LTE predicate on the "intent_hash" field.
func IntentHashLTE(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLTE(FieldIntentHash, v))
}

// IntentHashContains applies the Contains predicate on the "intent_hash" field.
func IntentHashContains(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldContains(FieldIntentHash, v))
}

// IntentHashHasPrefix applies the HasPrefix predicate on the "intent_hash" field.
func IntentHashHasPrefix(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldHasPrefix(FieldIntentHash, v))
}

// IntentHashHasSuffix applies the HasSuffix predicate on the "intent_hash" field.
func IntentHashHasSuffix(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldHasSuffix(FieldIntentHash, v))
}

// IntentHashEqualFold applies the EqualFold predicate on the "intent_hash" field.
func IntentHashEqualFold(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEqualFold(FieldIntentHash, v))
}

// IntentHashContainsFold applies the ContainsFold predicate on the "intent_hash" field.
func IntentHashContainsFold(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldContainsFold(FieldIntentHash, v))
}

// ResultContractEQ applies the EQ predicate on the "result_contract" field.
func ResultContractEQ(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldResultContract, v))
}

// ResultContractNEQ applies the NEQ predicate on the "result_contract" field.
func ResultContractNEQ(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNEQ(FieldResultContract, v))
}

// ResultContractIn applies the In predicate on the "result_contract" field.
func ResultContractIn(vs ...string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldIn(FieldResultContract, vs...))
}

// ResultContractNotIn applies the NotIn predicate on the "result_contract" field.
func ResultContractNotIn(vs ...string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNotIn(FieldResultContract, vs...))
}

// ResultContractGT applies the GT predicate on the "result_contract" field.
func ResultContractGT(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGT(FieldResultContract, v))
}

// ResultContractGTE applies the GTE predicate on the "result_contract" field.
func ResultContractGTE(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGTE(FieldResultContract, v))
}

// ResultContractLT applies the LT predicate on the "result_contract" field.
func ResultContractLT(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLT(FieldResultContract, v))
}

// ResultContractLTE applies the LTE predicate on the "result_contract" field.
func ResultContractLTE(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLTE(FieldResultContract, v))
}

// ResultContractContains applies the Contains predicate on the "result_contract" field.
func ResultContractContains(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldContains(FieldResultContract, v))
}

// ResultContractHasPrefix applies the HasPrefix predicate on the "result_contract" field.
func ResultContractHasPrefix(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldHasPrefix(FieldResultContract, v))
}

// ResultContractHasSuffix applies the HasSuffix predicate on the "result_contract" field.
func ResultContractHasSuffix(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldHasSuffix(FieldResultContract, v))
}

// ResultContractEqualFold applies the EqualFold predicate on the "result_contract" field.
func ResultContractEqualFold(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEqualFold(FieldResultContract, v))
}

// ResultContractContainsFold applies the ContainsFold predicate on the "result_contract" field.
func ResultContractContainsFold(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldContainsFold(FieldResultContract, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldContainsFold(FieldReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// HasProductionOrder applies the HasEdge predicate on the "production_order" edge.
func HasProductionOrder() predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductionOrderTable, ProductionOrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductionOrderWith applies the HasEdge predicate on the "production_order" edge with a given conditions (other predicates).
func HasProductionOrderWith(preds ...predicate.ProductionOrder) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(func(s *sql.Selector) {
		step := newProductionOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActor applies the HasEdge predicate on the "actor" edge.
func HasActor() predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ActorTable, ActorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActorWith applies the HasEdge predicate on the "actor" edge with a given conditions (other predicates).
func HasActorWith(preds ...predicate.AdminUser) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(func(s *sql.Selector) {
		step := newActorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProductionOrderEvent) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProductionOrderEvent) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProductionOrderEvent) predicate.ProductionOrderEvent {
	return predicate.ProductionOrderEvent(sql.NotPredicates(p))
}
