// Code generated by ent, DO NOT EDIT.

package process

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the process type in the database.
	Label = "process"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldOutsourcingEnabled holds the string denoting the outsourcing_enabled field in the database.
	FieldOutsourcingEnabled = "outsourcing_enabled"
	// FieldInhouseEnabled holds the string denoting the inhouse_enabled field in the database.
	FieldInhouseEnabled = "inhouse_enabled"
	// FieldQualityRequired holds the string denoting the quality_required field in the database.
	FieldQualityRequired = "quality_required"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOutsourcingOrderItems holds the string denoting the outsourcing_order_items edge name in mutations.
	EdgeOutsourcingOrderItems = "outsourcing_order_items"
	// EdgeCapableSuppliers holds the string denoting the capable_suppliers edge name in mutations.
	EdgeCapableSuppliers = "capable_suppliers"
	// Table holds the table name of the process in the database.
	Table = "processes"
	// OutsourcingOrderItemsTable is the table that holds the outsourcing_order_items relation/edge.
	OutsourcingOrderItemsTable = "outsourcing_order_items"
	// OutsourcingOrderItemsInverseTable is the table name for the OutsourcingOrderItem entity.
	// It exists in this package in order to avoid circular dependency with the "outsourcingorderitem" package.
	OutsourcingOrderItemsInverseTable = "outsourcing_order_items"
	// OutsourcingOrderItemsColumn is the table column denoting the outsourcing_order_items relation/edge.
	OutsourcingOrderItemsColumn = "process_id"
	// CapableSuppliersTable is the table that holds the capable_suppliers relation/edge. The primary key declared below.
	CapableSuppliersTable = "supplier_process_capabilities"
	// CapableSuppliersInverseTable is the table name for the Supplier entity.
	// It exists in this package in order to avoid circular dependency with the "supplier" package.
	CapableSuppliersInverseTable = "suppliers"
)

// Columns holds all SQL columns for process fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldName,
	FieldCategory,
	FieldOutsourcingEnabled,
	FieldInhouseEnabled,
	FieldQualityRequired,
	FieldSortOrder,
	FieldNote,
	FieldIsActive,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// CapableSuppliersPrimaryKey and CapableSuppliersColumn2 are the table columns denoting the
	// primary key for the capable_suppliers relation (M2M).
	CapableSuppliersPrimaryKey = []string{"supplier_id", "process_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// DefaultOutsourcingEnabled holds the default value on creation for the "outsourcing_enabled" field.
	DefaultOutsourcingEnabled bool
	// DefaultInhouseEnabled holds the default value on creation for the "inhouse_enabled" field.
	DefaultInhouseEnabled bool
	// DefaultQualityRequired holds the default value on creation for the "quality_required" field.
	DefaultQualityRequired bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// SortOrderValidator is a validator for the "sort_order" field. It is called by the builders before save.
	SortOrderValidator func(int) error
	// NoteValidator is a validator for the "note" field. It is called by the builders before save.
	NoteValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Process queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByOutsourcingEnabled orders the results by the outsourcing_enabled field.
func ByOutsourcingEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutsourcingEnabled, opts...).ToFunc()
}

// ByInhouseEnabled orders the results by the inhouse_enabled field.
func ByInhouseEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInhouseEnabled, opts...).ToFunc()
}

// ByQualityRequired orders the results by the quality_required field.
func ByQualityRequired(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQualityRequired, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOutsourcingOrderItemsCount orders the results by outsourcing_order_items count.
func ByOutsourcingOrderItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOutsourcingOrderItemsStep(), opts...)
	}
}

// ByOutsourcingOrderItems orders the results by outsourcing_order_items terms.
func ByOutsourcingOrderItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOutsourcingOrderItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCapableSuppliersCount orders the results by capable_suppliers count.
func ByCapableSuppliersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCapableSuppliersStep(), opts...)
	}
}

// ByCapableSuppliers orders the results by capable_suppliers terms.
func ByCapableSuppliers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCapableSuppliersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOutsourcingOrderItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OutsourcingOrderItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OutsourcingOrderItemsTable, OutsourcingOrderItemsColumn),
	)
}
func newCapableSuppliersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CapableSuppliersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, CapableSuppliersTable, CapableSuppliersPrimaryKey...),
	)
}
