export const customerPackageCatalog = Object.freeze({
  catalogKey: "customer-package-catalog-v1",
  status: "draft_catalog",
  runtimeEnabled: false,
  boundaries: Object.freeze({
    changesSchema: false,
    changesMigration: false,
    changesBackendRbac: false,
    changesWorkflowFactRules: false,
    createsTenant: false,
    executesImport: false,
    writesFacts: false,
  }),
  modules: Object.freeze([
    { key: "customers", label: "客户档案", layer: "MasterData" },
    { key: "suppliers", label: "供应商档案", layer: "MasterData" },
    { key: "products", label: "产品档案", layer: "MasterData" },
    { key: "materials", label: "材料档案", layer: "MasterData" },
    { key: "processes", label: "加工环节", layer: "MasterData" },
    { key: "material_bom", label: "BOM 管理", layer: "MasterData" },
    { key: "sales_orders", label: "销售订单", layer: "SourceDocument" },
    { key: "purchase_orders", label: "采购订单", layer: "SourceDocument" },
    { key: "purchase_receipts", label: "采购入库", layer: "Fact" },
    { key: "quality_inspections", label: "来料质检", layer: "Fact" },
    { key: "outsourcing_orders", label: "委外订单", layer: "SourceDocument" },
    { key: "inventory", label: "库存台账", layer: "FactReadModel" },
    { key: "shipments", label: "出货单", layer: "Fact" },
    { key: "finance", label: "财务业务", layer: "FactCandidate" },
    { key: "workflow_tasks", label: "协同任务", layer: "Workflow" },
    { key: "production_orders", label: "生产订单", layer: "SourceDocument" },
    { key: "production", label: "生产协同", layer: "Workflow" },
  ]),
  capabilities: Object.freeze([
    { key: "brand_menu.display", label: "品牌与菜单展示", layer: "CustomerConfig" },
    { key: "field_display.review", label: "字段显示评审", layer: "CustomerConfig" },
    { key: "numbering.review", label: "编号规则评审", layer: "CustomerConfig" },
    { key: "import.dry_run", label: "导入 dry-run", layer: "DataReview" },
    { key: "package.preview", label: "客户包预览", layer: "CustomerConfig" },
    { key: "process.preview", label: "流程结构预览", layer: "CustomerConfig" },
  ]),
  pages: Object.freeze([
    { key: "global-dashboard", label: "全局看板", requiredCapabilityKeys: ["erp.dashboard.read", "workflow.task.read"] },
    { key: "task-board", label: "任务看板", requiredCapabilityKeys: ["workflow.task.read"] },
    { key: "customers", label: "客户档案", requiredCapabilityKeys: ["customer.read"] },
    { key: "suppliers", label: "供应商档案", requiredCapabilityKeys: ["supplier.read", "contact.read"] },
    { key: "products", label: "产品档案", requiredCapabilityKeys: ["product.read", "product_sku.read", "material.read"] },
    { key: "materials", label: "材料档案", requiredCapabilityKeys: ["material.read"] },
    { key: "material-bom", label: "BOM 管理", requiredCapabilityKeys: ["bom.read", "product.read", "material.read"] },
    { key: "processes", label: "加工环节", requiredCapabilityKeys: ["process.read"] },
    { key: "sales-orders", label: "销售订单", requiredCapabilityKeys: ["sales_order.read", "sales_order_item.read", "customer.read", "contact.read", "product_sku.read", "material.read"] },
    { key: "accessories-purchase", label: "采购订单", requiredCapabilityKeys: ["purchase.order.read", "supplier.read", "contact.read", "material.read", "warehouse.inventory.read", "workflow.task.read"] },
    { key: "quality-inspections", label: "来料质检", requiredCapabilityKeys: ["quality.inspection.read", "purchase.receipt.read", "warehouse.inventory.read", "material.read"] },
    { key: "inbound", label: "入库管理", requiredCapabilityKeys: ["purchase.receipt.read", "supplier.read", "material.read", "warehouse.inventory.read"] },
    { key: "inventory", label: "库存台账", requiredCapabilityKeys: ["warehouse.inventory.read", "material.read", "product.read"] },
    { key: "processing-contracts", label: "加工合同", requiredCapabilityKeys: ["outsourcing.order.read", "supplier.read", "contact.read", "material.read", "process.read", "product.read", "workflow.task.read"] },
    { key: "production-orders", label: "生产订单", requiredCapabilityKeys: ["pmc.plan.read"] },
    { key: "production-scheduling", label: "生产排程", requiredCapabilityKeys: ["pmc.plan.read"] },
    { key: "production-progress", label: "生产进度", requiredCapabilityKeys: ["pmc.plan.read"] },
    { key: "production-exceptions", label: "生产异常", requiredCapabilityKeys: ["pmc.risk.read"] },
    { key: "outbound", label: "出库管理", requiredCapabilityKeys: ["warehouse.outbound.read", "warehouse.inventory.read"] },
    { key: "shipments", label: "出货单", requiredCapabilityKeys: ["shipment.read", "customer.read", "warehouse.inventory.read", "product.read", "product_sku.read", "sales_order.read", "sales_order_item.read", "material.read"] },
    { key: "reconciliation", label: "业务对账", requiredCapabilityKeys: ["finance.report.read", "finance.payable.read", "finance.receivable.read"] },
    { key: "payables", label: "应付台账", requiredCapabilityKeys: ["finance.payable.read"] },
    { key: "receivables", label: "应收台账", requiredCapabilityKeys: ["finance.receivable.read"] },
    { key: "invoices", label: "发票台账", requiredCapabilityKeys: ["finance.receivable.read", "finance.payable.read"] },
    { key: "print-center", label: "打印中心", requiredCapabilityKeys: ["erp.print_template.read"] },
    { key: "permission-center", label: "权限中心", requiredCapabilityKeys: ["system.user.read", "system.role.read"] },
    { key: "system-audit-logs", label: "审计日志", requiredCapabilityKeys: ["system.audit.read"] },
  ]),
  fields: Object.freeze([
    { key: "customer_code", module: "customers", label: "客户编码" },
    { key: "display_name", module: "customers", label: "客户简称" },
    { key: "supplier_code", module: "suppliers", label: "供应商编码" },
    { key: "supplier_type", module: "suppliers", label: "供应商分类" },
    { key: "order_no", module: "sales_orders", label: "销售订单编号" },
    { key: "source_no", module: "sales_orders", label: "客户订单号" },
    { key: "expected_ship_date", module: "sales_orders", label: "交期" },
    { key: "product_id", module: "sales_order_items", label: "产品" },
    { key: "style_no", module: "sales_order_items", label: "款式编号" },
    { key: "color_size", module: "sales_order_items", label: "颜色 / 尺寸" },
  ]),
  fieldPolicySurfaces: Object.freeze([
    Object.freeze({
      key: "customers.default",
      moduleKey: "customers",
      fieldKeys: Object.freeze(["customer_code", "display_name"]),
      protectedVisible: Object.freeze(["customer_code", "display_name"]),
    }),
    Object.freeze({
      key: "suppliers.default",
      moduleKey: "suppliers",
      fieldKeys: Object.freeze(["supplier_code", "supplier_type"]),
      protectedVisible: Object.freeze(["supplier_code"]),
    }),
    Object.freeze({
      key: "sales_orders.default",
      moduleKey: "sales_orders",
      fieldKeys: Object.freeze([
        "order_no",
        "source_no",
        "expected_ship_date",
      ]),
      protectedVisible: Object.freeze(["order_no"]),
    }),
  ]),
  workPools: Object.freeze([
    { key: "boss", label: "老板 / 管理层" },
    { key: "sales", label: "业务" },
    { key: "purchase", label: "采购" },
    { key: "warehouse", label: "仓库" },
    { key: "quality", label: "品质" },
    { key: "finance", label: "财务" },
    { key: "pmc", label: "PMC" },
    { key: "engineering", label: "工程" },
    { key: "production", label: "生产经理" },
  ]),
  policies: Object.freeze([
    { key: "skip_policy", label: "跳过策略", runtimeEnabled: false },
    { key: "auto_generate_policy", label: "自动生成策略", runtimeEnabled: false },
    { key: "close_policy", label: "关闭策略", runtimeEnabled: false },
  ]),
  commands: Object.freeze([
    { key: "submit_sales_order", label: "提交销售订单", runtimeEnabled: false },
    { key: "approve_sales_order", label: "审批销售订单", runtimeEnabled: false },
    { key: "review_purchase_order", label: "评审采购订单", runtimeEnabled: false },
    { key: "release_payment", label: "付款放行", runtimeEnabled: false },
    { key: "finished_goods_quality_decide", label: "成品质检判定", runtimeEnabled: false },
    { key: "release_shipment_finance", label: "出货财务放行", runtimeEnabled: false },
    { key: "ship_shipment", label: "仓库执行出货", runtimeEnabled: false },
    { key: "create_receivable_lead", label: "创建应收线索", runtimeEnabled: false },
  ]),
});
