export const customerPackageSchema = Object.freeze({
  schemaKey: "customer-package-schema-v1",
  status: "draft_schema",
  runtimeEnabled: false,
  requiredTopLevelKeys: Object.freeze([
    "customerKey",
    "packageKey",
    "status",
    "runtimeEnabled",
    "sourcePolicy",
    "boundaries",
    "workflows",
    "businessFlows",
    "stateMachines",
    "processPolicies",
    "extensionPoints",
  ]),
  allowedStatuses: Object.freeze(["draft", "preview_only"]),
  allowedWorkflowNodeTypes: Object.freeze([
    "human_task",
    "approval",
    "domain_command_preview",
    "wait_event",
    "end",
  ]),
  allowedPolicyKinds: Object.freeze([
    "skip_policy",
    "auto_generate_policy",
    "close_policy",
  ]),
  allowedProcessPolicyRuleKeys: Object.freeze([
    "key",
    "when",
    "decision",
    "action",
    "note",
  ]),
  requiredProcessPolicyRuleTriggerKeys: Object.freeze(["key", "when"]),
  requiredProcessPolicyRuleResultKeys: Object.freeze(["decision", "action"]),
  forbiddenProcessPolicyRuleKeys: Object.freeze([
    "handler",
    "module",
    "runtimeEnabled",
    "runtime_enabled",
    "writesFact",
    "writes_fact",
    "writesInventoryFacts",
    "writesShipmentFacts",
    "writesFinanceFacts",
  ]),
  allowedPrintTemplateKeys: Object.freeze([
    "material-purchase-contract",
    "processing-contract",
  ]),
  allowedPrintPartyDefaultKeys: Object.freeze([
    "buyerCompany",
    "buyerContact",
    "buyerPhone",
    "buyerAddress",
    "buyerSigner",
  ]),
  requiredPrintPartyDefaultKeys: Object.freeze([
    "buyerCompany",
    "buyerContact",
    "buyerAddress",
  ]),
  requiredBoundaryFalseKeys: Object.freeze([
    "createsTenant",
    "changesSchema",
    "changesMigration",
    "changesBackendRbac",
    "changesWorkflowFactRules",
    "changesRuntimeLoader",
    "executesImport",
    "executesRealImport",
    "writesBusinessRecords",
    "writesFacts",
    "writesInventoryFacts",
    "writesShipmentFacts",
    "writesFinanceFacts",
  ]),
  forbiddenPayloadKeys: Object.freeze([
    "rows",
    "rawRows",
    "rawValues",
    "records",
    "secrets",
    "secret",
    "sql",
    "go",
    "js",
  ]),
  forbiddenTargets: Object.freeze([
    "tenant_id",
    "business_records",
    "schema",
    "migration",
    "rbac",
    "inventory_txns",
    "inventory_balances",
    "shipments",
    "shipment_items",
    "finance_facts",
    "workflow_done_to_fact_posted",
    "shipping_released_to_shipped",
  ]),
  previewSections: Object.freeze([
    "identity",
    "workflows",
    "businessFlows",
    "stateMachines",
    "processPolicies",
    "extensionPoints",
    "printTemplateDefaults",
    "guardrails",
  ]),
});
