-- Create "finance_payments" table
CREATE TABLE "finance_payments" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "payment_no" character varying NOT NULL,
  "direction" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'DRAFT',
  "counterparty_type" character varying NOT NULL,
  "counterparty_id" bigint NOT NULL,
  "amount" numeric(20,6) NOT NULL,
  "currency" character varying NOT NULL,
  "account_ref" character varying NOT NULL,
  "evidence_ref" character varying NOT NULL,
  "idempotency_key" character varying NOT NULL,
  "idempotency_payload_hash" character varying NOT NULL,
  "version" bigint NOT NULL DEFAULT 1,
  "occurred_at" timestamptz NOT NULL,
  "posted_at" timestamptz NULL,
  "posted_by" bigint NULL,
  "reversed_at" timestamptz NULL,
  "reversed_by" bigint NULL,
  "reverse_reason" character varying NULL,
  "created_by" bigint NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "finance_payments_amount_positive" CHECK (amount > (0)::numeric),
  CONSTRAINT "finance_payments_counterparty_allowed" CHECK ((counterparty_type)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'SUPPLIER'::character varying])::text[])),
  CONSTRAINT "finance_payments_currency_allowed" CHECK ((currency)::text = ANY ((ARRAY['USD'::character varying, 'CNY'::character varying, 'HKD'::character varying])::text[])),
  CONSTRAINT "finance_payments_direction_allowed" CHECK ((direction)::text = ANY ((ARRAY['RECEIPT'::character varying, 'DISBURSEMENT'::character varying])::text[])),
  CONSTRAINT "finance_payments_intent_bundle" CHECK (((length(TRIM(BOTH FROM idempotency_key)) >= 1) AND (length(TRIM(BOTH FROM idempotency_key)) <= 128)) AND (length((idempotency_payload_hash)::text) = 64)),
  CONSTRAINT "finance_payments_status_allowed" CHECK ((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'POSTED'::character varying, 'REVERSED'::character varying])::text[])),
  CONSTRAINT "finance_payments_version_positive" CHECK (version > 0)
);
-- Create index "financepayment_counterparty_type_counterparty_id_currency_statu" to table: "finance_payments"
CREATE INDEX "financepayment_counterparty_type_counterparty_id_currency_statu" ON "finance_payments" ("counterparty_type", "counterparty_id", "currency", "status");
-- Create index "financepayment_created_by_idempotency_key" to table: "finance_payments"
CREATE UNIQUE INDEX "financepayment_created_by_idempotency_key" ON "finance_payments" ("created_by", "idempotency_key");
-- Create index "financepayment_payment_no" to table: "finance_payments"
CREATE UNIQUE INDEX "financepayment_payment_no" ON "finance_payments" ("payment_no");
-- Create "outsourcing_return_dispositions" table
CREATE TABLE "outsourcing_return_dispositions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "disposition_no" character varying NOT NULL,
  "quality_inspection_id" bigint NOT NULL,
  "outsourcing_return_fact_id" bigint NOT NULL,
  "disposition_type" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'DRAFT',
  "quantity" numeric(20,6) NOT NULL,
  "production_wip_batch_id" bigint NULL,
  "reason" character varying NOT NULL,
  "idempotency_key" character varying NOT NULL,
  "idempotency_payload_hash" character varying NOT NULL,
  "version" bigint NOT NULL DEFAULT 1,
  "posted_at" timestamptz NULL,
  "posted_by" bigint NULL,
  "cancelled_at" timestamptz NULL,
  "cancelled_by" bigint NULL,
  "cancel_reason" character varying NULL,
  "created_by" bigint NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "outsourcing_return_dispositions_intent_bundle" CHECK (((length(TRIM(BOTH FROM idempotency_key)) >= 1) AND (length(TRIM(BOTH FROM idempotency_key)) <= 128)) AND (length((idempotency_payload_hash)::text) = 64)),
  CONSTRAINT "outsourcing_return_dispositions_quantity_positive" CHECK (quantity > (0)::numeric),
  CONSTRAINT "outsourcing_return_dispositions_status_allowed" CHECK ((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'POSTED'::character varying, 'CANCELLED'::character varying])::text[])),
  CONSTRAINT "outsourcing_return_dispositions_type_allowed" CHECK ((disposition_type)::text = ANY ((ARRAY['RETURN_TO_VENDOR'::character varying, 'REWORK'::character varying])::text[])),
  CONSTRAINT "outsourcing_return_dispositions_version_positive" CHECK (version > 0)
);
-- Create index "outsourcingreturndisposition_created_by_idempotency_key" to table: "outsourcing_return_dispositions"
CREATE UNIQUE INDEX "outsourcingreturndisposition_created_by_idempotency_key" ON "outsourcing_return_dispositions" ("created_by", "idempotency_key");
-- Create index "outsourcingreturndisposition_disposition_no" to table: "outsourcing_return_dispositions"
CREATE UNIQUE INDEX "outsourcingreturndisposition_disposition_no" ON "outsourcing_return_dispositions" ("disposition_no");
-- Create index "outsourcingreturndisposition_outsourcing_return_fact_id_status" to table: "outsourcing_return_dispositions"
CREATE INDEX "outsourcingreturndisposition_outsourcing_return_fact_id_status" ON "outsourcing_return_dispositions" ("outsourcing_return_fact_id", "status");
-- Create index "outsourcingreturndisposition_quality_inspection_id" to table: "outsourcing_return_dispositions"
CREATE UNIQUE INDEX "outsourcingreturndisposition_quality_inspection_id" ON "outsourcing_return_dispositions" ("quality_inspection_id") WHERE ((status)::text <> 'CANCELLED'::text);
-- Modify "quality_inspections" table
ALTER TABLE "quality_inspections" ADD CONSTRAINT "quality_inspections_superseded_bundle" CHECK (((superseded_at IS NULL) AND (superseded_by IS NULL) AND (superseded_reason IS NULL)) OR ((superseded_at IS NOT NULL) AND (superseded_by IS NOT NULL) AND (superseded_reason IS NOT NULL) AND (length(TRIM(BOTH FROM superseded_reason)) > 0))), ADD COLUMN "correction_of_inspection_id" bigint NULL, ADD COLUMN "superseded_at" timestamptz NULL, ADD COLUMN "superseded_by" bigint NULL, ADD COLUMN "superseded_reason" character varying NULL;
-- Create index "qualityinspection_correction_of_inspection_id" to table: "quality_inspections"
CREATE UNIQUE INDEX "qualityinspection_correction_of_inspection_id" ON "quality_inspections" ("correction_of_inspection_id") WHERE (correction_of_inspection_id IS NOT NULL);
-- Modify "workflow_tasks" table
ALTER TABLE "workflow_tasks" ADD CONSTRAINT "workflow_tasks_create_intent_bundle" CHECK (((create_idempotency_key IS NULL) AND (create_intent_hash IS NULL)) OR ((create_idempotency_key IS NOT NULL) AND (create_intent_hash IS NOT NULL) AND (created_by IS NOT NULL) AND ((length(TRIM(BOTH FROM create_idempotency_key)) >= 1) AND (length(TRIM(BOTH FROM create_idempotency_key)) <= 128)) AND (length((create_intent_hash)::text) = 64))), ADD COLUMN "create_idempotency_key" character varying NULL, ADD COLUMN "create_intent_hash" character varying NULL;
-- Create index "workflowtask_created_by_create_idempotency_key" to table: "workflow_tasks"
CREATE UNIQUE INDEX "workflowtask_created_by_create_idempotency_key" ON "workflow_tasks" ("created_by", "create_idempotency_key") WHERE (create_idempotency_key IS NOT NULL);
-- Modify "process_node_instances" table
ALTER TABLE "process_node_instances" ADD CONSTRAINT "process_node_instances_recovery_bundle" CHECK (((domain_command_recovery_decision IS NULL) AND (domain_command_recovery_hash IS NULL) AND (domain_command_recovered_at IS NULL) AND (domain_command_recovered_by IS NULL)) OR (((domain_command_recovery_decision)::text = 'terminate_and_withdraw_downstream'::text) AND (domain_command_recovery_hash IS NOT NULL) AND (length((domain_command_recovery_hash)::text) = 64) AND (domain_command_recovered_at IS NOT NULL) AND (domain_command_recovered_by IS NOT NULL) AND ((node_type)::text = 'domain_command'::text) AND ((status)::text = 'completed'::text) AND ((domain_command_effect_state)::text = 'compensated'::text) AND (domain_command_result_hash IS NOT NULL) AND (domain_command_compensation_hash IS NOT NULL))), ADD COLUMN "domain_command_recovery_decision" character varying NULL, ADD COLUMN "domain_command_recovery_hash" character varying NULL, ADD COLUMN "domain_command_recovered_at" timestamptz NULL, ADD COLUMN "domain_command_recovered_by" bigint NULL;
-- Create "finance_credit_notes" table
CREATE TABLE "finance_credit_notes" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "credit_note_no" character varying NOT NULL,
  "finance_fact_id" bigint NOT NULL,
  "reversal_of_credit_note_id" bigint NULL,
  "amount" numeric(20,6) NOT NULL,
  "currency" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'POSTED',
  "reason" character varying NOT NULL,
  "idempotency_key" character varying NOT NULL,
  "idempotency_payload_hash" character varying NOT NULL,
  "created_by" bigint NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "finance_credit_notes_amount_positive" CHECK (amount > (0)::numeric),
  CONSTRAINT "finance_credit_notes_currency_allowed" CHECK ((currency)::text = ANY ((ARRAY['USD'::character varying, 'CNY'::character varying, 'HKD'::character varying])::text[])),
  CONSTRAINT "finance_credit_notes_intent_bundle" CHECK (((length(TRIM(BOTH FROM idempotency_key)) >= 1) AND (length(TRIM(BOTH FROM idempotency_key)) <= 128)) AND (length((idempotency_payload_hash)::text) = 64)),
  CONSTRAINT "finance_credit_notes_status_allowed" CHECK ((status)::text = ANY ((ARRAY['POSTED'::character varying, 'REVERSED'::character varying])::text[]))
);
-- Create index "financecreditnote_created_by_idempotency_key" to table: "finance_credit_notes"
CREATE UNIQUE INDEX "financecreditnote_created_by_idempotency_key" ON "finance_credit_notes" ("created_by", "idempotency_key");
-- Create index "financecreditnote_credit_note_no" to table: "finance_credit_notes"
CREATE UNIQUE INDEX "financecreditnote_credit_note_no" ON "finance_credit_notes" ("credit_note_no");
-- Create index "financecreditnote_finance_fact_id_status" to table: "finance_credit_notes"
CREATE INDEX "financecreditnote_finance_fact_id_status" ON "finance_credit_notes" ("finance_fact_id", "status");
-- Create index "financecreditnote_reversal_of_credit_note_id" to table: "finance_credit_notes"
CREATE UNIQUE INDEX "financecreditnote_reversal_of_credit_note_id" ON "finance_credit_notes" ("reversal_of_credit_note_id") WHERE (reversal_of_credit_note_id IS NOT NULL);
-- Create "purchase_rejection_dispositions" table
CREATE TABLE "purchase_rejection_dispositions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "disposition_no" character varying NOT NULL,
  "quality_inspection_id" bigint NOT NULL,
  "purchase_receipt_id" bigint NOT NULL,
  "purchase_receipt_item_id" bigint NOT NULL,
  "disposition_type" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'DRAFT',
  "quantity" numeric(20,6) NOT NULL,
  "supplier_id" bigint NULL,
  "supplier_name" character varying NOT NULL,
  "reason" character varying NOT NULL,
  "idempotency_key" character varying NOT NULL,
  "idempotency_payload_hash" character varying NOT NULL,
  "version" bigint NOT NULL DEFAULT 1,
  "posted_at" timestamptz NULL,
  "posted_by" bigint NULL,
  "cancelled_at" timestamptz NULL,
  "cancelled_by" bigint NULL,
  "cancel_reason" character varying NULL,
  "created_by" bigint NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "purchase_rejection_dispositions_intent_bundle" CHECK (((length(TRIM(BOTH FROM idempotency_key)) >= 1) AND (length(TRIM(BOTH FROM idempotency_key)) <= 128)) AND (length((idempotency_payload_hash)::text) = 64)),
  CONSTRAINT "purchase_rejection_dispositions_quantity_positive" CHECK (quantity > (0)::numeric),
  CONSTRAINT "purchase_rejection_dispositions_status_allowed" CHECK ((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'POSTED'::character varying, 'CANCELLED'::character varying])::text[])),
  CONSTRAINT "purchase_rejection_dispositions_type_allowed" CHECK ((disposition_type)::text = ANY ((ARRAY['RETURN_TO_VENDOR'::character varying, 'REPLACE'::character varying])::text[])),
  CONSTRAINT "purchase_rejection_dispositions_version_positive" CHECK (version > 0)
);
-- Create index "purchaserejectiondisposition_created_by_idempotency_key" to table: "purchase_rejection_dispositions"
CREATE UNIQUE INDEX "purchaserejectiondisposition_created_by_idempotency_key" ON "purchase_rejection_dispositions" ("created_by", "idempotency_key");
-- Create index "purchaserejectiondisposition_disposition_no" to table: "purchase_rejection_dispositions"
CREATE UNIQUE INDEX "purchaserejectiondisposition_disposition_no" ON "purchase_rejection_dispositions" ("disposition_no");
-- Create index "purchaserejectiondisposition_quality_inspection_id" to table: "purchase_rejection_dispositions"
CREATE UNIQUE INDEX "purchaserejectiondisposition_quality_inspection_id" ON "purchase_rejection_dispositions" ("quality_inspection_id") WHERE ((status)::text <> 'CANCELLED'::text);
-- Create "production_exception_decisions" table
CREATE TABLE "production_exception_decisions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "decision_no" character varying NOT NULL,
  "decision_type" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'SUBMITTED',
  "production_order_id" bigint NOT NULL,
  "production_order_item_id" bigint NOT NULL,
  "production_material_requirement_id" bigint NULL,
  "production_wip_batch_id" bigint NULL,
  "quality_inspection_id" bigint NULL,
  "requested_quantity" numeric(20,6) NOT NULL,
  "approved_quantity" numeric(20,6) NULL,
  "reason" character varying NOT NULL,
  "idempotency_key" character varying NOT NULL,
  "idempotency_payload_hash" character varying NOT NULL,
  "version" bigint NOT NULL DEFAULT 1,
  "requested_by" bigint NOT NULL,
  "requested_at" timestamptz NOT NULL,
  "decided_by" bigint NULL,
  "decided_at" timestamptz NULL,
  "decision_reason" character varying NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "production_exception_decisions_intent_bundle" CHECK (((length(TRIM(BOTH FROM idempotency_key)) >= 1) AND (length(TRIM(BOTH FROM idempotency_key)) <= 128)) AND (length((idempotency_payload_hash)::text) = 64)),
  CONSTRAINT "production_exception_decisions_quantity_positive" CHECK ((requested_quantity > (0)::numeric) AND ((approved_quantity IS NULL) OR (approved_quantity > (0)::numeric))),
  CONSTRAINT "production_exception_decisions_status_allowed" CHECK ((status)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying])::text[])),
  CONSTRAINT "production_exception_decisions_type_allowed" CHECK ((decision_type)::text = ANY ((ARRAY['SCRAP'::character varying, 'OVER_ISSUE'::character varying, 'WIP_CONCESSION'::character varying])::text[])),
  CONSTRAINT "production_exception_decisions_version_positive" CHECK (version > 0)
);
-- Create index "productionexceptiondecision_decision_no" to table: "production_exception_decisions"
CREATE UNIQUE INDEX "productionexceptiondecision_decision_no" ON "production_exception_decisions" ("decision_no");
-- Create index "productionexceptiondecision_decision_type_status_requested_at" to table: "production_exception_decisions"
CREATE INDEX "productionexceptiondecision_decision_type_status_requested_at" ON "production_exception_decisions" ("decision_type", "status", "requested_at");
-- Create index "productionexceptiondecision_production_order_id_production_orde" to table: "production_exception_decisions"
CREATE INDEX "productionexceptiondecision_production_order_id_production_orde" ON "production_exception_decisions" ("production_order_id", "production_order_item_id");
-- Create index "productionexceptiondecision_quality_inspection_id" to table: "production_exception_decisions"
CREATE UNIQUE INDEX "productionexceptiondecision_quality_inspection_id" ON "production_exception_decisions" ("quality_inspection_id") WHERE (((decision_type)::text = 'WIP_CONCESSION'::text) AND (((status)::text = 'SUBMITTED'::text) OR ((status)::text = 'APPROVED'::text)));
-- Create index "productionexceptiondecision_requested_by_idempotency_key" to table: "production_exception_decisions"
CREATE UNIQUE INDEX "productionexceptiondecision_requested_by_idempotency_key" ON "production_exception_decisions" ("requested_by", "idempotency_key");
-- Modify "production_facts" table
ALTER TABLE "production_facts" DROP CONSTRAINT "production_facts_type_allowed", ADD CONSTRAINT "production_facts_type_allowed" CHECK ((fact_type)::text = ANY ((ARRAY['MATERIAL_ISSUE'::character varying, 'FINISHED_GOODS_RECEIPT'::character varying, 'REWORK'::character varying, 'SCRAP'::character varying])::text[]));
-- Create "finance_allocations" table
CREATE TABLE "finance_allocations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "finance_fact_id" bigint NOT NULL,
  "amount" numeric(20,6) NOT NULL,
  "currency" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'POSTED',
  "reversal_of_allocation_id" bigint NULL,
  "idempotency_key" character varying NOT NULL,
  "created_by" bigint NOT NULL,
  "created_at" timestamptz NOT NULL,
  "payment_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "finance_allocations_finance_payments_allocations" FOREIGN KEY ("payment_id") REFERENCES "finance_payments" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "finance_allocations_amount_positive" CHECK (amount > (0)::numeric),
  CONSTRAINT "finance_allocations_currency_allowed" CHECK ((currency)::text = ANY ((ARRAY['USD'::character varying, 'CNY'::character varying, 'HKD'::character varying])::text[])),
  CONSTRAINT "finance_allocations_reversal_not_self" CHECK ((reversal_of_allocation_id IS NULL) OR (reversal_of_allocation_id <> id)),
  CONSTRAINT "finance_allocations_status_allowed" CHECK ((status)::text = ANY ((ARRAY['POSTED'::character varying, 'REVERSED'::character varying])::text[]))
);
-- Create index "financeallocation_idempotency_key" to table: "finance_allocations"
CREATE UNIQUE INDEX "financeallocation_idempotency_key" ON "finance_allocations" ("idempotency_key");
-- Create index "financeallocation_payment_id_finance_fact_id_status" to table: "finance_allocations"
CREATE INDEX "financeallocation_payment_id_finance_fact_id_status" ON "finance_allocations" ("payment_id", "finance_fact_id", "status");
-- Create index "financeallocation_reversal_of_allocation_id" to table: "finance_allocations"
CREATE UNIQUE INDEX "financeallocation_reversal_of_allocation_id" ON "finance_allocations" ("reversal_of_allocation_id") WHERE (reversal_of_allocation_id IS NOT NULL);
-- Create "inventory_operations" table
CREATE TABLE "inventory_operations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "operation_no" character varying NOT NULL,
  "operation_type" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'DRAFT',
  "reason" character varying NOT NULL,
  "approval_ref" character varying NULL,
  "idempotency_key" character varying NOT NULL,
  "idempotency_payload_hash" character varying NOT NULL,
  "idempotency_item_count" bigint NOT NULL,
  "version" bigint NOT NULL DEFAULT 1,
  "posted_at" timestamptz NULL,
  "posted_by" bigint NULL,
  "cancelled_at" timestamptz NULL,
  "cancelled_by" bigint NULL,
  "cancel_reason" character varying NULL,
  "created_by" bigint NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "inventory_operations_cancel_bundle" CHECK ((((status)::text = 'CANCELLED'::text) AND (cancelled_at IS NOT NULL) AND (cancelled_by IS NOT NULL) AND (cancel_reason IS NOT NULL) AND (length(TRIM(BOTH FROM cancel_reason)) > 0)) OR (((status)::text <> 'CANCELLED'::text) AND (cancelled_at IS NULL) AND (cancelled_by IS NULL) AND (cancel_reason IS NULL))),
  CONSTRAINT "inventory_operations_intent_bundle" CHECK (((length(TRIM(BOTH FROM idempotency_key)) >= 1) AND (length(TRIM(BOTH FROM idempotency_key)) <= 128)) AND (length((idempotency_payload_hash)::text) = 64) AND (idempotency_item_count > 0)),
  CONSTRAINT "inventory_operations_status_allowed" CHECK ((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'POSTED'::character varying, 'CANCELLED'::character varying])::text[])),
  CONSTRAINT "inventory_operations_type_allowed" CHECK ((operation_type)::text = ANY ((ARRAY['CYCLE_COUNT'::character varying, 'TRANSFER'::character varying, 'MANUAL_ADJUSTMENT'::character varying])::text[])),
  CONSTRAINT "inventory_operations_version_positive" CHECK (version > 0)
);
-- Create index "inventoryoperation_created_by_idempotency_key" to table: "inventory_operations"
CREATE UNIQUE INDEX "inventoryoperation_created_by_idempotency_key" ON "inventory_operations" ("created_by", "idempotency_key");
-- Create index "inventoryoperation_operation_no" to table: "inventory_operations"
CREATE UNIQUE INDEX "inventoryoperation_operation_no" ON "inventory_operations" ("operation_no");
-- Create index "inventoryoperation_operation_type_status_created_at" to table: "inventory_operations"
CREATE INDEX "inventoryoperation_operation_type_status_created_at" ON "inventory_operations" ("operation_type", "status", "created_at");
-- Create "inventory_operation_items" table
CREATE TABLE "inventory_operation_items" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "line_no" character varying NOT NULL,
  "subject_type" character varying NOT NULL,
  "subject_id" bigint NOT NULL,
  "product_sku_id" bigint NULL,
  "from_warehouse_id" bigint NOT NULL,
  "from_lot_id" bigint NULL,
  "to_warehouse_id" bigint NULL,
  "to_lot_id" bigint NULL,
  "unit_id" bigint NOT NULL,
  "expected_quantity" numeric(20,6) NULL,
  "counted_quantity" numeric(20,6) NULL,
  "adjustment_quantity" numeric(20,6) NOT NULL,
  "note" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "operation_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "inventory_operation_items_inventory_operations_items" FOREIGN KEY ("operation_id") REFERENCES "inventory_operations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "inventory_operation_items_counted_shape" CHECK ((counted_quantity IS NULL) OR (counted_quantity >= (0)::numeric)),
  CONSTRAINT "inventory_operation_items_nonzero_adjustment" CHECK (adjustment_quantity <> (0)::numeric),
  CONSTRAINT "inventory_operation_items_quantity_shape" CHECK ((expected_quantity IS NULL) OR (expected_quantity >= (0)::numeric)),
  CONSTRAINT "inventory_operation_items_sku_allowed" CHECK ((product_sku_id IS NULL) OR ((subject_type)::text = 'PRODUCT'::text)),
  CONSTRAINT "inventory_operation_items_subject_allowed" CHECK ((subject_type)::text = ANY ((ARRAY['MATERIAL'::character varying, 'PRODUCT'::character varying])::text[]))
);
-- Create index "inventoryoperationitem_operation_id_line_no" to table: "inventory_operation_items"
CREATE UNIQUE INDEX "inventoryoperationitem_operation_id_line_no" ON "inventory_operation_items" ("operation_id", "line_no");
-- Create index "inventoryoperationitem_subject_type_subject_id_from_warehouse_i" to table: "inventory_operation_items"
CREATE INDEX "inventoryoperationitem_subject_type_subject_id_from_warehouse_i" ON "inventory_operation_items" ("subject_type", "subject_id", "from_warehouse_id", "from_lot_id");
-- Create "sales_returns" table
CREATE TABLE "sales_returns" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "return_no" character varying NOT NULL,
  "shipment_id" bigint NOT NULL,
  "customer_id" bigint NOT NULL,
  "customer_name_snapshot" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'DRAFT',
  "reason" character varying NOT NULL,
  "idempotency_key" character varying NOT NULL,
  "idempotency_payload_hash" character varying NOT NULL,
  "idempotency_item_count" bigint NOT NULL,
  "version" bigint NOT NULL DEFAULT 1,
  "approved_at" timestamptz NULL,
  "approved_by" bigint NULL,
  "received_at" timestamptz NULL,
  "received_by" bigint NULL,
  "cancelled_at" timestamptz NULL,
  "cancelled_by" bigint NULL,
  "cancel_reason" character varying NULL,
  "created_by" bigint NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "sales_returns_intent_bundle" CHECK (((length(TRIM(BOTH FROM idempotency_key)) >= 1) AND (length(TRIM(BOTH FROM idempotency_key)) <= 128)) AND (length((idempotency_payload_hash)::text) = 64) AND (idempotency_item_count > 0)),
  CONSTRAINT "sales_returns_status_allowed" CHECK ((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'APPROVED'::character varying, 'RECEIVED'::character varying, 'CANCELLED'::character varying])::text[])),
  CONSTRAINT "sales_returns_version_positive" CHECK (version > 0)
);
-- Create index "salesreturn_created_by_idempotency_key" to table: "sales_returns"
CREATE UNIQUE INDEX "salesreturn_created_by_idempotency_key" ON "sales_returns" ("created_by", "idempotency_key");
-- Create index "salesreturn_return_no" to table: "sales_returns"
CREATE UNIQUE INDEX "salesreturn_return_no" ON "sales_returns" ("return_no");
-- Create index "salesreturn_shipment_id_status" to table: "sales_returns"
CREATE INDEX "salesreturn_shipment_id_status" ON "sales_returns" ("shipment_id", "status");
-- Create "sales_return_items" table
CREATE TABLE "sales_return_items" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "line_no" character varying NOT NULL,
  "shipment_item_id" bigint NOT NULL,
  "subject_type" character varying NOT NULL DEFAULT 'PRODUCT',
  "product_id" bigint NOT NULL,
  "product_sku_id" bigint NULL,
  "warehouse_id" bigint NOT NULL,
  "unit_id" bigint NOT NULL,
  "lot_id" bigint NULL,
  "quality_inspection_id" bigint NOT NULL,
  "quantity" numeric(20,6) NOT NULL,
  "condition" character varying NOT NULL DEFAULT 'PENDING_INSPECTION',
  "note" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "sales_return_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "sales_return_items_sales_returns_items" FOREIGN KEY ("sales_return_id") REFERENCES "sales_returns" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "sales_return_items_quantity_positive" CHECK (quantity > (0)::numeric),
  CONSTRAINT "sales_return_items_subject_allowed" CHECK ((subject_type)::text = 'PRODUCT'::text)
);
-- Create index "salesreturnitem_product_id_product_sku_id_warehouse_id_lot_id" to table: "sales_return_items"
CREATE INDEX "salesreturnitem_product_id_product_sku_id_warehouse_id_lot_id" ON "sales_return_items" ("product_id", "product_sku_id", "warehouse_id", "lot_id");
-- Create index "salesreturnitem_quality_inspection_id" to table: "sales_return_items"
CREATE UNIQUE INDEX "salesreturnitem_quality_inspection_id" ON "sales_return_items" ("quality_inspection_id");
-- Create index "salesreturnitem_sales_return_id_line_no" to table: "sales_return_items"
CREATE UNIQUE INDEX "salesreturnitem_sales_return_id_line_no" ON "sales_return_items" ("sales_return_id", "line_no");
-- Create index "salesreturnitem_shipment_item_id" to table: "sales_return_items"
CREATE INDEX "salesreturnitem_shipment_item_id" ON "sales_return_items" ("shipment_item_id");
