-- Create "quality_inspections" table
CREATE TABLE "quality_inspections" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "inspection_no" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'DRAFT',
  "result" character varying NULL,
  "original_lot_status" character varying NOT NULL DEFAULT '',
  "inspected_at" timestamptz NULL,
  "inspector_id" bigint NULL,
  "decision_note" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "inventory_lot_id" bigint NOT NULL,
  "material_id" bigint NOT NULL,
  "purchase_receipt_id" bigint NOT NULL,
  "purchase_receipt_item_id" bigint NULL,
  "warehouse_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "quality_inspections_inventory_lots_quality_inspections" FOREIGN KEY ("inventory_lot_id") REFERENCES "inventory_lots" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "quality_inspections_materials_quality_inspections" FOREIGN KEY ("material_id") REFERENCES "materials" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "quality_inspections_purchase_receipt_items_quality_inspections" FOREIGN KEY ("purchase_receipt_item_id") REFERENCES "purchase_receipt_items" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "quality_inspections_purchase_receipts_quality_inspections" FOREIGN KEY ("purchase_receipt_id") REFERENCES "purchase_receipts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "quality_inspections_warehouses_quality_inspections" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "qualityinspection_inspected_at" to table: "quality_inspections"
CREATE INDEX "qualityinspection_inspected_at" ON "quality_inspections" ("inspected_at");
-- Create index "qualityinspection_inspection_no" to table: "quality_inspections"
CREATE UNIQUE INDEX "qualityinspection_inspection_no" ON "quality_inspections" ("inspection_no");
-- Create index "qualityinspection_inventory_lot_id" to table: "quality_inspections"
CREATE INDEX "qualityinspection_inventory_lot_id" ON "quality_inspections" ("inventory_lot_id");
-- Create index "qualityinspection_inventory_lot_id_submitted" to table: "quality_inspections"
CREATE UNIQUE INDEX "qualityinspection_inventory_lot_id_submitted" ON "quality_inspections" ("inventory_lot_id") WHERE ((status)::text = 'SUBMITTED'::text);
-- Create index "qualityinspection_material_id" to table: "quality_inspections"
CREATE INDEX "qualityinspection_material_id" ON "quality_inspections" ("material_id");
-- Create index "qualityinspection_purchase_receipt_id" to table: "quality_inspections"
CREATE INDEX "qualityinspection_purchase_receipt_id" ON "quality_inspections" ("purchase_receipt_id");
-- Create index "qualityinspection_purchase_receipt_item_id" to table: "quality_inspections"
CREATE INDEX "qualityinspection_purchase_receipt_item_id" ON "quality_inspections" ("purchase_receipt_item_id");
-- Create index "qualityinspection_status" to table: "quality_inspections"
CREATE INDEX "qualityinspection_status" ON "quality_inspections" ("status");
-- Create index "qualityinspection_warehouse_id" to table: "quality_inspections"
CREATE INDEX "qualityinspection_warehouse_id" ON "quality_inspections" ("warehouse_id");
