export const plushIndustryTemplateConfig = Object.freeze({
  templateKey: "plush",
  label: "毛绒玩具行业模板",
  reviewMilestone: "industry-template-candidate",
  status: "candidate",
  runtimeEnabled: false,
  scope:
    "Industry Template candidate only. Use this file for review, QA and future customer package preparation; do not import it into runtime loaders until product review approves it.",
  sourcePolicy: Object.freeze({
    seedCustomerKeys: Object.freeze(["yoyoosun"]),
    singleCustomerMayOnlyCreateCandidate: true,
    requiresHumanIndustryReview: true,
    requiresMultiCustomerRepeatForDefault: true,
    customerSpecificTermsAllowedInDefaults: false,
  }),
  boundaries: Object.freeze({
    createsTenant: false,
    changesSchema: false,
    changesMigration: false,
    changesBackendRbac: false,
    changesWorkflowFactRules: false,
    changesRuntimeMenuLoader: false,
    executesImport: false,
    writesBusinessRecords: false,
    writesFacts: false,
  }),
  defaultRoles: Object.freeze([
    {
      key: "boss",
      label: "老板 / 管理层",
      classification: "industry_default_candidate",
      evidence: "mobile-workflow-target-release-evidence",
      boundary: "只作为管理层审批和全链路查看候选；不绕过 RBAC 或任务 owner / assignee 守卫。",
    },
    {
      key: "sales",
      label: "业务",
      classification: "industry_default_candidate",
      evidence: "试用账号角色菜单核对清单.md",
      boundary: "负责客户、销售订单和交期协同；销售订单不等于出货事实。",
    },
    {
      key: "purchase",
      label: "采购",
      classification: "industry_default_candidate",
      evidence: "试用账号角色菜单核对清单.md",
      boundary: "负责采购协同和入库跟进；采购承诺不替代 purchase_receipts 事实。",
    },
    {
      key: "warehouse",
      label: "仓库",
      classification: "industry_default_candidate",
      evidence: "mobile-workflow-target-release-evidence",
      boundary: "负责收货、库存、入库确认和出货放行协同；岗位任务 done 不写库存事实。",
    },
    {
      key: "quality",
      label: "品质",
      classification: "industry_default_candidate",
      evidence: "mobile-workflow-target-release-evidence",
      boundary: "负责检验协同；quality task done 不等于 quality_inspections 判定。",
    },
    {
      key: "finance",
      label: "财务",
      classification: "industry_default_candidate",
      evidence: "operational-fact-target-release-evidence",
      boundary: "负责来源明确的应收、应付、发票和单笔核对；PAYMENT 当前只读，不开放收付款录入，也不能从出货放行直接生成财务事实。",
    },
    {
      key: "pmc",
      label: "PMC",
      classification: "industry_default_candidate",
      evidence: "mobile-workflow-target-release-evidence",
      boundary: "负责齐套、排产、异常分发和催办；不替其他角色写事实。",
    },
    {
      key: "engineering",
      label: "工程",
      classification: "industry_default_candidate",
      evidence: "试用账号角色菜单核对清单.md",
      boundary: "负责产品资料、工序和 BOM 资料补齐；工程任务完成不写采购、库存、生产、成本或财务事实。",
    },
    {
      key: "production",
      label: "生产经理",
      classification: "industry_default_candidate",
      evidence: "mobile-workflow-target-release-evidence",
      boundary: "负责生产排程、进度和返工协同；生产事实仍由 OperationalFactUsecase 写入。",
    },
  ]),
  desktopMenuTemplate: Object.freeze({
    classification: "industry_default_candidate",
    sections: Object.freeze([
      {
        title: "看板中心",
        items: Object.freeze(["global-dashboard", "task-board", "business-dashboard"]),
      },
      {
        title: "主数据",
        items: Object.freeze(["customers", "suppliers", "products", "materials"]),
      },
      {
        title: "销售管理",
        items: Object.freeze(["sales-orders"]),
      },
      {
        title: "产品工程",
        items: Object.freeze(["material-bom", "processes"]),
      },
      {
        title: "采购管理",
        items: Object.freeze(["accessories-purchase"]),
      },
      {
        title: "质检管理",
        items: Object.freeze(["quality-inspections"]),
      },
      {
        title: "库存管理",
        items: Object.freeze(["inbound", "inventory"]),
      },
      {
        title: "委外管理",
        items: Object.freeze(["processing-contracts"]),
      },
      {
        title: "生产管理",
        items: Object.freeze([
          "production-scheduling",
          "production-progress",
          "production-exceptions",
        ]),
      },
      {
        title: "出货管理",
        items: Object.freeze(["shipping-release", "outbound", "shipments"]),
      },
      {
        title: "财务业务",
        items: Object.freeze([
          "reconciliation",
          "payables",
          "receivables",
          "invoices",
        ]),
      },
      {
        title: "运营工具",
        items: Object.freeze(["print-center", "exception-flow"]),
        classification: "customer_sample_only",
        boundary: "当前只保留既有两套模板入口；不把单客户合同样式升成行业默认模板。",
      },
      {
        title: "系统管理",
        items: Object.freeze(["permission-center"]),
      },
    ]),
  }),
  mobileTaskPatternTemplate: Object.freeze([
    {
      key: "approval",
      label: "审批处理",
      roles: Object.freeze(["boss"]),
      classification: "industry_default_candidate",
      factBoundary: "workflow_only",
      note: "审批任务只推进协同状态，不写库存、出货或财务事实。",
    },
    {
      key: "warehouse_inbound",
      label: "入库确认",
      roles: Object.freeze(["warehouse"]),
      classification: "industry_default_candidate",
      factBoundary: "workflow_only",
      note: "入库确认 task done 不等于采购入库或成品入库事实过账。",
    },
    {
      key: "quality_check",
      label: "现场质检协同",
      roles: Object.freeze(["quality"]),
      classification: "industry_default_candidate",
      factBoundary: "workflow_only",
      note: "移动端留痕不替代 quality_inspections 判定。",
    },
    {
      key: "engineering_data",
      label: "工程资料补齐",
      roles: Object.freeze(["engineering"]),
      classification: "industry_default_candidate",
      factBoundary: "workflow_only",
      note: "工程资料任务只推进产品、工序和 BOM 资料补齐协同，不自动生成采购、库存、生产、成本或财务事实。",
    },
    {
      key: "shipment_release",
      label: "出货放行（来源生成）",
      roles: Object.freeze(["warehouse"]),
      classification: "industry_default_candidate",
      factBoundary: "workflow_only",
      sourceGenerated: true,
      configurableProducer: false,
      producer: "shipment.submit_release",
      sourcePageKey: "shipments",
      sourceAction: "submit_shipment_release",
      ownerRoleKey: "warehouse",
      precondition: "出货前成品检验如已发起，必须先合格或让步接收，才能提交放行。",
      downstream: "仓库确认真实出货并达到 SHIPPED 后，财务才可按出货来源办理应收或发票。",
      note: "放行任务完成只表示 shipping_released，不自动确认出货、扣库存或生成财务事实。",
    },
    {
      key: "photo_scan_attachment",
      label: "拍照 / 扫码 / 附件",
      roles: Object.freeze(["warehouse", "quality", "production"]),
      classification: "deferred",
      factBoundary: "not_delivered",
      note: "当前只交付 evidence 文本和 refs；真实附件服务、对象存储和扫码另评审。",
    },
  ]),
  fieldDisplayTemplate: Object.freeze([
    {
      module: "customers",
      label: "客户档案",
      classification: "industry_default_candidate",
      fields: Object.freeze(["customer_code", "display_name", "contact"]),
      deferred: Object.freeze(["credit_limit", "settlement_terms"]),
    },
    {
      module: "suppliers",
      label: "供应商档案",
      classification: "industry_default_candidate",
      fields: Object.freeze(["supplier_code", "supplier_type", "contact"]),
      deferred: Object.freeze(["supplier_material_scope", "settlement_note"]),
    },
    {
      module: "products",
      label: "产品档案",
      classification: "industry_default_candidate",
      fields: Object.freeze(["product_code", "product_name", "unit"]),
      deferred: Object.freeze(["sku_color", "sku_size", "version"]),
    },
    {
      module: "engineering",
      label: "产品工程",
      classification: "industry_default_candidate",
      fields: Object.freeze(["product", "process", "bom_version"]),
      deferred: Object.freeze(["route_planning", "cost_rollup", "mrp"]),
    },
    {
      module: "sales_orders",
      label: "销售订单",
      classification: "industry_default_candidate",
      fields: Object.freeze(["order_no", "customer", "expected_ship_date"]),
      deferred: Object.freeze(["auto_reservation", "auto_shipment"]),
    },
    {
      module: "purchase",
      label: "采购 / 委外",
      classification: "industry_default_candidate",
      fields: Object.freeze(["supplier", "material", "quantity", "due_date"]),
      deferred: Object.freeze(["purchase_order_runtime", "outsourcing_settlement"]),
    },
    {
      module: "finance",
      label: "财务事实",
      classification: "industry_default_candidate",
      fields: Object.freeze(["fact_no", "source_document", "counterparty", "amount", "currency", "status"]),
      deferred: Object.freeze(["invoice_detail", "payment_entry", "payment_reconciliation_detail"]),
    },
  ]),
  numberingRuleTemplate: Object.freeze([
    {
      domain: "customers",
      key: "customer_code",
      label: "客户编码",
      classification: "industry_default_candidate",
      decision: "review_required",
    },
    {
      domain: "suppliers",
      key: "supplier_code",
      label: "供应商编码",
      classification: "industry_default_candidate",
      decision: "review_required",
    },
    {
      domain: "products",
      key: "product_code",
      label: "产品编码",
      classification: "industry_default_candidate",
      decision: "review_required",
    },
    {
      domain: "sales_orders",
      key: "order_no",
      label: "销售订单编号",
      classification: "industry_default_candidate",
      decision: "review_required",
    },
    {
      domain: "purchase_orders",
      key: "purchase_order_no",
      label: "采购订单编号",
      classification: "deferred",
      decision: "deferred",
    },
    {
      domain: "shipments",
      key: "shipment_no",
      label: "出货单编号",
      classification: "industry_default_candidate",
      decision: "review_required",
    },
    {
      domain: "finance_facts",
      key: "fact_no",
      label: "财务事实编号",
      classification: "industry_default_candidate",
      decision: "review_required",
    },
  ]),
  importTemplate: Object.freeze({
    classification: "industry_default_candidate",
    canExecuteRealImport: false,
    mode: "dry_run_only",
    sources: Object.freeze([
      "customers",
      "suppliers",
      "contacts",
      "products",
      "sales_orders",
    ]),
    forbiddenAutoTargets: Object.freeze([
      "tenant_id",
      "business_records",
      "product_skus",
      "purchase_orders",
      "shipments",
      "inventory_txns",
      "finance_facts",
    ]),
    requiredEvidence: Object.freeze([
      "source_inventory",
      "field_classification",
      "dry_run_package",
      "unresolved_queue",
      "backup_evidence",
      "human_approval",
    ]),
  }),
  trainingAcceptanceTemplate: Object.freeze([
    {
      key: "login_rbac_menu",
      label: "登录 / 角色 / 菜单核对",
      classification: "industry_default_candidate",
      command: "scripts/qa/trial-account-rbac.mjs",
    },
    {
      key: "masterdata_source_document",
      label: "主数据和销售订单演练",
      classification: "industry_default_candidate",
      command: "scripts/qa/trial-simulated-data.mjs",
    },
    {
      key: "fact_closure",
      label: "事实闭环模拟验收",
      classification: "industry_default_candidate",
      command: "scripts/qa/operational-fact-simulated-closure.mjs",
    },
    {
      key: "mobile_workflow",
      label: "岗位任务端模拟验收",
      classification: "industry_default_candidate",
      command: "scripts/qa/mobile-workflow-simulated-closure.mjs",
    },
  ]),
  deferredItems: Object.freeze([
    "真实客户数据导入",
    "拍照上传 / 附件服务 / 对象存储",
    "扫码 / PDA / 条码枪",
    "产品 SKU / 颜色 / 尺寸正式模型",
    "采购订单运行时",
    "通用打印模板引擎",
    "报表 / 审计 / 外部集成增强",
    "SaaS tenant / license / billing",
  ]),
});
