// Code generated by ent, DO NOT EDIT.

package workpoolmembership

import (
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLTE(FieldID, id))
}

// CustomerKey applies equality check predicate on the "customer_key" field. It's identical to CustomerKeyEQ.
func CustomerKey(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldCustomerKey, v))
}

// ConfigRevision applies equality check predicate on the "config_revision" field. It's identical to ConfigRevisionEQ.
func ConfigRevision(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldConfigRevision, v))
}

// PoolKey applies equality check predicate on the "pool_key" field. It's identical to PoolKeyEQ.
func PoolKey(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldPoolKey, v))
}

// RoleKey applies equality check predicate on the "role_key" field. It's identical to RoleKeyEQ.
func RoleKey(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldRoleKey, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldUserID, v))
}

// Strategy applies equality check predicate on the "strategy" field. It's identical to StrategyEQ.
func Strategy(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldStrategy, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldPriority, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldUpdatedAt, v))
}

// CustomerKeyEQ applies the EQ predicate on the "customer_key" field.
func CustomerKeyEQ(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldCustomerKey, v))
}

// CustomerKeyNEQ applies the NEQ predicate on the "customer_key" field.
func CustomerKeyNEQ(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNEQ(FieldCustomerKey, v))
}

// CustomerKeyIn applies the In predicate on the "customer_key" field.
func CustomerKeyIn(vs ...string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldIn(FieldCustomerKey, vs...))
}

// CustomerKeyNotIn applies the NotIn predicate on the "customer_key" field.
func CustomerKeyNotIn(vs ...string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNotIn(FieldCustomerKey, vs...))
}

// CustomerKeyGT applies the GT predicate on the "customer_key" field.
func CustomerKeyGT(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGT(FieldCustomerKey, v))
}

// CustomerKeyGTE applies the GTE predicate on the "customer_key" field.
func CustomerKeyGTE(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGTE(FieldCustomerKey, v))
}

// CustomerKeyLT applies the LT predicate on the "customer_key" field.
func CustomerKeyLT(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLT(FieldCustomerKey, v))
}

// CustomerKeyLTE applies the LTE predicate on the "customer_key" field.
func CustomerKeyLTE(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLTE(FieldCustomerKey, v))
}

// CustomerKeyContains applies the Contains predicate on the "customer_key" field.
func CustomerKeyContains(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldContains(FieldCustomerKey, v))
}

// CustomerKeyHasPrefix applies the HasPrefix predicate on the "customer_key" field.
func CustomerKeyHasPrefix(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldHasPrefix(FieldCustomerKey, v))
}

// CustomerKeyHasSuffix applies the HasSuffix predicate on the "customer_key" field.
func CustomerKeyHasSuffix(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldHasSuffix(FieldCustomerKey, v))
}

// CustomerKeyEqualFold applies the EqualFold predicate on the "customer_key" field.
func CustomerKeyEqualFold(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEqualFold(FieldCustomerKey, v))
}

// CustomerKeyContainsFold applies the ContainsFold predicate on the "customer_key" field.
func CustomerKeyContainsFold(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldContainsFold(FieldCustomerKey, v))
}

// ConfigRevisionEQ applies the EQ predicate on the "config_revision" field.
func ConfigRevisionEQ(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldConfigRevision, v))
}

// ConfigRevisionNEQ applies the NEQ predicate on the "config_revision" field.
func ConfigRevisionNEQ(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNEQ(FieldConfigRevision, v))
}

// ConfigRevisionIn applies the In predicate on the "config_revision" field.
func ConfigRevisionIn(vs ...string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldIn(FieldConfigRevision, vs...))
}

// ConfigRevisionNotIn applies the NotIn predicate on the "config_revision" field.
func ConfigRevisionNotIn(vs ...string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNotIn(FieldConfigRevision, vs...))
}

// ConfigRevisionGT applies the GT predicate on the "config_revision" field.
func ConfigRevisionGT(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGT(FieldConfigRevision, v))
}

// ConfigRevisionGTE applies the GTE predicate on the "config_revision" field.
func ConfigRevisionGTE(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGTE(FieldConfigRevision, v))
}

// ConfigRevisionLT applies the LT predicate on the "config_revision" field.
func ConfigRevisionLT(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLT(FieldConfigRevision, v))
}

// ConfigRevisionLTE applies the LTE predicate on the "config_revision" field.
func ConfigRevisionLTE(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLTE(FieldConfigRevision, v))
}

// ConfigRevisionContains applies the Contains predicate on the "config_revision" field.
func ConfigRevisionContains(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldContains(FieldConfigRevision, v))
}

// ConfigRevisionHasPrefix applies the HasPrefix predicate on the "config_revision" field.
func ConfigRevisionHasPrefix(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldHasPrefix(FieldConfigRevision, v))
}

// ConfigRevisionHasSuffix applies the HasSuffix predicate on the "config_revision" field.
func ConfigRevisionHasSuffix(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldHasSuffix(FieldConfigRevision, v))
}

// ConfigRevisionEqualFold applies the EqualFold predicate on the "config_revision" field.
func ConfigRevisionEqualFold(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEqualFold(FieldConfigRevision, v))
}

// ConfigRevisionContainsFold applies the ContainsFold predicate on the "config_revision" field.
func ConfigRevisionContainsFold(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldContainsFold(FieldConfigRevision, v))
}

// PoolKeyEQ applies the EQ predicate on the "pool_key" field.
func PoolKeyEQ(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldPoolKey, v))
}

// PoolKeyNEQ applies the NEQ predicate on the "pool_key" field.
func PoolKeyNEQ(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNEQ(FieldPoolKey, v))
}

// PoolKeyIn applies the In predicate on the "pool_key" field.
func PoolKeyIn(vs ...string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldIn(FieldPoolKey, vs...))
}

// PoolKeyNotIn applies the NotIn predicate on the "pool_key" field.
func PoolKeyNotIn(vs ...string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNotIn(FieldPoolKey, vs...))
}

// PoolKeyGT applies the GT predicate on the "pool_key" field.
func PoolKeyGT(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGT(FieldPoolKey, v))
}

// PoolKeyGTE applies the GTE predicate on the "pool_key" field.
func PoolKeyGTE(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGTE(FieldPoolKey, v))
}

// PoolKeyLT applies the LT predicate on the "pool_key" field.
func PoolKeyLT(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLT(FieldPoolKey, v))
}

// PoolKeyLTE applies the LTE predicate on the "pool_key" field.
func PoolKeyLTE(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLTE(FieldPoolKey, v))
}

// PoolKeyContains applies the Contains predicate on the "pool_key" field.
func PoolKeyContains(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldContains(FieldPoolKey, v))
}

// PoolKeyHasPrefix applies the HasPrefix predicate on the "pool_key" field.
func PoolKeyHasPrefix(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldHasPrefix(FieldPoolKey, v))
}

// PoolKeyHasSuffix applies the HasSuffix predicate on the "pool_key" field.
func PoolKeyHasSuffix(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldHasSuffix(FieldPoolKey, v))
}

// PoolKeyEqualFold applies the EqualFold predicate on the "pool_key" field.
func PoolKeyEqualFold(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEqualFold(FieldPoolKey, v))
}

// PoolKeyContainsFold applies the ContainsFold predicate on the "pool_key" field.
func PoolKeyContainsFold(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldContainsFold(FieldPoolKey, v))
}

// RoleKeyEQ applies the EQ predicate on the "role_key" field.
func RoleKeyEQ(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldRoleKey, v))
}

// RoleKeyNEQ applies the NEQ predicate on the "role_key" field.
func RoleKeyNEQ(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNEQ(FieldRoleKey, v))
}

// RoleKeyIn applies the In predicate on the "role_key" field.
func RoleKeyIn(vs ...string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldIn(FieldRoleKey, vs...))
}

// RoleKeyNotIn applies the NotIn predicate on the "role_key" field.
func RoleKeyNotIn(vs ...string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNotIn(FieldRoleKey, vs...))
}

// RoleKeyGT applies the GT predicate on the "role_key" field.
func RoleKeyGT(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGT(FieldRoleKey, v))
}

// RoleKeyGTE applies the GTE predicate on the "role_key" field.
func RoleKeyGTE(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGTE(FieldRoleKey, v))
}

// RoleKeyLT applies the LT predicate on the "role_key" field.
func RoleKeyLT(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLT(FieldRoleKey, v))
}

// RoleKeyLTE applies the LTE predicate on the "role_key" field.
func RoleKeyLTE(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLTE(FieldRoleKey, v))
}

// RoleKeyContains applies the Contains predicate on the "role_key" field.
func RoleKeyContains(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldContains(FieldRoleKey, v))
}

// RoleKeyHasPrefix applies the HasPrefix predicate on the "role_key" field.
func RoleKeyHasPrefix(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldHasPrefix(FieldRoleKey, v))
}

// RoleKeyHasSuffix applies the HasSuffix predicate on the "role_key" field.
func RoleKeyHasSuffix(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldHasSuffix(FieldRoleKey, v))
}

// RoleKeyEqualFold applies the EqualFold predicate on the "role_key" field.
func RoleKeyEqualFold(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEqualFold(FieldRoleKey, v))
}

// RoleKeyContainsFold applies the ContainsFold predicate on the "role_key" field.
func RoleKeyContainsFold(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldContainsFold(FieldRoleKey, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLTE(FieldUserID, v))
}

// StrategyEQ applies the EQ predicate on the "strategy" field.
func StrategyEQ(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldStrategy, v))
}

// StrategyNEQ applies the NEQ predicate on the "strategy" field.
func StrategyNEQ(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNEQ(FieldStrategy, v))
}

// StrategyIn applies the In predicate on the "strategy" field.
func StrategyIn(vs ...string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldIn(FieldStrategy, vs...))
}

// StrategyNotIn applies the NotIn predicate on the "strategy" field.
func StrategyNotIn(vs ...string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNotIn(FieldStrategy, vs...))
}

// StrategyGT applies the GT predicate on the "strategy" field.
func StrategyGT(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGT(FieldStrategy, v))
}

// StrategyGTE applies the GTE predicate on the "strategy" field.
func StrategyGTE(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGTE(FieldStrategy, v))
}

// StrategyLT applies the LT predicate on the "strategy" field.
func StrategyLT(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLT(FieldStrategy, v))
}

// StrategyLTE applies the LTE predicate on the "strategy" field.
func StrategyLTE(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLTE(FieldStrategy, v))
}

// StrategyContains applies the Contains predicate on the "strategy" field.
func StrategyContains(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldContains(FieldStrategy, v))
}

// StrategyHasPrefix applies the HasPrefix predicate on the "strategy" field.
func StrategyHasPrefix(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldHasPrefix(FieldStrategy, v))
}

// StrategyHasSuffix applies the HasSuffix predicate on the "strategy" field.
func StrategyHasSuffix(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldHasSuffix(FieldStrategy, v))
}

// StrategyEqualFold applies the EqualFold predicate on the "strategy" field.
func StrategyEqualFold(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEqualFold(FieldStrategy, v))
}

// StrategyContainsFold applies the ContainsFold predicate on the "strategy" field.
func StrategyContainsFold(v string) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldContainsFold(FieldStrategy, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLTE(FieldPriority, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkPoolMembership) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkPoolMembership) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkPoolMembership) predicate.WorkPoolMembership {
	return predicate.WorkPoolMembership(sql.NotPredicates(p))
}
