// Code generated by ent, DO NOT EDIT.

package productsku

import (
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLTE(FieldID, id))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldProductID, v))
}

// SkuCode applies equality check predicate on the "sku_code" field. It's identical to SkuCodeEQ.
func SkuCode(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldSkuCode, v))
}

// SkuName applies equality check predicate on the "sku_name" field. It's identical to SkuNameEQ.
func SkuName(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldSkuName, v))
}

// Barcode applies equality check predicate on the "barcode" field. It's identical to BarcodeEQ.
func Barcode(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldBarcode, v))
}

// CustomerSku applies equality check predicate on the "customer_sku" field. It's identical to CustomerSkuEQ.
func CustomerSku(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldCustomerSku, v))
}

// Color applies equality check predicate on the "color" field. It's identical to ColorEQ.
func Color(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldColor, v))
}

// ColorNo applies equality check predicate on the "color_no" field. It's identical to ColorNoEQ.
func ColorNo(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldColorNo, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldSize, v))
}

// PackagingVersion applies equality check predicate on the "packaging_version" field. It's identical to PackagingVersionEQ.
func PackagingVersion(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldPackagingVersion, v))
}

// DefaultUnitID applies equality check predicate on the "default_unit_id" field. It's identical to DefaultUnitIDEQ.
func DefaultUnitID(v int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldDefaultUnitID, v))
}

// UnitNetWeightKg applies equality check predicate on the "unit_net_weight_kg" field. It's identical to UnitNetWeightKgEQ.
func UnitNetWeightKg(v decimal.Decimal) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldUnitNetWeightKg, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotIn(FieldProductID, vs...))
}

// SkuCodeEQ applies the EQ predicate on the "sku_code" field.
func SkuCodeEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldSkuCode, v))
}

// SkuCodeNEQ applies the NEQ predicate on the "sku_code" field.
func SkuCodeNEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldSkuCode, v))
}

// SkuCodeIn applies the In predicate on the "sku_code" field.
func SkuCodeIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIn(FieldSkuCode, vs...))
}

// SkuCodeNotIn applies the NotIn predicate on the "sku_code" field.
func SkuCodeNotIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotIn(FieldSkuCode, vs...))
}

// SkuCodeGT applies the GT predicate on the "sku_code" field.
func SkuCodeGT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGT(FieldSkuCode, v))
}

// SkuCodeGTE applies the GTE predicate on the "sku_code" field.
func SkuCodeGTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGTE(FieldSkuCode, v))
}

// SkuCodeLT applies the LT predicate on the "sku_code" field.
func SkuCodeLT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLT(FieldSkuCode, v))
}

// SkuCodeLTE applies the LTE predicate on the "sku_code" field.
func SkuCodeLTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLTE(FieldSkuCode, v))
}

// SkuCodeContains applies the Contains predicate on the "sku_code" field.
func SkuCodeContains(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContains(FieldSkuCode, v))
}

// SkuCodeHasPrefix applies the HasPrefix predicate on the "sku_code" field.
func SkuCodeHasPrefix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasPrefix(FieldSkuCode, v))
}

// SkuCodeHasSuffix applies the HasSuffix predicate on the "sku_code" field.
func SkuCodeHasSuffix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasSuffix(FieldSkuCode, v))
}

// SkuCodeEqualFold applies the EqualFold predicate on the "sku_code" field.
func SkuCodeEqualFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEqualFold(FieldSkuCode, v))
}

// SkuCodeContainsFold applies the ContainsFold predicate on the "sku_code" field.
func SkuCodeContainsFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContainsFold(FieldSkuCode, v))
}

// SkuNameEQ applies the EQ predicate on the "sku_name" field.
func SkuNameEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldSkuName, v))
}

// SkuNameNEQ applies the NEQ predicate on the "sku_name" field.
func SkuNameNEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldSkuName, v))
}

// SkuNameIn applies the In predicate on the "sku_name" field.
func SkuNameIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIn(FieldSkuName, vs...))
}

// SkuNameNotIn applies the NotIn predicate on the "sku_name" field.
func SkuNameNotIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotIn(FieldSkuName, vs...))
}

// SkuNameGT applies the GT predicate on the "sku_name" field.
func SkuNameGT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGT(FieldSkuName, v))
}

// SkuNameGTE applies the GTE predicate on the "sku_name" field.
func SkuNameGTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGTE(FieldSkuName, v))
}

// SkuNameLT applies the LT predicate on the "sku_name" field.
func SkuNameLT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLT(FieldSkuName, v))
}

// SkuNameLTE applies the LTE predicate on the "sku_name" field.
func SkuNameLTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLTE(FieldSkuName, v))
}

// SkuNameContains applies the Contains predicate on the "sku_name" field.
func SkuNameContains(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContains(FieldSkuName, v))
}

// SkuNameHasPrefix applies the HasPrefix predicate on the "sku_name" field.
func SkuNameHasPrefix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasPrefix(FieldSkuName, v))
}

// SkuNameHasSuffix applies the HasSuffix predicate on the "sku_name" field.
func SkuNameHasSuffix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasSuffix(FieldSkuName, v))
}

// SkuNameIsNil applies the IsNil predicate on the "sku_name" field.
func SkuNameIsNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIsNull(FieldSkuName))
}

// SkuNameNotNil applies the NotNil predicate on the "sku_name" field.
func SkuNameNotNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotNull(FieldSkuName))
}

// SkuNameEqualFold applies the EqualFold predicate on the "sku_name" field.
func SkuNameEqualFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEqualFold(FieldSkuName, v))
}

// SkuNameContainsFold applies the ContainsFold predicate on the "sku_name" field.
func SkuNameContainsFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContainsFold(FieldSkuName, v))
}

// BarcodeEQ applies the EQ predicate on the "barcode" field.
func BarcodeEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldBarcode, v))
}

// BarcodeNEQ applies the NEQ predicate on the "barcode" field.
func BarcodeNEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldBarcode, v))
}

// BarcodeIn applies the In predicate on the "barcode" field.
func BarcodeIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIn(FieldBarcode, vs...))
}

// BarcodeNotIn applies the NotIn predicate on the "barcode" field.
func BarcodeNotIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotIn(FieldBarcode, vs...))
}

// BarcodeGT applies the GT predicate on the "barcode" field.
func BarcodeGT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGT(FieldBarcode, v))
}

// BarcodeGTE applies the GTE predicate on the "barcode" field.
func BarcodeGTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGTE(FieldBarcode, v))
}

// BarcodeLT applies the LT predicate on the "barcode" field.
func BarcodeLT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLT(FieldBarcode, v))
}

// BarcodeLTE applies the LTE predicate on the "barcode" field.
func BarcodeLTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLTE(FieldBarcode, v))
}

// BarcodeContains applies the Contains predicate on the "barcode" field.
func BarcodeContains(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContains(FieldBarcode, v))
}

// BarcodeHasPrefix applies the HasPrefix predicate on the "barcode" field.
func BarcodeHasPrefix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasPrefix(FieldBarcode, v))
}

// BarcodeHasSuffix applies the HasSuffix predicate on the "barcode" field.
func BarcodeHasSuffix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasSuffix(FieldBarcode, v))
}

// BarcodeIsNil applies the IsNil predicate on the "barcode" field.
func BarcodeIsNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIsNull(FieldBarcode))
}

// BarcodeNotNil applies the NotNil predicate on the "barcode" field.
func BarcodeNotNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotNull(FieldBarcode))
}

// BarcodeEqualFold applies the EqualFold predicate on the "barcode" field.
func BarcodeEqualFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEqualFold(FieldBarcode, v))
}

// BarcodeContainsFold applies the ContainsFold predicate on the "barcode" field.
func BarcodeContainsFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContainsFold(FieldBarcode, v))
}

// CustomerSkuEQ applies the EQ predicate on the "customer_sku" field.
func CustomerSkuEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldCustomerSku, v))
}

// CustomerSkuNEQ applies the NEQ predicate on the "customer_sku" field.
func CustomerSkuNEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldCustomerSku, v))
}

// CustomerSkuIn applies the In predicate on the "customer_sku" field.
func CustomerSkuIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIn(FieldCustomerSku, vs...))
}

// CustomerSkuNotIn applies the NotIn predicate on the "customer_sku" field.
func CustomerSkuNotIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotIn(FieldCustomerSku, vs...))
}

// CustomerSkuGT applies the GT predicate on the "customer_sku" field.
func CustomerSkuGT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGT(FieldCustomerSku, v))
}

// CustomerSkuGTE applies the GTE predicate on the "customer_sku" field.
func CustomerSkuGTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGTE(FieldCustomerSku, v))
}

// CustomerSkuLT applies the LT predicate on the "customer_sku" field.
func CustomerSkuLT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLT(FieldCustomerSku, v))
}

// CustomerSkuLTE applies the LTE predicate on the "customer_sku" field.
func CustomerSkuLTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLTE(FieldCustomerSku, v))
}

// CustomerSkuContains applies the Contains predicate on the "customer_sku" field.
func CustomerSkuContains(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContains(FieldCustomerSku, v))
}

// CustomerSkuHasPrefix applies the HasPrefix predicate on the "customer_sku" field.
func CustomerSkuHasPrefix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasPrefix(FieldCustomerSku, v))
}

// CustomerSkuHasSuffix applies the HasSuffix predicate on the "customer_sku" field.
func CustomerSkuHasSuffix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasSuffix(FieldCustomerSku, v))
}

// CustomerSkuIsNil applies the IsNil predicate on the "customer_sku" field.
func CustomerSkuIsNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIsNull(FieldCustomerSku))
}

// CustomerSkuNotNil applies the NotNil predicate on the "customer_sku" field.
func CustomerSkuNotNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotNull(FieldCustomerSku))
}

// CustomerSkuEqualFold applies the EqualFold predicate on the "customer_sku" field.
func CustomerSkuEqualFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEqualFold(FieldCustomerSku, v))
}

// CustomerSkuContainsFold applies the ContainsFold predicate on the "customer_sku" field.
func CustomerSkuContainsFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContainsFold(FieldCustomerSku, v))
}

// ColorEQ applies the EQ predicate on the "color" field.
func ColorEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldColor, v))
}

// ColorNEQ applies the NEQ predicate on the "color" field.
func ColorNEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldColor, v))
}

// ColorIn applies the In predicate on the "color" field.
func ColorIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIn(FieldColor, vs...))
}

// ColorNotIn applies the NotIn predicate on the "color" field.
func ColorNotIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotIn(FieldColor, vs...))
}

// ColorGT applies the GT predicate on the "color" field.
func ColorGT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGT(FieldColor, v))
}

// ColorGTE applies the GTE predicate on the "color" field.
func ColorGTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGTE(FieldColor, v))
}

// ColorLT applies the LT predicate on the "color" field.
func ColorLT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLT(FieldColor, v))
}

// ColorLTE applies the LTE predicate on the "color" field.
func ColorLTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLTE(FieldColor, v))
}

// ColorContains applies the Contains predicate on the "color" field.
func ColorContains(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContains(FieldColor, v))
}

// ColorHasPrefix applies the HasPrefix predicate on the "color" field.
func ColorHasPrefix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasPrefix(FieldColor, v))
}

// ColorHasSuffix applies the HasSuffix predicate on the "color" field.
func ColorHasSuffix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasSuffix(FieldColor, v))
}

// ColorIsNil applies the IsNil predicate on the "color" field.
func ColorIsNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIsNull(FieldColor))
}

// ColorNotNil applies the NotNil predicate on the "color" field.
func ColorNotNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotNull(FieldColor))
}

// ColorEqualFold applies the EqualFold predicate on the "color" field.
func ColorEqualFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEqualFold(FieldColor, v))
}

// ColorContainsFold applies the ContainsFold predicate on the "color" field.
func ColorContainsFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContainsFold(FieldColor, v))
}

// ColorNoEQ applies the EQ predicate on the "color_no" field.
func ColorNoEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldColorNo, v))
}

// ColorNoNEQ applies the NEQ predicate on the "color_no" field.
func ColorNoNEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldColorNo, v))
}

// ColorNoIn applies the In predicate on the "color_no" field.
func ColorNoIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIn(FieldColorNo, vs...))
}

// ColorNoNotIn applies the NotIn predicate on the "color_no" field.
func ColorNoNotIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotIn(FieldColorNo, vs...))
}

// ColorNoGT applies the GT predicate on the "color_no" field.
func ColorNoGT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGT(FieldColorNo, v))
}

// ColorNoGTE applies the GTE predicate on the "color_no" field.
func ColorNoGTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGTE(FieldColorNo, v))
}

// ColorNoLT applies the LT predicate on the "color_no" field.
func ColorNoLT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLT(FieldColorNo, v))
}

// ColorNoLTE applies the LTE predicate on the "color_no" field.
func ColorNoLTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLTE(FieldColorNo, v))
}

// ColorNoContains applies the Contains predicate on the "color_no" field.
func ColorNoContains(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContains(FieldColorNo, v))
}

// ColorNoHasPrefix applies the HasPrefix predicate on the "color_no" field.
func ColorNoHasPrefix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasPrefix(FieldColorNo, v))
}

// ColorNoHasSuffix applies the HasSuffix predicate on the "color_no" field.
func ColorNoHasSuffix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasSuffix(FieldColorNo, v))
}

// ColorNoIsNil applies the IsNil predicate on the "color_no" field.
func ColorNoIsNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIsNull(FieldColorNo))
}

// ColorNoNotNil applies the NotNil predicate on the "color_no" field.
func ColorNoNotNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotNull(FieldColorNo))
}

// ColorNoEqualFold applies the EqualFold predicate on the "color_no" field.
func ColorNoEqualFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEqualFold(FieldColorNo, v))
}

// ColorNoContainsFold applies the ContainsFold predicate on the "color_no" field.
func ColorNoContainsFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContainsFold(FieldColorNo, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLTE(FieldSize, v))
}

// SizeContains applies the Contains predicate on the "size" field.
func SizeContains(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContains(FieldSize, v))
}

// SizeHasPrefix applies the HasPrefix predicate on the "size" field.
func SizeHasPrefix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasPrefix(FieldSize, v))
}

// SizeHasSuffix applies the HasSuffix predicate on the "size" field.
func SizeHasSuffix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasSuffix(FieldSize, v))
}

// SizeIsNil applies the IsNil predicate on the "size" field.
func SizeIsNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIsNull(FieldSize))
}

// SizeNotNil applies the NotNil predicate on the "size" field.
func SizeNotNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotNull(FieldSize))
}

// SizeEqualFold applies the EqualFold predicate on the "size" field.
func SizeEqualFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEqualFold(FieldSize, v))
}

// SizeContainsFold applies the ContainsFold predicate on the "size" field.
func SizeContainsFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContainsFold(FieldSize, v))
}

// PackagingVersionEQ applies the EQ predicate on the "packaging_version" field.
func PackagingVersionEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldPackagingVersion, v))
}

// PackagingVersionNEQ applies the NEQ predicate on the "packaging_version" field.
func PackagingVersionNEQ(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldPackagingVersion, v))
}

// PackagingVersionIn applies the In predicate on the "packaging_version" field.
func PackagingVersionIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIn(FieldPackagingVersion, vs...))
}

// PackagingVersionNotIn applies the NotIn predicate on the "packaging_version" field.
func PackagingVersionNotIn(vs ...string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotIn(FieldPackagingVersion, vs...))
}

// PackagingVersionGT applies the GT predicate on the "packaging_version" field.
func PackagingVersionGT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGT(FieldPackagingVersion, v))
}

// PackagingVersionGTE applies the GTE predicate on the "packaging_version" field.
func PackagingVersionGTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGTE(FieldPackagingVersion, v))
}

// PackagingVersionLT applies the LT predicate on the "packaging_version" field.
func PackagingVersionLT(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLT(FieldPackagingVersion, v))
}

// PackagingVersionLTE applies the LTE predicate on the "packaging_version" field.
func PackagingVersionLTE(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLTE(FieldPackagingVersion, v))
}

// PackagingVersionContains applies the Contains predicate on the "packaging_version" field.
func PackagingVersionContains(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContains(FieldPackagingVersion, v))
}

// PackagingVersionHasPrefix applies the HasPrefix predicate on the "packaging_version" field.
func PackagingVersionHasPrefix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasPrefix(FieldPackagingVersion, v))
}

// PackagingVersionHasSuffix applies the HasSuffix predicate on the "packaging_version" field.
func PackagingVersionHasSuffix(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldHasSuffix(FieldPackagingVersion, v))
}

// PackagingVersionIsNil applies the IsNil predicate on the "packaging_version" field.
func PackagingVersionIsNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIsNull(FieldPackagingVersion))
}

// PackagingVersionNotNil applies the NotNil predicate on the "packaging_version" field.
func PackagingVersionNotNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotNull(FieldPackagingVersion))
}

// PackagingVersionEqualFold applies the EqualFold predicate on the "packaging_version" field.
func PackagingVersionEqualFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEqualFold(FieldPackagingVersion, v))
}

// PackagingVersionContainsFold applies the ContainsFold predicate on the "packaging_version" field.
func PackagingVersionContainsFold(v string) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldContainsFold(FieldPackagingVersion, v))
}

// DefaultUnitIDEQ applies the EQ predicate on the "default_unit_id" field.
func DefaultUnitIDEQ(v int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldDefaultUnitID, v))
}

// DefaultUnitIDNEQ applies the NEQ predicate on the "default_unit_id" field.
func DefaultUnitIDNEQ(v int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldDefaultUnitID, v))
}

// DefaultUnitIDIn applies the In predicate on the "default_unit_id" field.
func DefaultUnitIDIn(vs ...int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIn(FieldDefaultUnitID, vs...))
}

// DefaultUnitIDNotIn applies the NotIn predicate on the "default_unit_id" field.
func DefaultUnitIDNotIn(vs ...int) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotIn(FieldDefaultUnitID, vs...))
}

// DefaultUnitIDIsNil applies the IsNil predicate on the "default_unit_id" field.
func DefaultUnitIDIsNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIsNull(FieldDefaultUnitID))
}

// DefaultUnitIDNotNil applies the NotNil predicate on the "default_unit_id" field.
func DefaultUnitIDNotNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotNull(FieldDefaultUnitID))
}

// UnitNetWeightKgEQ applies the EQ predicate on the "unit_net_weight_kg" field.
func UnitNetWeightKgEQ(v decimal.Decimal) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldUnitNetWeightKg, v))
}

// UnitNetWeightKgNEQ applies the NEQ predicate on the "unit_net_weight_kg" field.
func UnitNetWeightKgNEQ(v decimal.Decimal) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldUnitNetWeightKg, v))
}

// UnitNetWeightKgIn applies the In predicate on the "unit_net_weight_kg" field.
func UnitNetWeightKgIn(vs ...decimal.Decimal) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIn(FieldUnitNetWeightKg, vs...))
}

// UnitNetWeightKgNotIn applies the NotIn predicate on the "unit_net_weight_kg" field.
func UnitNetWeightKgNotIn(vs ...decimal.Decimal) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotIn(FieldUnitNetWeightKg, vs...))
}

// UnitNetWeightKgGT applies the GT predicate on the "unit_net_weight_kg" field.
func UnitNetWeightKgGT(v decimal.Decimal) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGT(FieldUnitNetWeightKg, v))
}

// UnitNetWeightKgGTE applies the GTE predicate on the "unit_net_weight_kg" field.
func UnitNetWeightKgGTE(v decimal.Decimal) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGTE(FieldUnitNetWeightKg, v))
}

// UnitNetWeightKgLT applies the LT predicate on the "unit_net_weight_kg" field.
func UnitNetWeightKgLT(v decimal.Decimal) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLT(FieldUnitNetWeightKg, v))
}

// UnitNetWeightKgLTE applies the LTE predicate on the "unit_net_weight_kg" field.
func UnitNetWeightKgLTE(v decimal.Decimal) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLTE(FieldUnitNetWeightKg, v))
}

// UnitNetWeightKgIsNil applies the IsNil predicate on the "unit_net_weight_kg" field.
func UnitNetWeightKgIsNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIsNull(FieldUnitNetWeightKg))
}

// UnitNetWeightKgNotNil applies the NotNil predicate on the "unit_net_weight_kg" field.
func UnitNetWeightKgNotNil() predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotNull(FieldUnitNetWeightKg))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProductSKU {
	return predicate.ProductSKU(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.Product) predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := newProductStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDefaultUnit applies the HasEdge predicate on the "default_unit" edge.
func HasDefaultUnit() predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DefaultUnitTable, DefaultUnitColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDefaultUnitWith applies the HasEdge predicate on the "default_unit" edge with a given conditions (other predicates).
func HasDefaultUnitWith(preds ...predicate.Unit) predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := newDefaultUnitStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSalesOrderItems applies the HasEdge predicate on the "sales_order_items" edge.
func HasSalesOrderItems() predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SalesOrderItemsTable, SalesOrderItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSalesOrderItemsWith applies the HasEdge predicate on the "sales_order_items" edge with a given conditions (other predicates).
func HasSalesOrderItemsWith(preds ...predicate.SalesOrderItem) predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := newSalesOrderItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInventoryLots applies the HasEdge predicate on the "inventory_lots" edge.
func HasInventoryLots() predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InventoryLotsTable, InventoryLotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInventoryLotsWith applies the HasEdge predicate on the "inventory_lots" edge with a given conditions (other predicates).
func HasInventoryLotsWith(preds ...predicate.InventoryLot) predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := newInventoryLotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInventoryTxns applies the HasEdge predicate on the "inventory_txns" edge.
func HasInventoryTxns() predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InventoryTxnsTable, InventoryTxnsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInventoryTxnsWith applies the HasEdge predicate on the "inventory_txns" edge with a given conditions (other predicates).
func HasInventoryTxnsWith(preds ...predicate.InventoryTxn) predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := newInventoryTxnsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInventoryBalances applies the HasEdge predicate on the "inventory_balances" edge.
func HasInventoryBalances() predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InventoryBalancesTable, InventoryBalancesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInventoryBalancesWith applies the HasEdge predicate on the "inventory_balances" edge with a given conditions (other predicates).
func HasInventoryBalancesWith(preds ...predicate.InventoryBalance) predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := newInventoryBalancesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProductionFacts applies the HasEdge predicate on the "production_facts" edge.
func HasProductionFacts() predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProductionFactsTable, ProductionFactsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductionFactsWith applies the HasEdge predicate on the "production_facts" edge with a given conditions (other predicates).
func HasProductionFactsWith(preds ...predicate.ProductionFact) predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := newProductionFactsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOutsourcingFacts applies the HasEdge predicate on the "outsourcing_facts" edge.
func HasOutsourcingFacts() predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OutsourcingFactsTable, OutsourcingFactsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOutsourcingFactsWith applies the HasEdge predicate on the "outsourcing_facts" edge with a given conditions (other predicates).
func HasOutsourcingFactsWith(preds ...predicate.OutsourcingFact) predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := newOutsourcingFactsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasShipmentItems applies the HasEdge predicate on the "shipment_items" edge.
func HasShipmentItems() predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ShipmentItemsTable, ShipmentItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShipmentItemsWith applies the HasEdge predicate on the "shipment_items" edge with a given conditions (other predicates).
func HasShipmentItemsWith(preds ...predicate.ShipmentItem) predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := newShipmentItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStockReservations applies the HasEdge predicate on the "stock_reservations" edge.
func HasStockReservations() predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StockReservationsTable, StockReservationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStockReservationsWith applies the HasEdge predicate on the "stock_reservations" edge with a given conditions (other predicates).
func HasStockReservationsWith(preds ...predicate.StockReservation) predicate.ProductSKU {
	return predicate.ProductSKU(func(s *sql.Selector) {
		step := newStockReservationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProductSKU) predicate.ProductSKU {
	return predicate.ProductSKU(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProductSKU) predicate.ProductSKU {
	return predicate.ProductSKU(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProductSKU) predicate.ProductSKU {
	return predicate.ProductSKU(sql.NotPredicates(p))
}
