export const privateDeploymentPackageTemplate = Object.freeze({
  templateKey: "private-customer-package",
  label: "多客户私有化复制包模板",
  reviewMilestone: "private-deployment-package-candidate",
  status: "template_candidate",
  runtimeEnabled: false,
  simulatedCustomerKey: "SIM-PRIVATE-DEPLOYMENT",
  scope:
    "Prepare private customer package boundaries for docs, config and deployment reuse. This template is not a runtime loader and must not create a real customer package by itself.",
  sourcePolicy: Object.freeze({
    industryTemplateKey: "plush",
    industryTemplateMustRemainCandidate: true,
    singleCustomerPackageMayOnlyCreateCustomerConfig: true,
    requiresCustomerKeyReview: true,
    requiresHumanImportApprovalForRealData: true,
    simulatedCustomerKeyMustNotBecomeDirectory: true,
  }),
  boundaries: Object.freeze({
    createsTenant: false,
    startsSaas: false,
    changesSchema: false,
    changesMigration: false,
    changesBackendRbac: false,
    changesWorkflowFactRules: false,
    changesRuntimeMenuLoader: false,
    forksCodebase: false,
    executesRealImport: false,
    writesBusinessRecords: false,
    writesFacts: false,
    buildsOnTargetServer: false,
  }),
  requiredPackageRoots: Object.freeze([
    "docs/customers/<customer-key>/",
    "config/customers/<customer-key>/",
    "deployments/<customer-key>/",
  ]),
  requiredCustomerDocs: Object.freeze([
    "README.md",
    "客户配置草案.md",
    "差异登记.md",
    "导入来源清单.md",
    "导入字段分类.md",
    "导入待确认队列.md",
    "导入风险登记.md",
    "试用账号角色菜单核对清单.md",
    "试用环境执行手册.md",
  ]),
  requiredCustomerConfigFiles: Object.freeze([
    "README.md",
    "menuConfig.mjs",
    "fieldNumberingConfig.mjs",
  ]),
  requiredDeploymentDocs: Object.freeze([
    "README.md",
    "env/.env.example",
    "env/secrets.required.md",
    "compose/docker-compose.example.yml",
    "runbooks/01-first-deploy.md",
    "runbooks/02-upgrade.md",
    "runbooks/03-rollback.md",
    "runbooks/04-backup-restore.md",
    "runbooks/05-migration.md",
    "runbooks/06-import-apply.md",
    "runbooks/07-incident-response.md",
    "runbooks/08-daily-ops.md",
    "checklists/pre-deploy-checklist.md",
    "checklists/post-deploy-checklist.md",
    "checklists/smoke-test-checklist.md",
    "checklists/security-checklist.md",
    "checklists/backup-restore-checklist.md",
    "checklists/upgrade-checklist.md",
    "checklists/rollback-checklist.md",
    "evidence/README.md",
    "evidence/releases/release-evidence-template.md",
    "evidence/migrations/migration-evidence-template.md",
    "evidence/backups/backup-evidence-template.md",
  ]),
  reusableSources: Object.freeze([
    {
      key: "industry-template",
      path: "config/industry-templates/plush/templateConfig.mjs",
      boundary: "candidate only; not runtime default",
    },
    {
      key: "prod-compose",
      path: "server/deploy/compose/prod",
      boundary: "single deploy truth; customer package may document overrides but must not create a second deploy path",
    },
    {
      key: "import-dry-run-tools",
      path: "scripts/import",
      boundary: "dry-run and evidence only unless a separate data governance task approves real import",
    },
    {
      key: "simulation-tools",
      path: "scripts/qa/trial-*.mjs scripts/qa/operational-fact-*.mjs scripts/qa/mobile-workflow-*.mjs",
      boundary: "simulation only; all generated data must use explicit SIM prefixes",
    },
  ]),
  simulatedAcceptanceChecks: Object.freeze([
    "customer key is stable and reviewed",
    "docs/config/deployments package roots are planned",
    "real import remains blocked",
    "schema and migration are unchanged",
    "core code is not forked",
    "target server only loads built images",
    "pre-migration backup evidence is required before future migration apply",
    "post-deploy smoke covers health, ready, desktop route, RBAC and simulated closure where applicable",
  ]),
});
