export const privateDeploymentPackageTemplate = Object.freeze({
  templateKey: "private-customer-package",
  label: "多客户私有化复制包模板",
  phase: "Phase 11",
  status: "template_candidate",
  runtimeEnabled: false,
  simulatedCustomerKey: "SIM-PRIVATE-PHASE11",
  scope:
    "Prepare private customer package boundaries for docs, config and deployment reuse. This template is not a runtime loader and must not create a real customer package by itself.",
  sourcePolicy: Object.freeze({
    industryTemplateKey: "plush",
    industryTemplateMustRemainCandidate: true,
    singleCustomerPackageMayOnlyCreateCustomerConfig: true,
    requiresCustomerKeyReview: true,
    requiresHumanImportApprovalForRealData: true,
    simulatedCustomerKeyMustNotBecomeDirectory: true,
  }),
  boundaries: Object.freeze({
    createsTenant: false,
    startsSaas: false,
    changesSchema: false,
    changesMigration: false,
    changesBackendRbac: false,
    changesWorkflowFactRules: false,
    changesRuntimeMenuLoader: false,
    forksCodebase: false,
    executesRealImport: false,
    writesBusinessRecords: false,
    writesFacts: false,
    buildsOnTargetServer: false,
  }),
  requiredPackageRoots: Object.freeze([
    "docs/customers/<customer-key>/",
    "config/customers/<customer-key>/",
    "deployments/<customer-key>/",
  ]),
  requiredCustomerDocs: Object.freeze([
    "README.md",
    "customer-config-draft.md",
    "delta-register.md",
    "import-source-inventory.md",
    "import-field-classification.md",
    "import-dry-run-plan.md",
    "import-unresolved-queue.md",
    "import-risk-register.md",
    "trial-account-role-menu-checklist.md",
    "trial-environment-runbook.md",
  ]),
  requiredCustomerConfigFiles: Object.freeze([
    "README.md",
    "menuConfig.mjs",
    "fieldNumberingConfig.mjs",
  ]),
  requiredDeploymentDocs: Object.freeze([
    "README.md",
    "env-checklist.md",
    "release-runbook.md",
    "backup-restore.md",
    "acceptance-checklist.md",
  ]),
  reusableSources: Object.freeze([
    {
      key: "industry-template",
      path: "config/industry-templates/plush/templateConfig.mjs",
      boundary: "candidate only; not runtime default",
    },
    {
      key: "prod-compose",
      path: "server/deploy/compose/prod",
      boundary: "single deploy truth; customer package may document overrides but must not create a second deploy path",
    },
    {
      key: "import-dry-run-tools",
      path: "scripts/import",
      boundary: "dry-run and evidence only unless a separate data governance task approves real import",
    },
    {
      key: "phase-simulation-tools",
      path: "scripts/qa/phase7-*.mjs scripts/qa/phase8-*.mjs scripts/qa/phase9-*.mjs",
      boundary: "simulation only; all generated data must use explicit SIM prefixes",
    },
  ]),
  simulatedAcceptanceChecks: Object.freeze([
    "customer key is stable and reviewed",
    "docs/config/deployments package roots are planned",
    "real import remains blocked",
    "schema and migration are unchanged",
    "core code is not forked",
    "target server only loads built images",
    "pre-migration backup evidence is required before future migration apply",
    "post-deploy smoke covers health, ready, desktop route, RBAC and simulated closure where applicable",
  ]),
});

