export const privateDeploymentPackageTemplate = Object.freeze({
  templateKey: "private-customer-package",
  label: "多客户私有化复制包模板",
  reviewMilestone: "private-deployment-package-candidate",
  status: "template_candidate",
  runtimeEnabled: false,
  simulatedCustomerKey: "SIM-PRIVATE-DEPLOYMENT",
  scope:
    "Prepare private customer package boundaries for docs, config and deployment reuse. This template is not a runtime loader and must not create a real customer package by itself.",
  sourcePolicy: Object.freeze({
    industryTemplateKey: "plush",
    industryTemplateMustRemainCandidate: true,
    singleCustomerPackageMayOnlyCreateCustomerConfig: true,
    requiresCustomerKeyReview: true,
    requiresHumanImportApprovalForRealData: true,
    simulatedCustomerKeyMustNotBecomeDirectory: true,
  }),
  boundaries: Object.freeze({
    createsTenant: false,
    startsSaas: false,
    changesSchema: false,
    changesMigration: false,
    changesBackendRbac: false,
    changesWorkflowFactRules: false,
    changesRuntimeMenuLoader: false,
    forksCodebase: false,
    executesRealImport: false,
    writesBusinessRecords: false,
    writesFacts: false,
    buildsOnTargetServer: false,
  }),
  requiredPackageRoots: Object.freeze([
    "docs/customers/<customer-key>/",
    "config/customers/<customer-key>/",
    "deployments/<customer-key>/",
  ]),
  requiredCustomerDocs: Object.freeze([
    "README.md",
    "差异与边界.md",
    "实施测试部署验收.md",
  ]),
  requiredCustomerConfigFiles: Object.freeze([
    "README.md",
    "customerPackage.mjs",
    "customer-config.example.js",
  ]),
  requiredDeploymentDocs: Object.freeze([
    "README.md",
    "reference-customer.env.example",
  ]),
  reusableSources: Object.freeze([
    {
      key: "industry-template",
      path: "config/industry-templates/plush/templateConfig.mjs",
      boundary: "candidate only; not runtime default",
    },
    {
      key: "prod-compose",
      path: "server/deploy/compose/prod",
      boundary: "single deploy truth; customer package may document overrides but must not create a second deploy path",
    },
    {
      key: "import-dry-run-tools",
      path: "scripts/import",
      boundary: "dry-run and evidence only unless a separate data governance task approves real import",
    },
    {
      key: "simulation-tools",
      path: "scripts/qa/trial-*.mjs scripts/qa/operational-fact-*.mjs scripts/qa/mobile-workflow-*.mjs",
      boundary: "simulation only; all generated data must use explicit SIM prefixes",
    },
  ]),
  boundaryReviewChecks: Object.freeze([
    "customer key is stable and reviewed",
    "docs, config and deployment responsibilities stay separated",
    "real import remains blocked",
    "schema and migration are unchanged",
    "core code is not forked",
    "target server only loads built images",
    "pre-migration backup evidence is required before future migration apply",
    "target-environment smoke and customer sign-off remain external acceptance evidence",
  ]),
});
