// Code generated by ent, DO NOT EDIT.

package sourceorderlifecycleevent

import (
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLTE(FieldID, id))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldSourceType, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldSourceID, v))
}

// SourceVersion applies equality check predicate on the "source_version" field. It's identical to SourceVersionEQ.
func SourceVersion(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldSourceVersion, v))
}

// ActionKey applies equality check predicate on the "action_key" field. It's identical to ActionKeyEQ.
func ActionKey(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldActionKey, v))
}

// FromStatus applies equality check predicate on the "from_status" field. It's identical to FromStatusEQ.
func FromStatus(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldFromStatus, v))
}

// ToStatus applies equality check predicate on the "to_status" field. It's identical to ToStatusEQ.
func ToStatus(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldToStatus, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IntentHash applies equality check predicate on the "intent_hash" field. It's identical to IntentHashEQ.
func IntentHash(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldIntentHash, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldReason, v))
}

// CloseMode applies equality check predicate on the "close_mode" field. It's identical to CloseModeEQ.
func CloseMode(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldCloseMode, v))
}

// ResultContract applies equality check predicate on the "result_contract" field. It's identical to ResultContractEQ.
func ResultContract(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldResultContract, v))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldActorID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLTE(FieldSourceID, v))
}

// SourceVersionEQ applies the EQ predicate on the "source_version" field.
func SourceVersionEQ(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldSourceVersion, v))
}

// SourceVersionNEQ applies the NEQ predicate on the "source_version" field.
func SourceVersionNEQ(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNEQ(FieldSourceVersion, v))
}

// SourceVersionIn applies the In predicate on the "source_version" field.
func SourceVersionIn(vs ...int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIn(FieldSourceVersion, vs...))
}

// SourceVersionNotIn applies the NotIn predicate on the "source_version" field.
func SourceVersionNotIn(vs ...int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotIn(FieldSourceVersion, vs...))
}

// SourceVersionGT applies the GT predicate on the "source_version" field.
func SourceVersionGT(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGT(FieldSourceVersion, v))
}

// SourceVersionGTE applies the GTE predicate on the "source_version" field.
func SourceVersionGTE(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGTE(FieldSourceVersion, v))
}

// SourceVersionLT applies the LT predicate on the "source_version" field.
func SourceVersionLT(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLT(FieldSourceVersion, v))
}

// SourceVersionLTE applies the LTE predicate on the "source_version" field.
func SourceVersionLTE(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLTE(FieldSourceVersion, v))
}

// ActionKeyEQ applies the EQ predicate on the "action_key" field.
func ActionKeyEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldActionKey, v))
}

// ActionKeyNEQ applies the NEQ predicate on the "action_key" field.
func ActionKeyNEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNEQ(FieldActionKey, v))
}

// ActionKeyIn applies the In predicate on the "action_key" field.
func ActionKeyIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIn(FieldActionKey, vs...))
}

// ActionKeyNotIn applies the NotIn predicate on the "action_key" field.
func ActionKeyNotIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotIn(FieldActionKey, vs...))
}

// ActionKeyGT applies the GT predicate on the "action_key" field.
func ActionKeyGT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGT(FieldActionKey, v))
}

// ActionKeyGTE applies the GTE predicate on the "action_key" field.
func ActionKeyGTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGTE(FieldActionKey, v))
}

// ActionKeyLT applies the LT predicate on the "action_key" field.
func ActionKeyLT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLT(FieldActionKey, v))
}

// ActionKeyLTE applies the LTE predicate on the "action_key" field.
func ActionKeyLTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLTE(FieldActionKey, v))
}

// ActionKeyContains applies the Contains predicate on the "action_key" field.
func ActionKeyContains(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContains(FieldActionKey, v))
}

// ActionKeyHasPrefix applies the HasPrefix predicate on the "action_key" field.
func ActionKeyHasPrefix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasPrefix(FieldActionKey, v))
}

// ActionKeyHasSuffix applies the HasSuffix predicate on the "action_key" field.
func ActionKeyHasSuffix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasSuffix(FieldActionKey, v))
}

// ActionKeyEqualFold applies the EqualFold predicate on the "action_key" field.
func ActionKeyEqualFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEqualFold(FieldActionKey, v))
}

// ActionKeyContainsFold applies the ContainsFold predicate on the "action_key" field.
func ActionKeyContainsFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContainsFold(FieldActionKey, v))
}

// FromStatusEQ applies the EQ predicate on the "from_status" field.
func FromStatusEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldFromStatus, v))
}

// FromStatusNEQ applies the NEQ predicate on the "from_status" field.
func FromStatusNEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNEQ(FieldFromStatus, v))
}

// FromStatusIn applies the In predicate on the "from_status" field.
func FromStatusIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIn(FieldFromStatus, vs...))
}

// FromStatusNotIn applies the NotIn predicate on the "from_status" field.
func FromStatusNotIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotIn(FieldFromStatus, vs...))
}

// FromStatusGT applies the GT predicate on the "from_status" field.
func FromStatusGT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGT(FieldFromStatus, v))
}

// FromStatusGTE applies the GTE predicate on the "from_status" field.
func FromStatusGTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGTE(FieldFromStatus, v))
}

// FromStatusLT applies the LT predicate on the "from_status" field.
func FromStatusLT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLT(FieldFromStatus, v))
}

// FromStatusLTE applies the LTE predicate on the "from_status" field.
func FromStatusLTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLTE(FieldFromStatus, v))
}

// FromStatusContains applies the Contains predicate on the "from_status" field.
func FromStatusContains(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContains(FieldFromStatus, v))
}

// FromStatusHasPrefix applies the HasPrefix predicate on the "from_status" field.
func FromStatusHasPrefix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasPrefix(FieldFromStatus, v))
}

// FromStatusHasSuffix applies the HasSuffix predicate on the "from_status" field.
func FromStatusHasSuffix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasSuffix(FieldFromStatus, v))
}

// FromStatusEqualFold applies the EqualFold predicate on the "from_status" field.
func FromStatusEqualFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEqualFold(FieldFromStatus, v))
}

// FromStatusContainsFold applies the ContainsFold predicate on the "from_status" field.
func FromStatusContainsFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContainsFold(FieldFromStatus, v))
}

// ToStatusEQ applies the EQ predicate on the "to_status" field.
func ToStatusEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldToStatus, v))
}

// ToStatusNEQ applies the NEQ predicate on the "to_status" field.
func ToStatusNEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNEQ(FieldToStatus, v))
}

// ToStatusIn applies the In predicate on the "to_status" field.
func ToStatusIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIn(FieldToStatus, vs...))
}

// ToStatusNotIn applies the NotIn predicate on the "to_status" field.
func ToStatusNotIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotIn(FieldToStatus, vs...))
}

// ToStatusGT applies the GT predicate on the "to_status" field.
func ToStatusGT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGT(FieldToStatus, v))
}

// ToStatusGTE applies the GTE predicate on the "to_status" field.
func ToStatusGTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGTE(FieldToStatus, v))
}

// ToStatusLT applies the LT predicate on the "to_status" field.
func ToStatusLT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLT(FieldToStatus, v))
}

// ToStatusLTE applies the LTE predicate on the "to_status" field.
func ToStatusLTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLTE(FieldToStatus, v))
}

// ToStatusContains applies the Contains predicate on the "to_status" field.
func ToStatusContains(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContains(FieldToStatus, v))
}

// ToStatusHasPrefix applies the HasPrefix predicate on the "to_status" field.
func ToStatusHasPrefix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasPrefix(FieldToStatus, v))
}

// ToStatusHasSuffix applies the HasSuffix predicate on the "to_status" field.
func ToStatusHasSuffix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasSuffix(FieldToStatus, v))
}

// ToStatusEqualFold applies the EqualFold predicate on the "to_status" field.
func ToStatusEqualFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEqualFold(FieldToStatus, v))
}

// ToStatusContainsFold applies the ContainsFold predicate on the "to_status" field.
func ToStatusContainsFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContainsFold(FieldToStatus, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// IntentHashEQ applies the EQ predicate on the "intent_hash" field.
func IntentHashEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldIntentHash, v))
}

// IntentHashNEQ applies the NEQ predicate on the "intent_hash" field.
func IntentHashNEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNEQ(FieldIntentHash, v))
}

// IntentHashIn applies the In predicate on the "intent_hash" field.
func IntentHashIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIn(FieldIntentHash, vs...))
}

// IntentHashNotIn applies the NotIn predicate on the "intent_hash" field.
func IntentHashNotIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotIn(FieldIntentHash, vs...))
}

// IntentHashGT applies the GT predicate on the "intent_hash" field.
func IntentHashGT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGT(FieldIntentHash, v))
}

// IntentHashGTE applies the GTE predicate on the "intent_hash" field.
func IntentHashGTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGTE(FieldIntentHash, v))
}

// IntentHashLT applies the LT predicate on the "intent_hash" field.
func IntentHashLT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLT(FieldIntentHash, v))
}

// IntentHashLTE applies the LTE predicate on the "intent_hash" field.
func IntentHashLTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLTE(FieldIntentHash, v))
}

// IntentHashContains applies the Contains predicate on the "intent_hash" field.
func IntentHashContains(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContains(FieldIntentHash, v))
}

// IntentHashHasPrefix applies the HasPrefix predicate on the "intent_hash" field.
func IntentHashHasPrefix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasPrefix(FieldIntentHash, v))
}

// IntentHashHasSuffix applies the HasSuffix predicate on the "intent_hash" field.
func IntentHashHasSuffix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasSuffix(FieldIntentHash, v))
}

// IntentHashEqualFold applies the EqualFold predicate on the "intent_hash" field.
func IntentHashEqualFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEqualFold(FieldIntentHash, v))
}

// IntentHashContainsFold applies the ContainsFold predicate on the "intent_hash" field.
func IntentHashContainsFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContainsFold(FieldIntentHash, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContainsFold(FieldReason, v))
}

// CloseModeEQ applies the EQ predicate on the "close_mode" field.
func CloseModeEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldCloseMode, v))
}

// CloseModeNEQ applies the NEQ predicate on the "close_mode" field.
func CloseModeNEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNEQ(FieldCloseMode, v))
}

// CloseModeIn applies the In predicate on the "close_mode" field.
func CloseModeIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIn(FieldCloseMode, vs...))
}

// CloseModeNotIn applies the NotIn predicate on the "close_mode" field.
func CloseModeNotIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotIn(FieldCloseMode, vs...))
}

// CloseModeGT applies the GT predicate on the "close_mode" field.
func CloseModeGT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGT(FieldCloseMode, v))
}

// CloseModeGTE applies the GTE predicate on the "close_mode" field.
func CloseModeGTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGTE(FieldCloseMode, v))
}

// CloseModeLT applies the LT predicate on the "close_mode" field.
func CloseModeLT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLT(FieldCloseMode, v))
}

// CloseModeLTE applies the LTE predicate on the "close_mode" field.
func CloseModeLTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLTE(FieldCloseMode, v))
}

// CloseModeContains applies the Contains predicate on the "close_mode" field.
func CloseModeContains(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContains(FieldCloseMode, v))
}

// CloseModeHasPrefix applies the HasPrefix predicate on the "close_mode" field.
func CloseModeHasPrefix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasPrefix(FieldCloseMode, v))
}

// CloseModeHasSuffix applies the HasSuffix predicate on the "close_mode" field.
func CloseModeHasSuffix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasSuffix(FieldCloseMode, v))
}

// CloseModeIsNil applies the IsNil predicate on the "close_mode" field.
func CloseModeIsNil() predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIsNull(FieldCloseMode))
}

// CloseModeNotNil applies the NotNil predicate on the "close_mode" field.
func CloseModeNotNil() predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotNull(FieldCloseMode))
}

// CloseModeEqualFold applies the EqualFold predicate on the "close_mode" field.
func CloseModeEqualFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEqualFold(FieldCloseMode, v))
}

// CloseModeContainsFold applies the ContainsFold predicate on the "close_mode" field.
func CloseModeContainsFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContainsFold(FieldCloseMode, v))
}

// ResultContractEQ applies the EQ predicate on the "result_contract" field.
func ResultContractEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldResultContract, v))
}

// ResultContractNEQ applies the NEQ predicate on the "result_contract" field.
func ResultContractNEQ(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNEQ(FieldResultContract, v))
}

// ResultContractIn applies the In predicate on the "result_contract" field.
func ResultContractIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIn(FieldResultContract, vs...))
}

// ResultContractNotIn applies the NotIn predicate on the "result_contract" field.
func ResultContractNotIn(vs ...string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotIn(FieldResultContract, vs...))
}

// ResultContractGT applies the GT predicate on the "result_contract" field.
func ResultContractGT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGT(FieldResultContract, v))
}

// ResultContractGTE applies the GTE predicate on the "result_contract" field.
func ResultContractGTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGTE(FieldResultContract, v))
}

// ResultContractLT applies the LT predicate on the "result_contract" field.
func ResultContractLT(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLT(FieldResultContract, v))
}

// ResultContractLTE applies the LTE predicate on the "result_contract" field.
func ResultContractLTE(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLTE(FieldResultContract, v))
}

// ResultContractContains applies the Contains predicate on the "result_contract" field.
func ResultContractContains(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContains(FieldResultContract, v))
}

// ResultContractHasPrefix applies the HasPrefix predicate on the "result_contract" field.
func ResultContractHasPrefix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasPrefix(FieldResultContract, v))
}

// ResultContractHasSuffix applies the HasSuffix predicate on the "result_contract" field.
func ResultContractHasSuffix(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldHasSuffix(FieldResultContract, v))
}

// ResultContractEqualFold applies the EqualFold predicate on the "result_contract" field.
func ResultContractEqualFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEqualFold(FieldResultContract, v))
}

// ResultContractContainsFold applies the ContainsFold predicate on the "result_contract" field.
func ResultContractContainsFold(v string) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldContainsFold(FieldResultContract, v))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotIn(FieldActorID, vs...))
}

// ActorIDGT applies the GT predicate on the "actor_id" field.
func ActorIDGT(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGT(FieldActorID, v))
}

// ActorIDGTE applies the GTE predicate on the "actor_id" field.
func ActorIDGTE(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGTE(FieldActorID, v))
}

// ActorIDLT applies the LT predicate on the "actor_id" field.
func ActorIDLT(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLT(FieldActorID, v))
}

// ActorIDLTE applies the LTE predicate on the "actor_id" field.
func ActorIDLTE(v int) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLTE(FieldActorID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SourceOrderLifecycleEvent) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SourceOrderLifecycleEvent) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SourceOrderLifecycleEvent) predicate.SourceOrderLifecycleEvent {
	return predicate.SourceOrderLifecycleEvent(sql.NotPredicates(p))
}
