// Code generated by ent, DO NOT EDIT.

package businessrecordevent

import (
	"server/internal/data/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLTE(FieldID, id))
}

// RecordID applies equality check predicate on the "record_id" field. It's identical to RecordIDEQ.
func RecordID(v int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldRecordID, v))
}

// ModuleKey applies equality check predicate on the "module_key" field. It's identical to ModuleKeyEQ.
func ModuleKey(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldModuleKey, v))
}

// ActionKey applies equality check predicate on the "action_key" field. It's identical to ActionKeyEQ.
func ActionKey(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldActionKey, v))
}

// FromStatusKey applies equality check predicate on the "from_status_key" field. It's identical to FromStatusKeyEQ.
func FromStatusKey(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldFromStatusKey, v))
}

// ToStatusKey applies equality check predicate on the "to_status_key" field. It's identical to ToStatusKeyEQ.
func ToStatusKey(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldToStatusKey, v))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldActorID, v))
}

// ActorRoleKey applies equality check predicate on the "actor_role_key" field. It's identical to ActorRoleKeyEQ.
func ActorRoleKey(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldActorRoleKey, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// RecordIDEQ applies the EQ predicate on the "record_id" field.
func RecordIDEQ(v int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldRecordID, v))
}

// RecordIDNEQ applies the NEQ predicate on the "record_id" field.
func RecordIDNEQ(v int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNEQ(FieldRecordID, v))
}

// RecordIDIn applies the In predicate on the "record_id" field.
func RecordIDIn(vs ...int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIn(FieldRecordID, vs...))
}

// RecordIDNotIn applies the NotIn predicate on the "record_id" field.
func RecordIDNotIn(vs ...int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotIn(FieldRecordID, vs...))
}

// RecordIDGT applies the GT predicate on the "record_id" field.
func RecordIDGT(v int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGT(FieldRecordID, v))
}

// RecordIDGTE applies the GTE predicate on the "record_id" field.
func RecordIDGTE(v int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGTE(FieldRecordID, v))
}

// RecordIDLT applies the LT predicate on the "record_id" field.
func RecordIDLT(v int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLT(FieldRecordID, v))
}

// RecordIDLTE applies the LTE predicate on the "record_id" field.
func RecordIDLTE(v int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLTE(FieldRecordID, v))
}

// RecordIDIsNil applies the IsNil predicate on the "record_id" field.
func RecordIDIsNil() predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIsNull(FieldRecordID))
}

// RecordIDNotNil applies the NotNil predicate on the "record_id" field.
func RecordIDNotNil() predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotNull(FieldRecordID))
}

// ModuleKeyEQ applies the EQ predicate on the "module_key" field.
func ModuleKeyEQ(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldModuleKey, v))
}

// ModuleKeyNEQ applies the NEQ predicate on the "module_key" field.
func ModuleKeyNEQ(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNEQ(FieldModuleKey, v))
}

// ModuleKeyIn applies the In predicate on the "module_key" field.
func ModuleKeyIn(vs ...string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIn(FieldModuleKey, vs...))
}

// ModuleKeyNotIn applies the NotIn predicate on the "module_key" field.
func ModuleKeyNotIn(vs ...string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotIn(FieldModuleKey, vs...))
}

// ModuleKeyGT applies the GT predicate on the "module_key" field.
func ModuleKeyGT(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGT(FieldModuleKey, v))
}

// ModuleKeyGTE applies the GTE predicate on the "module_key" field.
func ModuleKeyGTE(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGTE(FieldModuleKey, v))
}

// ModuleKeyLT applies the LT predicate on the "module_key" field.
func ModuleKeyLT(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLT(FieldModuleKey, v))
}

// ModuleKeyLTE applies the LTE predicate on the "module_key" field.
func ModuleKeyLTE(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLTE(FieldModuleKey, v))
}

// ModuleKeyContains applies the Contains predicate on the "module_key" field.
func ModuleKeyContains(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldContains(FieldModuleKey, v))
}

// ModuleKeyHasPrefix applies the HasPrefix predicate on the "module_key" field.
func ModuleKeyHasPrefix(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldHasPrefix(FieldModuleKey, v))
}

// ModuleKeyHasSuffix applies the HasSuffix predicate on the "module_key" field.
func ModuleKeyHasSuffix(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldHasSuffix(FieldModuleKey, v))
}

// ModuleKeyEqualFold applies the EqualFold predicate on the "module_key" field.
func ModuleKeyEqualFold(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEqualFold(FieldModuleKey, v))
}

// ModuleKeyContainsFold applies the ContainsFold predicate on the "module_key" field.
func ModuleKeyContainsFold(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldContainsFold(FieldModuleKey, v))
}

// ActionKeyEQ applies the EQ predicate on the "action_key" field.
func ActionKeyEQ(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldActionKey, v))
}

// ActionKeyNEQ applies the NEQ predicate on the "action_key" field.
func ActionKeyNEQ(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNEQ(FieldActionKey, v))
}

// ActionKeyIn applies the In predicate on the "action_key" field.
func ActionKeyIn(vs ...string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIn(FieldActionKey, vs...))
}

// ActionKeyNotIn applies the NotIn predicate on the "action_key" field.
func ActionKeyNotIn(vs ...string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotIn(FieldActionKey, vs...))
}

// ActionKeyGT applies the GT predicate on the "action_key" field.
func ActionKeyGT(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGT(FieldActionKey, v))
}

// ActionKeyGTE applies the GTE predicate on the "action_key" field.
func ActionKeyGTE(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGTE(FieldActionKey, v))
}

// ActionKeyLT applies the LT predicate on the "action_key" field.
func ActionKeyLT(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLT(FieldActionKey, v))
}

// ActionKeyLTE applies the LTE predicate on the "action_key" field.
func ActionKeyLTE(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLTE(FieldActionKey, v))
}

// ActionKeyContains applies the Contains predicate on the "action_key" field.
func ActionKeyContains(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldContains(FieldActionKey, v))
}

// ActionKeyHasPrefix applies the HasPrefix predicate on the "action_key" field.
func ActionKeyHasPrefix(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldHasPrefix(FieldActionKey, v))
}

// ActionKeyHasSuffix applies the HasSuffix predicate on the "action_key" field.
func ActionKeyHasSuffix(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldHasSuffix(FieldActionKey, v))
}

// ActionKeyEqualFold applies the EqualFold predicate on the "action_key" field.
func ActionKeyEqualFold(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEqualFold(FieldActionKey, v))
}

// ActionKeyContainsFold applies the ContainsFold predicate on the "action_key" field.
func ActionKeyContainsFold(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldContainsFold(FieldActionKey, v))
}

// FromStatusKeyEQ applies the EQ predicate on the "from_status_key" field.
func FromStatusKeyEQ(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldFromStatusKey, v))
}

// FromStatusKeyNEQ applies the NEQ predicate on the "from_status_key" field.
func FromStatusKeyNEQ(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNEQ(FieldFromStatusKey, v))
}

// FromStatusKeyIn applies the In predicate on the "from_status_key" field.
func FromStatusKeyIn(vs ...string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIn(FieldFromStatusKey, vs...))
}

// FromStatusKeyNotIn applies the NotIn predicate on the "from_status_key" field.
func FromStatusKeyNotIn(vs ...string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotIn(FieldFromStatusKey, vs...))
}

// FromStatusKeyGT applies the GT predicate on the "from_status_key" field.
func FromStatusKeyGT(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGT(FieldFromStatusKey, v))
}

// FromStatusKeyGTE applies the GTE predicate on the "from_status_key" field.
func FromStatusKeyGTE(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGTE(FieldFromStatusKey, v))
}

// FromStatusKeyLT applies the LT predicate on the "from_status_key" field.
func FromStatusKeyLT(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLT(FieldFromStatusKey, v))
}

// FromStatusKeyLTE applies the LTE predicate on the "from_status_key" field.
func FromStatusKeyLTE(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLTE(FieldFromStatusKey, v))
}

// FromStatusKeyContains applies the Contains predicate on the "from_status_key" field.
func FromStatusKeyContains(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldContains(FieldFromStatusKey, v))
}

// FromStatusKeyHasPrefix applies the HasPrefix predicate on the "from_status_key" field.
func FromStatusKeyHasPrefix(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldHasPrefix(FieldFromStatusKey, v))
}

// FromStatusKeyHasSuffix applies the HasSuffix predicate on the "from_status_key" field.
func FromStatusKeyHasSuffix(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldHasSuffix(FieldFromStatusKey, v))
}

// FromStatusKeyIsNil applies the IsNil predicate on the "from_status_key" field.
func FromStatusKeyIsNil() predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIsNull(FieldFromStatusKey))
}

// FromStatusKeyNotNil applies the NotNil predicate on the "from_status_key" field.
func FromStatusKeyNotNil() predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotNull(FieldFromStatusKey))
}

// FromStatusKeyEqualFold applies the EqualFold predicate on the "from_status_key" field.
func FromStatusKeyEqualFold(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEqualFold(FieldFromStatusKey, v))
}

// FromStatusKeyContainsFold applies the ContainsFold predicate on the "from_status_key" field.
func FromStatusKeyContainsFold(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldContainsFold(FieldFromStatusKey, v))
}

// ToStatusKeyEQ applies the EQ predicate on the "to_status_key" field.
func ToStatusKeyEQ(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldToStatusKey, v))
}

// ToStatusKeyNEQ applies the NEQ predicate on the "to_status_key" field.
func ToStatusKeyNEQ(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNEQ(FieldToStatusKey, v))
}

// ToStatusKeyIn applies the In predicate on the "to_status_key" field.
func ToStatusKeyIn(vs ...string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIn(FieldToStatusKey, vs...))
}

// ToStatusKeyNotIn applies the NotIn predicate on the "to_status_key" field.
func ToStatusKeyNotIn(vs ...string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotIn(FieldToStatusKey, vs...))
}

// ToStatusKeyGT applies the GT predicate on the "to_status_key" field.
func ToStatusKeyGT(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGT(FieldToStatusKey, v))
}

// ToStatusKeyGTE applies the GTE predicate on the "to_status_key" field.
func ToStatusKeyGTE(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGTE(FieldToStatusKey, v))
}

// ToStatusKeyLT applies the LT predicate on the "to_status_key" field.
func ToStatusKeyLT(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLT(FieldToStatusKey, v))
}

// ToStatusKeyLTE applies the LTE predicate on the "to_status_key" field.
func ToStatusKeyLTE(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLTE(FieldToStatusKey, v))
}

// ToStatusKeyContains applies the Contains predicate on the "to_status_key" field.
func ToStatusKeyContains(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldContains(FieldToStatusKey, v))
}

// ToStatusKeyHasPrefix applies the HasPrefix predicate on the "to_status_key" field.
func ToStatusKeyHasPrefix(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldHasPrefix(FieldToStatusKey, v))
}

// ToStatusKeyHasSuffix applies the HasSuffix predicate on the "to_status_key" field.
func ToStatusKeyHasSuffix(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldHasSuffix(FieldToStatusKey, v))
}

// ToStatusKeyIsNil applies the IsNil predicate on the "to_status_key" field.
func ToStatusKeyIsNil() predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIsNull(FieldToStatusKey))
}

// ToStatusKeyNotNil applies the NotNil predicate on the "to_status_key" field.
func ToStatusKeyNotNil() predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotNull(FieldToStatusKey))
}

// ToStatusKeyEqualFold applies the EqualFold predicate on the "to_status_key" field.
func ToStatusKeyEqualFold(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEqualFold(FieldToStatusKey, v))
}

// ToStatusKeyContainsFold applies the ContainsFold predicate on the "to_status_key" field.
func ToStatusKeyContainsFold(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldContainsFold(FieldToStatusKey, v))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotIn(FieldActorID, vs...))
}

// ActorIDGT applies the GT predicate on the "actor_id" field.
func ActorIDGT(v int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGT(FieldActorID, v))
}

// ActorIDGTE applies the GTE predicate on the "actor_id" field.
func ActorIDGTE(v int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGTE(FieldActorID, v))
}

// ActorIDLT applies the LT predicate on the "actor_id" field.
func ActorIDLT(v int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLT(FieldActorID, v))
}

// ActorIDLTE applies the LTE predicate on the "actor_id" field.
func ActorIDLTE(v int) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLTE(FieldActorID, v))
}

// ActorIDIsNil applies the IsNil predicate on the "actor_id" field.
func ActorIDIsNil() predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIsNull(FieldActorID))
}

// ActorIDNotNil applies the NotNil predicate on the "actor_id" field.
func ActorIDNotNil() predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotNull(FieldActorID))
}

// ActorRoleKeyEQ applies the EQ predicate on the "actor_role_key" field.
func ActorRoleKeyEQ(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldActorRoleKey, v))
}

// ActorRoleKeyNEQ applies the NEQ predicate on the "actor_role_key" field.
func ActorRoleKeyNEQ(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNEQ(FieldActorRoleKey, v))
}

// ActorRoleKeyIn applies the In predicate on the "actor_role_key" field.
func ActorRoleKeyIn(vs ...string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIn(FieldActorRoleKey, vs...))
}

// ActorRoleKeyNotIn applies the NotIn predicate on the "actor_role_key" field.
func ActorRoleKeyNotIn(vs ...string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotIn(FieldActorRoleKey, vs...))
}

// ActorRoleKeyGT applies the GT predicate on the "actor_role_key" field.
func ActorRoleKeyGT(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGT(FieldActorRoleKey, v))
}

// ActorRoleKeyGTE applies the GTE predicate on the "actor_role_key" field.
func ActorRoleKeyGTE(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGTE(FieldActorRoleKey, v))
}

// ActorRoleKeyLT applies the LT predicate on the "actor_role_key" field.
func ActorRoleKeyLT(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLT(FieldActorRoleKey, v))
}

// ActorRoleKeyLTE applies the LTE predicate on the "actor_role_key" field.
func ActorRoleKeyLTE(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLTE(FieldActorRoleKey, v))
}

// ActorRoleKeyContains applies the Contains predicate on the "actor_role_key" field.
func ActorRoleKeyContains(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldContains(FieldActorRoleKey, v))
}

// ActorRoleKeyHasPrefix applies the HasPrefix predicate on the "actor_role_key" field.
func ActorRoleKeyHasPrefix(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldHasPrefix(FieldActorRoleKey, v))
}

// ActorRoleKeyHasSuffix applies the HasSuffix predicate on the "actor_role_key" field.
func ActorRoleKeyHasSuffix(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldHasSuffix(FieldActorRoleKey, v))
}

// ActorRoleKeyIsNil applies the IsNil predicate on the "actor_role_key" field.
func ActorRoleKeyIsNil() predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIsNull(FieldActorRoleKey))
}

// ActorRoleKeyNotNil applies the NotNil predicate on the "actor_role_key" field.
func ActorRoleKeyNotNil() predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotNull(FieldActorRoleKey))
}

// ActorRoleKeyEqualFold applies the EqualFold predicate on the "actor_role_key" field.
func ActorRoleKeyEqualFold(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEqualFold(FieldActorRoleKey, v))
}

// ActorRoleKeyContainsFold applies the ContainsFold predicate on the "actor_role_key" field.
func ActorRoleKeyContainsFold(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldContainsFold(FieldActorRoleKey, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldContainsFold(FieldNote, v))
}

// PayloadIsNil applies the IsNil predicate on the "payload" field.
func PayloadIsNil() predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIsNull(FieldPayload))
}

// PayloadNotNil applies the NotNil predicate on the "payload" field.
func PayloadNotNil() predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotNull(FieldPayload))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BusinessRecordEvent) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BusinessRecordEvent) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BusinessRecordEvent) predicate.BusinessRecordEvent {
	return predicate.BusinessRecordEvent(sql.NotPredicates(p))
}
