// Code generated by ent, DO NOT EDIT.

package workflowtask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the workflowtask type in the database.
	Label = "workflow_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaskCode holds the string denoting the task_code field in the database.
	FieldTaskCode = "task_code"
	// FieldTaskGroup holds the string denoting the task_group field in the database.
	FieldTaskGroup = "task_group"
	// FieldTaskName holds the string denoting the task_name field in the database.
	FieldTaskName = "task_name"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldSourceNo holds the string denoting the source_no field in the database.
	FieldSourceNo = "source_no"
	// FieldBusinessStatusKey holds the string denoting the business_status_key field in the database.
	FieldBusinessStatusKey = "business_status_key"
	// FieldTaskStatusKey holds the string denoting the task_status_key field in the database.
	FieldTaskStatusKey = "task_status_key"
	// FieldOwnerRoleKey holds the string denoting the owner_role_key field in the database.
	FieldOwnerRoleKey = "owner_role_key"
	// FieldAssigneeID holds the string denoting the assignee_id field in the database.
	FieldAssigneeID = "assignee_id"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldBlockedReason holds the string denoting the blocked_reason field in the database.
	FieldBlockedReason = "blocked_reason"
	// FieldDueAt holds the string denoting the due_at field in the database.
	FieldDueAt = "due_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldClosedAt holds the string denoting the closed_at field in the database.
	FieldClosedAt = "closed_at"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// Table holds the table name of the workflowtask in the database.
	Table = "workflow_tasks"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "workflow_task_events"
	// EventsInverseTable is the table name for the WorkflowTaskEvent entity.
	// It exists in this package in order to avoid circular dependency with the "workflowtaskevent" package.
	EventsInverseTable = "workflow_task_events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "task_id"
)

// Columns holds all SQL columns for workflowtask fields.
var Columns = []string{
	FieldID,
	FieldTaskCode,
	FieldTaskGroup,
	FieldTaskName,
	FieldSourceType,
	FieldSourceID,
	FieldSourceNo,
	FieldBusinessStatusKey,
	FieldTaskStatusKey,
	FieldOwnerRoleKey,
	FieldAssigneeID,
	FieldPriority,
	FieldBlockedReason,
	FieldDueAt,
	FieldStartedAt,
	FieldCompletedAt,
	FieldClosedAt,
	FieldPayload,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TaskCodeValidator is a validator for the "task_code" field. It is called by the builders before save.
	TaskCodeValidator func(string) error
	// TaskGroupValidator is a validator for the "task_group" field. It is called by the builders before save.
	TaskGroupValidator func(string) error
	// TaskNameValidator is a validator for the "task_name" field. It is called by the builders before save.
	TaskNameValidator func(string) error
	// SourceTypeValidator is a validator for the "source_type" field. It is called by the builders before save.
	SourceTypeValidator func(string) error
	// SourceIDValidator is a validator for the "source_id" field. It is called by the builders before save.
	SourceIDValidator func(int) error
	// SourceNoValidator is a validator for the "source_no" field. It is called by the builders before save.
	SourceNoValidator func(string) error
	// BusinessStatusKeyValidator is a validator for the "business_status_key" field. It is called by the builders before save.
	BusinessStatusKeyValidator func(string) error
	// TaskStatusKeyValidator is a validator for the "task_status_key" field. It is called by the builders before save.
	TaskStatusKeyValidator func(string) error
	// OwnerRoleKeyValidator is a validator for the "owner_role_key" field. It is called by the builders before save.
	OwnerRoleKeyValidator func(string) error
	// AssigneeIDValidator is a validator for the "assignee_id" field. It is called by the builders before save.
	AssigneeIDValidator func(int) error
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int16
	// BlockedReasonValidator is a validator for the "blocked_reason" field. It is called by the builders before save.
	BlockedReasonValidator func(string) error
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(int) error
	// UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	UpdatedByValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the WorkflowTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTaskCode orders the results by the task_code field.
func ByTaskCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskCode, opts...).ToFunc()
}

// ByTaskGroup orders the results by the task_group field.
func ByTaskGroup(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskGroup, opts...).ToFunc()
}

// ByTaskName orders the results by the task_name field.
func ByTaskName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskName, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// BySourceNo orders the results by the source_no field.
func BySourceNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceNo, opts...).ToFunc()
}

// ByBusinessStatusKey orders the results by the business_status_key field.
func ByBusinessStatusKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBusinessStatusKey, opts...).ToFunc()
}

// ByTaskStatusKey orders the results by the task_status_key field.
func ByTaskStatusKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskStatusKey, opts...).ToFunc()
}

// ByOwnerRoleKey orders the results by the owner_role_key field.
func ByOwnerRoleKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerRoleKey, opts...).ToFunc()
}

// ByAssigneeID orders the results by the assignee_id field.
func ByAssigneeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssigneeID, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByBlockedReason orders the results by the blocked_reason field.
func ByBlockedReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlockedReason, opts...).ToFunc()
}

// ByDueAt orders the results by the due_at field.
func ByDueAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDueAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByClosedAt orders the results by the closed_at field.
func ByClosedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}
