// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"server/internal/data/model/ent/businessrecord"
	"server/internal/data/model/ent/predicate"
	"server/internal/data/model/ent/purchasereceipt"
	"server/internal/data/model/ent/purchasereceiptadjustment"
	"server/internal/data/model/ent/purchasereturn"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BusinessRecordQuery is the builder for querying BusinessRecord entities.
type BusinessRecordQuery struct {
	config
	ctx                            *QueryContext
	order                          []businessrecord.OrderOption
	inters                         []Interceptor
	predicates                     []predicate.BusinessRecord
	withPurchaseReceipts           *PurchaseReceiptQuery
	withPurchaseReturns            *PurchaseReturnQuery
	withPurchaseReceiptAdjustments *PurchaseReceiptAdjustmentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BusinessRecordQuery builder.
func (_q *BusinessRecordQuery) Where(ps ...predicate.BusinessRecord) *BusinessRecordQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *BusinessRecordQuery) Limit(limit int) *BusinessRecordQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *BusinessRecordQuery) Offset(offset int) *BusinessRecordQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *BusinessRecordQuery) Unique(unique bool) *BusinessRecordQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *BusinessRecordQuery) Order(o ...businessrecord.OrderOption) *BusinessRecordQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPurchaseReceipts chains the current query on the "purchase_receipts" edge.
func (_q *BusinessRecordQuery) QueryPurchaseReceipts() *PurchaseReceiptQuery {
	query := (&PurchaseReceiptClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(businessrecord.Table, businessrecord.FieldID, selector),
			sqlgraph.To(purchasereceipt.Table, purchasereceipt.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, businessrecord.PurchaseReceiptsTable, businessrecord.PurchaseReceiptsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPurchaseReturns chains the current query on the "purchase_returns" edge.
func (_q *BusinessRecordQuery) QueryPurchaseReturns() *PurchaseReturnQuery {
	query := (&PurchaseReturnClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(businessrecord.Table, businessrecord.FieldID, selector),
			sqlgraph.To(purchasereturn.Table, purchasereturn.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, businessrecord.PurchaseReturnsTable, businessrecord.PurchaseReturnsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPurchaseReceiptAdjustments chains the current query on the "purchase_receipt_adjustments" edge.
func (_q *BusinessRecordQuery) QueryPurchaseReceiptAdjustments() *PurchaseReceiptAdjustmentQuery {
	query := (&PurchaseReceiptAdjustmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(businessrecord.Table, businessrecord.FieldID, selector),
			sqlgraph.To(purchasereceiptadjustment.Table, purchasereceiptadjustment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, businessrecord.PurchaseReceiptAdjustmentsTable, businessrecord.PurchaseReceiptAdjustmentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BusinessRecord entity from the query.
// Returns a *NotFoundError when no BusinessRecord was found.
func (_q *BusinessRecordQuery) First(ctx context.Context) (*BusinessRecord, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{businessrecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *BusinessRecordQuery) FirstX(ctx context.Context) *BusinessRecord {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BusinessRecord ID from the query.
// Returns a *NotFoundError when no BusinessRecord ID was found.
func (_q *BusinessRecordQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{businessrecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *BusinessRecordQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BusinessRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BusinessRecord entity is found.
// Returns a *NotFoundError when no BusinessRecord entities are found.
func (_q *BusinessRecordQuery) Only(ctx context.Context) (*BusinessRecord, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{businessrecord.Label}
	default:
		return nil, &NotSingularError{businessrecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *BusinessRecordQuery) OnlyX(ctx context.Context) *BusinessRecord {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BusinessRecord ID in the query.
// Returns a *NotSingularError when more than one BusinessRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *BusinessRecordQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{businessrecord.Label}
	default:
		err = &NotSingularError{businessrecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *BusinessRecordQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BusinessRecords.
func (_q *BusinessRecordQuery) All(ctx context.Context) ([]*BusinessRecord, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BusinessRecord, *BusinessRecordQuery]()
	return withInterceptors[[]*BusinessRecord](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *BusinessRecordQuery) AllX(ctx context.Context) []*BusinessRecord {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BusinessRecord IDs.
func (_q *BusinessRecordQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(businessrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *BusinessRecordQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *BusinessRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*BusinessRecordQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *BusinessRecordQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *BusinessRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *BusinessRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BusinessRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *BusinessRecordQuery) Clone() *BusinessRecordQuery {
	if _q == nil {
		return nil
	}
	return &BusinessRecordQuery{
		config:                         _q.config,
		ctx:                            _q.ctx.Clone(),
		order:                          append([]businessrecord.OrderOption{}, _q.order...),
		inters:                         append([]Interceptor{}, _q.inters...),
		predicates:                     append([]predicate.BusinessRecord{}, _q.predicates...),
		withPurchaseReceipts:           _q.withPurchaseReceipts.Clone(),
		withPurchaseReturns:            _q.withPurchaseReturns.Clone(),
		withPurchaseReceiptAdjustments: _q.withPurchaseReceiptAdjustments.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPurchaseReceipts tells the query-builder to eager-load the nodes that are connected to
// the "purchase_receipts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BusinessRecordQuery) WithPurchaseReceipts(opts ...func(*PurchaseReceiptQuery)) *BusinessRecordQuery {
	query := (&PurchaseReceiptClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPurchaseReceipts = query
	return _q
}

// WithPurchaseReturns tells the query-builder to eager-load the nodes that are connected to
// the "purchase_returns" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BusinessRecordQuery) WithPurchaseReturns(opts ...func(*PurchaseReturnQuery)) *BusinessRecordQuery {
	query := (&PurchaseReturnClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPurchaseReturns = query
	return _q
}

// WithPurchaseReceiptAdjustments tells the query-builder to eager-load the nodes that are connected to
// the "purchase_receipt_adjustments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BusinessRecordQuery) WithPurchaseReceiptAdjustments(opts ...func(*PurchaseReceiptAdjustmentQuery)) *BusinessRecordQuery {
	query := (&PurchaseReceiptAdjustmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPurchaseReceiptAdjustments = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ModuleKey string `json:"module_key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BusinessRecord.Query().
//		GroupBy(businessrecord.FieldModuleKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *BusinessRecordQuery) GroupBy(field string, fields ...string) *BusinessRecordGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BusinessRecordGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = businessrecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ModuleKey string `json:"module_key,omitempty"`
//	}
//
//	client.BusinessRecord.Query().
//		Select(businessrecord.FieldModuleKey).
//		Scan(ctx, &v)
func (_q *BusinessRecordQuery) Select(fields ...string) *BusinessRecordSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &BusinessRecordSelect{BusinessRecordQuery: _q}
	sbuild.label = businessrecord.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BusinessRecordSelect configured with the given aggregations.
func (_q *BusinessRecordQuery) Aggregate(fns ...AggregateFunc) *BusinessRecordSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *BusinessRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !businessrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *BusinessRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BusinessRecord, error) {
	var (
		nodes       = []*BusinessRecord{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withPurchaseReceipts != nil,
			_q.withPurchaseReturns != nil,
			_q.withPurchaseReceiptAdjustments != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BusinessRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BusinessRecord{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPurchaseReceipts; query != nil {
		if err := _q.loadPurchaseReceipts(ctx, query, nodes,
			func(n *BusinessRecord) { n.Edges.PurchaseReceipts = []*PurchaseReceipt{} },
			func(n *BusinessRecord, e *PurchaseReceipt) {
				n.Edges.PurchaseReceipts = append(n.Edges.PurchaseReceipts, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withPurchaseReturns; query != nil {
		if err := _q.loadPurchaseReturns(ctx, query, nodes,
			func(n *BusinessRecord) { n.Edges.PurchaseReturns = []*PurchaseReturn{} },
			func(n *BusinessRecord, e *PurchaseReturn) {
				n.Edges.PurchaseReturns = append(n.Edges.PurchaseReturns, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withPurchaseReceiptAdjustments; query != nil {
		if err := _q.loadPurchaseReceiptAdjustments(ctx, query, nodes,
			func(n *BusinessRecord) { n.Edges.PurchaseReceiptAdjustments = []*PurchaseReceiptAdjustment{} },
			func(n *BusinessRecord, e *PurchaseReceiptAdjustment) {
				n.Edges.PurchaseReceiptAdjustments = append(n.Edges.PurchaseReceiptAdjustments, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *BusinessRecordQuery) loadPurchaseReceipts(ctx context.Context, query *PurchaseReceiptQuery, nodes []*BusinessRecord, init func(*BusinessRecord), assign func(*BusinessRecord, *PurchaseReceipt)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*BusinessRecord)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(purchasereceipt.FieldBusinessRecordID)
	}
	query.Where(predicate.PurchaseReceipt(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(businessrecord.PurchaseReceiptsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BusinessRecordID
		if fk == nil {
			return fmt.Errorf(`foreign-key "business_record_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "business_record_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *BusinessRecordQuery) loadPurchaseReturns(ctx context.Context, query *PurchaseReturnQuery, nodes []*BusinessRecord, init func(*BusinessRecord), assign func(*BusinessRecord, *PurchaseReturn)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*BusinessRecord)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(purchasereturn.FieldBusinessRecordID)
	}
	query.Where(predicate.PurchaseReturn(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(businessrecord.PurchaseReturnsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BusinessRecordID
		if fk == nil {
			return fmt.Errorf(`foreign-key "business_record_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "business_record_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *BusinessRecordQuery) loadPurchaseReceiptAdjustments(ctx context.Context, query *PurchaseReceiptAdjustmentQuery, nodes []*BusinessRecord, init func(*BusinessRecord), assign func(*BusinessRecord, *PurchaseReceiptAdjustment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*BusinessRecord)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(purchasereceiptadjustment.FieldBusinessRecordID)
	}
	query.Where(predicate.PurchaseReceiptAdjustment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(businessrecord.PurchaseReceiptAdjustmentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.BusinessRecordID
		if fk == nil {
			return fmt.Errorf(`foreign-key "business_record_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "business_record_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *BusinessRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *BusinessRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(businessrecord.Table, businessrecord.Columns, sqlgraph.NewFieldSpec(businessrecord.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, businessrecord.FieldID)
		for i := range fields {
			if fields[i] != businessrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *BusinessRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(businessrecord.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = businessrecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BusinessRecordGroupBy is the group-by builder for BusinessRecord entities.
type BusinessRecordGroupBy struct {
	selector
	build *BusinessRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *BusinessRecordGroupBy) Aggregate(fns ...AggregateFunc) *BusinessRecordGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *BusinessRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BusinessRecordQuery, *BusinessRecordGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *BusinessRecordGroupBy) sqlScan(ctx context.Context, root *BusinessRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BusinessRecordSelect is the builder for selecting fields of BusinessRecord entities.
type BusinessRecordSelect struct {
	*BusinessRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *BusinessRecordSelect) Aggregate(fns ...AggregateFunc) *BusinessRecordSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *BusinessRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BusinessRecordQuery, *BusinessRecordSelect](ctx, _s.BusinessRecordQuery, _s, _s.inters, v)
}

func (_s *BusinessRecordSelect) sqlScan(ctx context.Context, root *BusinessRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
