// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"server/internal/data/model/ent/process"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Process is the model entity for the Process schema.
type Process struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Category holds the value of the "category" field.
	Category *string `json:"category,omitempty"`
	// OutsourcingEnabled holds the value of the "outsourcing_enabled" field.
	OutsourcingEnabled bool `json:"outsourcing_enabled,omitempty"`
	// InhouseEnabled holds the value of the "inhouse_enabled" field.
	InhouseEnabled bool `json:"inhouse_enabled,omitempty"`
	// QualityRequired holds the value of the "quality_required" field.
	QualityRequired bool `json:"quality_required,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Note holds the value of the "note" field.
	Note *string `json:"note,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProcessQuery when eager-loading is set.
	Edges        ProcessEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProcessEdges holds the relations/edges for other nodes in the graph.
type ProcessEdges struct {
	// OutsourcingOrderItems holds the value of the outsourcing_order_items edge.
	OutsourcingOrderItems []*OutsourcingOrderItem `json:"outsourcing_order_items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OutsourcingOrderItemsOrErr returns the OutsourcingOrderItems value or an error if the edge
// was not loaded in eager-loading.
func (e ProcessEdges) OutsourcingOrderItemsOrErr() ([]*OutsourcingOrderItem, error) {
	if e.loadedTypes[0] {
		return e.OutsourcingOrderItems, nil
	}
	return nil, &NotLoadedError{edge: "outsourcing_order_items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Process) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case process.FieldOutsourcingEnabled, process.FieldInhouseEnabled, process.FieldQualityRequired, process.FieldIsActive:
			values[i] = new(sql.NullBool)
		case process.FieldID, process.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case process.FieldCode, process.FieldName, process.FieldCategory, process.FieldNote:
			values[i] = new(sql.NullString)
		case process.FieldCreatedAt, process.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Process fields.
func (_m *Process) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case process.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case process.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case process.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case process.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = new(string)
				*_m.Category = value.String
			}
		case process.FieldOutsourcingEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field outsourcing_enabled", values[i])
			} else if value.Valid {
				_m.OutsourcingEnabled = value.Bool
			}
		case process.FieldInhouseEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field inhouse_enabled", values[i])
			} else if value.Valid {
				_m.InhouseEnabled = value.Bool
			}
		case process.FieldQualityRequired:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field quality_required", values[i])
			} else if value.Valid {
				_m.QualityRequired = value.Bool
			}
		case process.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case process.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = new(string)
				*_m.Note = value.String
			}
		case process.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case process.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case process.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Process.
// This includes values selected through modifiers, order, etc.
func (_m *Process) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOutsourcingOrderItems queries the "outsourcing_order_items" edge of the Process entity.
func (_m *Process) QueryOutsourcingOrderItems() *OutsourcingOrderItemQuery {
	return NewProcessClient(_m.config).QueryOutsourcingOrderItems(_m)
}

// Update returns a builder for updating this Process.
// Note that you need to call Process.Unwrap() before calling this method if this Process
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Process) Update() *ProcessUpdateOne {
	return NewProcessClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Process entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Process) Unwrap() *Process {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Process is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Process) String() string {
	var builder strings.Builder
	builder.WriteString("Process(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Category; v != nil {
		builder.WriteString("category=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("outsourcing_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutsourcingEnabled))
	builder.WriteString(", ")
	builder.WriteString("inhouse_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.InhouseEnabled))
	builder.WriteString(", ")
	builder.WriteString("quality_required=")
	builder.WriteString(fmt.Sprintf("%v", _m.QualityRequired))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	if v := _m.Note; v != nil {
		builder.WriteString("note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Processes is a parsable slice of Process.
type Processes []*Process
