// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/outsourcingorderitem"
	"server/internal/data/model/ent/process"
	"server/internal/data/model/ent/supplier"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProcessCreate is the builder for creating a Process entity.
type ProcessCreate struct {
	config
	mutation *ProcessMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *ProcessCreate) SetCode(v string) *ProcessCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ProcessCreate) SetName(v string) *ProcessCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *ProcessCreate) SetCategory(v string) *ProcessCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *ProcessCreate) SetNillableCategory(v *string) *ProcessCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetProductionRouteOperationCode sets the "production_route_operation_code" field.
func (_c *ProcessCreate) SetProductionRouteOperationCode(v string) *ProcessCreate {
	_c.mutation.SetProductionRouteOperationCode(v)
	return _c
}

// SetNillableProductionRouteOperationCode sets the "production_route_operation_code" field if the given value is not nil.
func (_c *ProcessCreate) SetNillableProductionRouteOperationCode(v *string) *ProcessCreate {
	if v != nil {
		_c.SetProductionRouteOperationCode(*v)
	}
	return _c
}

// SetOutsourcingEnabled sets the "outsourcing_enabled" field.
func (_c *ProcessCreate) SetOutsourcingEnabled(v bool) *ProcessCreate {
	_c.mutation.SetOutsourcingEnabled(v)
	return _c
}

// SetNillableOutsourcingEnabled sets the "outsourcing_enabled" field if the given value is not nil.
func (_c *ProcessCreate) SetNillableOutsourcingEnabled(v *bool) *ProcessCreate {
	if v != nil {
		_c.SetOutsourcingEnabled(*v)
	}
	return _c
}

// SetInhouseEnabled sets the "inhouse_enabled" field.
func (_c *ProcessCreate) SetInhouseEnabled(v bool) *ProcessCreate {
	_c.mutation.SetInhouseEnabled(v)
	return _c
}

// SetNillableInhouseEnabled sets the "inhouse_enabled" field if the given value is not nil.
func (_c *ProcessCreate) SetNillableInhouseEnabled(v *bool) *ProcessCreate {
	if v != nil {
		_c.SetInhouseEnabled(*v)
	}
	return _c
}

// SetQualityRequired sets the "quality_required" field.
func (_c *ProcessCreate) SetQualityRequired(v bool) *ProcessCreate {
	_c.mutation.SetQualityRequired(v)
	return _c
}

// SetNillableQualityRequired sets the "quality_required" field if the given value is not nil.
func (_c *ProcessCreate) SetNillableQualityRequired(v *bool) *ProcessCreate {
	if v != nil {
		_c.SetQualityRequired(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *ProcessCreate) SetSortOrder(v int) *ProcessCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *ProcessCreate) SetNillableSortOrder(v *int) *ProcessCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *ProcessCreate) SetNote(v string) *ProcessCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *ProcessCreate) SetNillableNote(v *string) *ProcessCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *ProcessCreate) SetIsActive(v bool) *ProcessCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *ProcessCreate) SetNillableIsActive(v *bool) *ProcessCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProcessCreate) SetCreatedAt(v time.Time) *ProcessCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProcessCreate) SetNillableCreatedAt(v *time.Time) *ProcessCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProcessCreate) SetUpdatedAt(v time.Time) *ProcessCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProcessCreate) SetNillableUpdatedAt(v *time.Time) *ProcessCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddOutsourcingOrderItemIDs adds the "outsourcing_order_items" edge to the OutsourcingOrderItem entity by IDs.
func (_c *ProcessCreate) AddOutsourcingOrderItemIDs(ids ...int) *ProcessCreate {
	_c.mutation.AddOutsourcingOrderItemIDs(ids...)
	return _c
}

// AddOutsourcingOrderItems adds the "outsourcing_order_items" edges to the OutsourcingOrderItem entity.
func (_c *ProcessCreate) AddOutsourcingOrderItems(v ...*OutsourcingOrderItem) *ProcessCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOutsourcingOrderItemIDs(ids...)
}

// AddCapableSupplierIDs adds the "capable_suppliers" edge to the Supplier entity by IDs.
func (_c *ProcessCreate) AddCapableSupplierIDs(ids ...int) *ProcessCreate {
	_c.mutation.AddCapableSupplierIDs(ids...)
	return _c
}

// AddCapableSuppliers adds the "capable_suppliers" edges to the Supplier entity.
func (_c *ProcessCreate) AddCapableSuppliers(v ...*Supplier) *ProcessCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCapableSupplierIDs(ids...)
}

// Mutation returns the ProcessMutation object of the builder.
func (_c *ProcessCreate) Mutation() *ProcessMutation {
	return _c.mutation
}

// Save creates the Process in the database.
func (_c *ProcessCreate) Save(ctx context.Context) (*Process, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProcessCreate) SaveX(ctx context.Context) *Process {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProcessCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProcessCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProcessCreate) defaults() {
	if _, ok := _c.mutation.OutsourcingEnabled(); !ok {
		v := process.DefaultOutsourcingEnabled
		_c.mutation.SetOutsourcingEnabled(v)
	}
	if _, ok := _c.mutation.InhouseEnabled(); !ok {
		v := process.DefaultInhouseEnabled
		_c.mutation.SetInhouseEnabled(v)
	}
	if _, ok := _c.mutation.QualityRequired(); !ok {
		v := process.DefaultQualityRequired
		_c.mutation.SetQualityRequired(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := process.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := process.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := process.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := process.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProcessCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Process.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := process.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Process.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Process.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := process.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Process.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := process.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Process.category": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProductionRouteOperationCode(); ok {
		if err := process.ProductionRouteOperationCodeValidator(v); err != nil {
			return &ValidationError{Name: "production_route_operation_code", err: fmt.Errorf(`ent: validator failed for field "Process.production_route_operation_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OutsourcingEnabled(); !ok {
		return &ValidationError{Name: "outsourcing_enabled", err: errors.New(`ent: missing required field "Process.outsourcing_enabled"`)}
	}
	if _, ok := _c.mutation.InhouseEnabled(); !ok {
		return &ValidationError{Name: "inhouse_enabled", err: errors.New(`ent: missing required field "Process.inhouse_enabled"`)}
	}
	if _, ok := _c.mutation.QualityRequired(); !ok {
		return &ValidationError{Name: "quality_required", err: errors.New(`ent: missing required field "Process.quality_required"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Process.sort_order"`)}
	}
	if v, ok := _c.mutation.SortOrder(); ok {
		if err := process.SortOrderValidator(v); err != nil {
			return &ValidationError{Name: "sort_order", err: fmt.Errorf(`ent: validator failed for field "Process.sort_order": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Note(); ok {
		if err := process.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "Process.note": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Process.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Process.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Process.updated_at"`)}
	}
	return nil
}

func (_c *ProcessCreate) sqlSave(ctx context.Context) (*Process, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProcessCreate) createSpec() (*Process, *sqlgraph.CreateSpec) {
	var (
		_node = &Process{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(process.Table, sqlgraph.NewFieldSpec(process.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(process.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(process.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(process.FieldCategory, field.TypeString, value)
		_node.Category = &value
	}
	if value, ok := _c.mutation.ProductionRouteOperationCode(); ok {
		_spec.SetField(process.FieldProductionRouteOperationCode, field.TypeString, value)
		_node.ProductionRouteOperationCode = &value
	}
	if value, ok := _c.mutation.OutsourcingEnabled(); ok {
		_spec.SetField(process.FieldOutsourcingEnabled, field.TypeBool, value)
		_node.OutsourcingEnabled = value
	}
	if value, ok := _c.mutation.InhouseEnabled(); ok {
		_spec.SetField(process.FieldInhouseEnabled, field.TypeBool, value)
		_node.InhouseEnabled = value
	}
	if value, ok := _c.mutation.QualityRequired(); ok {
		_spec.SetField(process.FieldQualityRequired, field.TypeBool, value)
		_node.QualityRequired = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(process.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(process.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(process.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(process.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(process.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OutsourcingOrderItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   process.OutsourcingOrderItemsTable,
			Columns: []string{process.OutsourcingOrderItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(outsourcingorderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CapableSuppliersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   process.CapableSuppliersTable,
			Columns: process.CapableSuppliersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplier.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProcessCreateBulk is the builder for creating many Process entities in bulk.
type ProcessCreateBulk struct {
	config
	err      error
	builders []*ProcessCreate
}

// Save creates the Process entities in the database.
func (_c *ProcessCreateBulk) Save(ctx context.Context) ([]*Process, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Process, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProcessMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProcessCreateBulk) SaveX(ctx context.Context) []*Process {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProcessCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProcessCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
