// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"server/internal/data/model/ent/adminuser"
	"server/internal/data/model/ent/predicate"
	"server/internal/data/model/ent/productionorder"
	"server/internal/data/model/ent/productionorderevent"
	"server/internal/data/model/ent/productionorderitem"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductionOrderQuery is the builder for querying ProductionOrder entities.
type ProductionOrderQuery struct {
	config
	ctx           *QueryContext
	order         []productionorder.OrderOption
	inters        []Interceptor
	predicates    []predicate.ProductionOrder
	withItems     *ProductionOrderItemQuery
	withEvents    *ProductionOrderEventQuery
	withCreator   *AdminUserQuery
	withReleaser  *AdminUserQuery
	withCloser    *AdminUserQuery
	withCanceller *AdminUserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductionOrderQuery builder.
func (_q *ProductionOrderQuery) Where(ps ...predicate.ProductionOrder) *ProductionOrderQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ProductionOrderQuery) Limit(limit int) *ProductionOrderQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ProductionOrderQuery) Offset(offset int) *ProductionOrderQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ProductionOrderQuery) Unique(unique bool) *ProductionOrderQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ProductionOrderQuery) Order(o ...productionorder.OrderOption) *ProductionOrderQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryItems chains the current query on the "items" edge.
func (_q *ProductionOrderQuery) QueryItems() *ProductionOrderItemQuery {
	query := (&ProductionOrderItemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productionorder.Table, productionorder.FieldID, selector),
			sqlgraph.To(productionorderitem.Table, productionorderitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, productionorder.ItemsTable, productionorder.ItemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEvents chains the current query on the "events" edge.
func (_q *ProductionOrderQuery) QueryEvents() *ProductionOrderEventQuery {
	query := (&ProductionOrderEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productionorder.Table, productionorder.FieldID, selector),
			sqlgraph.To(productionorderevent.Table, productionorderevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, productionorder.EventsTable, productionorder.EventsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCreator chains the current query on the "creator" edge.
func (_q *ProductionOrderQuery) QueryCreator() *AdminUserQuery {
	query := (&AdminUserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productionorder.Table, productionorder.FieldID, selector),
			sqlgraph.To(adminuser.Table, adminuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, productionorder.CreatorTable, productionorder.CreatorColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReleaser chains the current query on the "releaser" edge.
func (_q *ProductionOrderQuery) QueryReleaser() *AdminUserQuery {
	query := (&AdminUserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productionorder.Table, productionorder.FieldID, selector),
			sqlgraph.To(adminuser.Table, adminuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, productionorder.ReleaserTable, productionorder.ReleaserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCloser chains the current query on the "closer" edge.
func (_q *ProductionOrderQuery) QueryCloser() *AdminUserQuery {
	query := (&AdminUserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productionorder.Table, productionorder.FieldID, selector),
			sqlgraph.To(adminuser.Table, adminuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, productionorder.CloserTable, productionorder.CloserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCanceller chains the current query on the "canceller" edge.
func (_q *ProductionOrderQuery) QueryCanceller() *AdminUserQuery {
	query := (&AdminUserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productionorder.Table, productionorder.FieldID, selector),
			sqlgraph.To(adminuser.Table, adminuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, productionorder.CancellerTable, productionorder.CancellerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProductionOrder entity from the query.
// Returns a *NotFoundError when no ProductionOrder was found.
func (_q *ProductionOrderQuery) First(ctx context.Context) (*ProductionOrder, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{productionorder.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ProductionOrderQuery) FirstX(ctx context.Context) *ProductionOrder {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProductionOrder ID from the query.
// Returns a *NotFoundError when no ProductionOrder ID was found.
func (_q *ProductionOrderQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{productionorder.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ProductionOrderQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProductionOrder entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProductionOrder entity is found.
// Returns a *NotFoundError when no ProductionOrder entities are found.
func (_q *ProductionOrderQuery) Only(ctx context.Context) (*ProductionOrder, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{productionorder.Label}
	default:
		return nil, &NotSingularError{productionorder.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ProductionOrderQuery) OnlyX(ctx context.Context) *ProductionOrder {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProductionOrder ID in the query.
// Returns a *NotSingularError when more than one ProductionOrder ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ProductionOrderQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{productionorder.Label}
	default:
		err = &NotSingularError{productionorder.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ProductionOrderQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProductionOrders.
func (_q *ProductionOrderQuery) All(ctx context.Context) ([]*ProductionOrder, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProductionOrder, *ProductionOrderQuery]()
	return withInterceptors[[]*ProductionOrder](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ProductionOrderQuery) AllX(ctx context.Context) []*ProductionOrder {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProductionOrder IDs.
func (_q *ProductionOrderQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(productionorder.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ProductionOrderQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ProductionOrderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ProductionOrderQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ProductionOrderQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ProductionOrderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ProductionOrderQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductionOrderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ProductionOrderQuery) Clone() *ProductionOrderQuery {
	if _q == nil {
		return nil
	}
	return &ProductionOrderQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]productionorder.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.ProductionOrder{}, _q.predicates...),
		withItems:     _q.withItems.Clone(),
		withEvents:    _q.withEvents.Clone(),
		withCreator:   _q.withCreator.Clone(),
		withReleaser:  _q.withReleaser.Clone(),
		withCloser:    _q.withCloser.Clone(),
		withCanceller: _q.withCanceller.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithItems tells the query-builder to eager-load the nodes that are connected to
// the "items" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProductionOrderQuery) WithItems(opts ...func(*ProductionOrderItemQuery)) *ProductionOrderQuery {
	query := (&ProductionOrderItemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withItems = query
	return _q
}

// WithEvents tells the query-builder to eager-load the nodes that are connected to
// the "events" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProductionOrderQuery) WithEvents(opts ...func(*ProductionOrderEventQuery)) *ProductionOrderQuery {
	query := (&ProductionOrderEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEvents = query
	return _q
}

// WithCreator tells the query-builder to eager-load the nodes that are connected to
// the "creator" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProductionOrderQuery) WithCreator(opts ...func(*AdminUserQuery)) *ProductionOrderQuery {
	query := (&AdminUserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCreator = query
	return _q
}

// WithReleaser tells the query-builder to eager-load the nodes that are connected to
// the "releaser" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProductionOrderQuery) WithReleaser(opts ...func(*AdminUserQuery)) *ProductionOrderQuery {
	query := (&AdminUserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReleaser = query
	return _q
}

// WithCloser tells the query-builder to eager-load the nodes that are connected to
// the "closer" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProductionOrderQuery) WithCloser(opts ...func(*AdminUserQuery)) *ProductionOrderQuery {
	query := (&AdminUserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCloser = query
	return _q
}

// WithCanceller tells the query-builder to eager-load the nodes that are connected to
// the "canceller" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ProductionOrderQuery) WithCanceller(opts ...func(*AdminUserQuery)) *ProductionOrderQuery {
	query := (&AdminUserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCanceller = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OrderNo string `json:"order_no,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProductionOrder.Query().
//		GroupBy(productionorder.FieldOrderNo).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ProductionOrderQuery) GroupBy(field string, fields ...string) *ProductionOrderGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProductionOrderGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = productionorder.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OrderNo string `json:"order_no,omitempty"`
//	}
//
//	client.ProductionOrder.Query().
//		Select(productionorder.FieldOrderNo).
//		Scan(ctx, &v)
func (_q *ProductionOrderQuery) Select(fields ...string) *ProductionOrderSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ProductionOrderSelect{ProductionOrderQuery: _q}
	sbuild.label = productionorder.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProductionOrderSelect configured with the given aggregations.
func (_q *ProductionOrderQuery) Aggregate(fns ...AggregateFunc) *ProductionOrderSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ProductionOrderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !productionorder.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ProductionOrderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProductionOrder, error) {
	var (
		nodes       = []*ProductionOrder{}
		_spec       = _q.querySpec()
		loadedTypes = [6]bool{
			_q.withItems != nil,
			_q.withEvents != nil,
			_q.withCreator != nil,
			_q.withReleaser != nil,
			_q.withCloser != nil,
			_q.withCanceller != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProductionOrder).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProductionOrder{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withItems; query != nil {
		if err := _q.loadItems(ctx, query, nodes,
			func(n *ProductionOrder) { n.Edges.Items = []*ProductionOrderItem{} },
			func(n *ProductionOrder, e *ProductionOrderItem) { n.Edges.Items = append(n.Edges.Items, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEvents; query != nil {
		if err := _q.loadEvents(ctx, query, nodes,
			func(n *ProductionOrder) { n.Edges.Events = []*ProductionOrderEvent{} },
			func(n *ProductionOrder, e *ProductionOrderEvent) { n.Edges.Events = append(n.Edges.Events, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCreator; query != nil {
		if err := _q.loadCreator(ctx, query, nodes, nil,
			func(n *ProductionOrder, e *AdminUser) { n.Edges.Creator = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withReleaser; query != nil {
		if err := _q.loadReleaser(ctx, query, nodes, nil,
			func(n *ProductionOrder, e *AdminUser) { n.Edges.Releaser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCloser; query != nil {
		if err := _q.loadCloser(ctx, query, nodes, nil,
			func(n *ProductionOrder, e *AdminUser) { n.Edges.Closer = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCanceller; query != nil {
		if err := _q.loadCanceller(ctx, query, nodes, nil,
			func(n *ProductionOrder, e *AdminUser) { n.Edges.Canceller = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ProductionOrderQuery) loadItems(ctx context.Context, query *ProductionOrderItemQuery, nodes []*ProductionOrder, init func(*ProductionOrder), assign func(*ProductionOrder, *ProductionOrderItem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ProductionOrder)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(productionorderitem.FieldProductionOrderID)
	}
	query.Where(predicate.ProductionOrderItem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(productionorder.ItemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProductionOrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "production_order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ProductionOrderQuery) loadEvents(ctx context.Context, query *ProductionOrderEventQuery, nodes []*ProductionOrder, init func(*ProductionOrder), assign func(*ProductionOrder, *ProductionOrderEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ProductionOrder)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(productionorderevent.FieldProductionOrderID)
	}
	query.Where(predicate.ProductionOrderEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(productionorder.EventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ProductionOrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "production_order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ProductionOrderQuery) loadCreator(ctx context.Context, query *AdminUserQuery, nodes []*ProductionOrder, init func(*ProductionOrder), assign func(*ProductionOrder, *AdminUser)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ProductionOrder)
	for i := range nodes {
		fk := nodes[i].CreatedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(adminuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "created_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProductionOrderQuery) loadReleaser(ctx context.Context, query *AdminUserQuery, nodes []*ProductionOrder, init func(*ProductionOrder), assign func(*ProductionOrder, *AdminUser)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ProductionOrder)
	for i := range nodes {
		if nodes[i].ReleasedBy == nil {
			continue
		}
		fk := *nodes[i].ReleasedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(adminuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "released_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProductionOrderQuery) loadCloser(ctx context.Context, query *AdminUserQuery, nodes []*ProductionOrder, init func(*ProductionOrder), assign func(*ProductionOrder, *AdminUser)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ProductionOrder)
	for i := range nodes {
		if nodes[i].ClosedBy == nil {
			continue
		}
		fk := *nodes[i].ClosedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(adminuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "closed_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ProductionOrderQuery) loadCanceller(ctx context.Context, query *AdminUserQuery, nodes []*ProductionOrder, init func(*ProductionOrder), assign func(*ProductionOrder, *AdminUser)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ProductionOrder)
	for i := range nodes {
		if nodes[i].CancelledBy == nil {
			continue
		}
		fk := *nodes[i].CancelledBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(adminuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "cancelled_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ProductionOrderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ProductionOrderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(productionorder.Table, productionorder.Columns, sqlgraph.NewFieldSpec(productionorder.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productionorder.FieldID)
		for i := range fields {
			if fields[i] != productionorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withCreator != nil {
			_spec.Node.AddColumnOnce(productionorder.FieldCreatedBy)
		}
		if _q.withReleaser != nil {
			_spec.Node.AddColumnOnce(productionorder.FieldReleasedBy)
		}
		if _q.withCloser != nil {
			_spec.Node.AddColumnOnce(productionorder.FieldClosedBy)
		}
		if _q.withCanceller != nil {
			_spec.Node.AddColumnOnce(productionorder.FieldCancelledBy)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ProductionOrderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(productionorder.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = productionorder.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProductionOrderGroupBy is the group-by builder for ProductionOrder entities.
type ProductionOrderGroupBy struct {
	selector
	build *ProductionOrderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ProductionOrderGroupBy) Aggregate(fns ...AggregateFunc) *ProductionOrderGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ProductionOrderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductionOrderQuery, *ProductionOrderGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ProductionOrderGroupBy) sqlScan(ctx context.Context, root *ProductionOrderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProductionOrderSelect is the builder for selecting fields of ProductionOrder entities.
type ProductionOrderSelect struct {
	*ProductionOrderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ProductionOrderSelect) Aggregate(fns ...AggregateFunc) *ProductionOrderSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ProductionOrderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductionOrderQuery, *ProductionOrderSelect](ctx, _s.ProductionOrderQuery, _s, _s.inters, v)
}

func (_s *ProductionOrderSelect) sqlScan(ctx context.Context, root *ProductionOrderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
