// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/adminuser"
	"server/internal/data/model/ent/predicate"
	"server/internal/data/model/ent/productionpackagingconfirmation"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductionPackagingConfirmationUpdate is the builder for updating ProductionPackagingConfirmation entities.
type ProductionPackagingConfirmationUpdate struct {
	config
	hooks    []Hook
	mutation *ProductionPackagingConfirmationMutation
}

// Where appends a list predicates to the ProductionPackagingConfirmationUpdate builder.
func (_u *ProductionPackagingConfirmationUpdate) Where(ps ...predicate.ProductionPackagingConfirmation) *ProductionPackagingConfirmationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProductionPackagingConfirmationUpdate) SetStatus(v string) *ProductionPackagingConfirmationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdate) SetNillableStatus(v *string) *ProductionPackagingConfirmationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ProductionPackagingConfirmationUpdate) SetVersion(v int) *ProductionPackagingConfirmationUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdate) SetNillableVersion(v *int) *ProductionPackagingConfirmationUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ProductionPackagingConfirmationUpdate) AddVersion(v int) *ProductionPackagingConfirmationUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetPackagingVersionSnapshot sets the "packaging_version_snapshot" field.
func (_u *ProductionPackagingConfirmationUpdate) SetPackagingVersionSnapshot(v string) *ProductionPackagingConfirmationUpdate {
	_u.mutation.SetPackagingVersionSnapshot(v)
	return _u
}

// SetNillablePackagingVersionSnapshot sets the "packaging_version_snapshot" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdate) SetNillablePackagingVersionSnapshot(v *string) *ProductionPackagingConfirmationUpdate {
	if v != nil {
		_u.SetPackagingVersionSnapshot(*v)
	}
	return _u
}

// ClearPackagingVersionSnapshot clears the value of the "packaging_version_snapshot" field.
func (_u *ProductionPackagingConfirmationUpdate) ClearPackagingVersionSnapshot() *ProductionPackagingConfirmationUpdate {
	_u.mutation.ClearPackagingVersionSnapshot()
	return _u
}

// SetConfirmedBy sets the "confirmed_by" field.
func (_u *ProductionPackagingConfirmationUpdate) SetConfirmedBy(v int) *ProductionPackagingConfirmationUpdate {
	_u.mutation.SetConfirmedBy(v)
	return _u
}

// SetNillableConfirmedBy sets the "confirmed_by" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdate) SetNillableConfirmedBy(v *int) *ProductionPackagingConfirmationUpdate {
	if v != nil {
		_u.SetConfirmedBy(*v)
	}
	return _u
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (_u *ProductionPackagingConfirmationUpdate) ClearConfirmedBy() *ProductionPackagingConfirmationUpdate {
	_u.mutation.ClearConfirmedBy()
	return _u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_u *ProductionPackagingConfirmationUpdate) SetConfirmedAt(v time.Time) *ProductionPackagingConfirmationUpdate {
	_u.mutation.SetConfirmedAt(v)
	return _u
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdate) SetNillableConfirmedAt(v *time.Time) *ProductionPackagingConfirmationUpdate {
	if v != nil {
		_u.SetConfirmedAt(*v)
	}
	return _u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (_u *ProductionPackagingConfirmationUpdate) ClearConfirmedAt() *ProductionPackagingConfirmationUpdate {
	_u.mutation.ClearConfirmedAt()
	return _u
}

// SetConfirmationIdempotencyKey sets the "confirmation_idempotency_key" field.
func (_u *ProductionPackagingConfirmationUpdate) SetConfirmationIdempotencyKey(v string) *ProductionPackagingConfirmationUpdate {
	_u.mutation.SetConfirmationIdempotencyKey(v)
	return _u
}

// SetNillableConfirmationIdempotencyKey sets the "confirmation_idempotency_key" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdate) SetNillableConfirmationIdempotencyKey(v *string) *ProductionPackagingConfirmationUpdate {
	if v != nil {
		_u.SetConfirmationIdempotencyKey(*v)
	}
	return _u
}

// ClearConfirmationIdempotencyKey clears the value of the "confirmation_idempotency_key" field.
func (_u *ProductionPackagingConfirmationUpdate) ClearConfirmationIdempotencyKey() *ProductionPackagingConfirmationUpdate {
	_u.mutation.ClearConfirmationIdempotencyKey()
	return _u
}

// SetConfirmationIntentHash sets the "confirmation_intent_hash" field.
func (_u *ProductionPackagingConfirmationUpdate) SetConfirmationIntentHash(v string) *ProductionPackagingConfirmationUpdate {
	_u.mutation.SetConfirmationIntentHash(v)
	return _u
}

// SetNillableConfirmationIntentHash sets the "confirmation_intent_hash" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdate) SetNillableConfirmationIntentHash(v *string) *ProductionPackagingConfirmationUpdate {
	if v != nil {
		_u.SetConfirmationIntentHash(*v)
	}
	return _u
}

// ClearConfirmationIntentHash clears the value of the "confirmation_intent_hash" field.
func (_u *ProductionPackagingConfirmationUpdate) ClearConfirmationIntentHash() *ProductionPackagingConfirmationUpdate {
	_u.mutation.ClearConfirmationIntentHash()
	return _u
}

// SetNote sets the "note" field.
func (_u *ProductionPackagingConfirmationUpdate) SetNote(v string) *ProductionPackagingConfirmationUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdate) SetNillableNote(v *string) *ProductionPackagingConfirmationUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *ProductionPackagingConfirmationUpdate) ClearNote() *ProductionPackagingConfirmationUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProductionPackagingConfirmationUpdate) SetUpdatedAt(v time.Time) *ProductionPackagingConfirmationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConfirmerID sets the "confirmer" edge to the AdminUser entity by ID.
func (_u *ProductionPackagingConfirmationUpdate) SetConfirmerID(id int) *ProductionPackagingConfirmationUpdate {
	_u.mutation.SetConfirmerID(id)
	return _u
}

// SetNillableConfirmerID sets the "confirmer" edge to the AdminUser entity by ID if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdate) SetNillableConfirmerID(id *int) *ProductionPackagingConfirmationUpdate {
	if id != nil {
		_u = _u.SetConfirmerID(*id)
	}
	return _u
}

// SetConfirmer sets the "confirmer" edge to the AdminUser entity.
func (_u *ProductionPackagingConfirmationUpdate) SetConfirmer(v *AdminUser) *ProductionPackagingConfirmationUpdate {
	return _u.SetConfirmerID(v.ID)
}

// Mutation returns the ProductionPackagingConfirmationMutation object of the builder.
func (_u *ProductionPackagingConfirmationUpdate) Mutation() *ProductionPackagingConfirmationMutation {
	return _u.mutation
}

// ClearConfirmer clears the "confirmer" edge to the AdminUser entity.
func (_u *ProductionPackagingConfirmationUpdate) ClearConfirmer() *ProductionPackagingConfirmationUpdate {
	_u.mutation.ClearConfirmer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductionPackagingConfirmationUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductionPackagingConfirmationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductionPackagingConfirmationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductionPackagingConfirmationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProductionPackagingConfirmationUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if productionpackagingconfirmation.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized productionpackagingconfirmation.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := productionpackagingconfirmation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductionPackagingConfirmationUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := productionpackagingconfirmation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProductionPackagingConfirmation.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := productionpackagingconfirmation.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProductionPackagingConfirmation.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PackagingVersionSnapshot(); ok {
		if err := productionpackagingconfirmation.PackagingVersionSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "packaging_version_snapshot", err: fmt.Errorf(`ent: validator failed for field "ProductionPackagingConfirmation.packaging_version_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfirmedBy(); ok {
		if err := productionpackagingconfirmation.ConfirmedByValidator(v); err != nil {
			return &ValidationError{Name: "confirmed_by", err: fmt.Errorf(`ent: validator failed for field "ProductionPackagingConfirmation.confirmed_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfirmationIdempotencyKey(); ok {
		if err := productionpackagingconfirmation.ConfirmationIdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "confirmation_idempotency_key", err: fmt.Errorf(`ent: validator failed for field "ProductionPackagingConfirmation.confirmation_idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfirmationIntentHash(); ok {
		if err := productionpackagingconfirmation.ConfirmationIntentHashValidator(v); err != nil {
			return &ValidationError{Name: "confirmation_intent_hash", err: fmt.Errorf(`ent: validator failed for field "ProductionPackagingConfirmation.confirmation_intent_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := productionpackagingconfirmation.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "ProductionPackagingConfirmation.note": %w`, err)}
		}
	}
	if _u.mutation.ProductionOrderCleared() && len(_u.mutation.ProductionOrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProductionPackagingConfirmation.production_order"`)
	}
	if _u.mutation.ProductionOrderItemCleared() && len(_u.mutation.ProductionOrderItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProductionPackagingConfirmation.production_order_item"`)
	}
	return nil
}

func (_u *ProductionPackagingConfirmationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productionpackagingconfirmation.Table, productionpackagingconfirmation.Columns, sqlgraph.NewFieldSpec(productionpackagingconfirmation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(productionpackagingconfirmation.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PackagingVersionSnapshot(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldPackagingVersionSnapshot, field.TypeString, value)
	}
	if _u.mutation.PackagingVersionSnapshotCleared() {
		_spec.ClearField(productionpackagingconfirmation.FieldPackagingVersionSnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.ConfirmedAt(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmedAtCleared() {
		_spec.ClearField(productionpackagingconfirmation.FieldConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConfirmationIdempotencyKey(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldConfirmationIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.ConfirmationIdempotencyKeyCleared() {
		_spec.ClearField(productionpackagingconfirmation.FieldConfirmationIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.ConfirmationIntentHash(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldConfirmationIntentHash, field.TypeString, value)
	}
	if _u.mutation.ConfirmationIntentHashCleared() {
		_spec.ClearField(productionpackagingconfirmation.FieldConfirmationIntentHash, field.TypeString)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(productionpackagingconfirmation.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   productionpackagingconfirmation.ConfirmerTable,
			Columns: []string{productionpackagingconfirmation.ConfirmerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfirmerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   productionpackagingconfirmation.ConfirmerTable,
			Columns: []string{productionpackagingconfirmation.ConfirmerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productionpackagingconfirmation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProductionPackagingConfirmationUpdateOne is the builder for updating a single ProductionPackagingConfirmation entity.
type ProductionPackagingConfirmationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductionPackagingConfirmationMutation
}

// SetStatus sets the "status" field.
func (_u *ProductionPackagingConfirmationUpdateOne) SetStatus(v string) *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdateOne) SetNillableStatus(v *string) *ProductionPackagingConfirmationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ProductionPackagingConfirmationUpdateOne) SetVersion(v int) *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdateOne) SetNillableVersion(v *int) *ProductionPackagingConfirmationUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ProductionPackagingConfirmationUpdateOne) AddVersion(v int) *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetPackagingVersionSnapshot sets the "packaging_version_snapshot" field.
func (_u *ProductionPackagingConfirmationUpdateOne) SetPackagingVersionSnapshot(v string) *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.SetPackagingVersionSnapshot(v)
	return _u
}

// SetNillablePackagingVersionSnapshot sets the "packaging_version_snapshot" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdateOne) SetNillablePackagingVersionSnapshot(v *string) *ProductionPackagingConfirmationUpdateOne {
	if v != nil {
		_u.SetPackagingVersionSnapshot(*v)
	}
	return _u
}

// ClearPackagingVersionSnapshot clears the value of the "packaging_version_snapshot" field.
func (_u *ProductionPackagingConfirmationUpdateOne) ClearPackagingVersionSnapshot() *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.ClearPackagingVersionSnapshot()
	return _u
}

// SetConfirmedBy sets the "confirmed_by" field.
func (_u *ProductionPackagingConfirmationUpdateOne) SetConfirmedBy(v int) *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.SetConfirmedBy(v)
	return _u
}

// SetNillableConfirmedBy sets the "confirmed_by" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdateOne) SetNillableConfirmedBy(v *int) *ProductionPackagingConfirmationUpdateOne {
	if v != nil {
		_u.SetConfirmedBy(*v)
	}
	return _u
}

// ClearConfirmedBy clears the value of the "confirmed_by" field.
func (_u *ProductionPackagingConfirmationUpdateOne) ClearConfirmedBy() *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.ClearConfirmedBy()
	return _u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_u *ProductionPackagingConfirmationUpdateOne) SetConfirmedAt(v time.Time) *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.SetConfirmedAt(v)
	return _u
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdateOne) SetNillableConfirmedAt(v *time.Time) *ProductionPackagingConfirmationUpdateOne {
	if v != nil {
		_u.SetConfirmedAt(*v)
	}
	return _u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (_u *ProductionPackagingConfirmationUpdateOne) ClearConfirmedAt() *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.ClearConfirmedAt()
	return _u
}

// SetConfirmationIdempotencyKey sets the "confirmation_idempotency_key" field.
func (_u *ProductionPackagingConfirmationUpdateOne) SetConfirmationIdempotencyKey(v string) *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.SetConfirmationIdempotencyKey(v)
	return _u
}

// SetNillableConfirmationIdempotencyKey sets the "confirmation_idempotency_key" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdateOne) SetNillableConfirmationIdempotencyKey(v *string) *ProductionPackagingConfirmationUpdateOne {
	if v != nil {
		_u.SetConfirmationIdempotencyKey(*v)
	}
	return _u
}

// ClearConfirmationIdempotencyKey clears the value of the "confirmation_idempotency_key" field.
func (_u *ProductionPackagingConfirmationUpdateOne) ClearConfirmationIdempotencyKey() *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.ClearConfirmationIdempotencyKey()
	return _u
}

// SetConfirmationIntentHash sets the "confirmation_intent_hash" field.
func (_u *ProductionPackagingConfirmationUpdateOne) SetConfirmationIntentHash(v string) *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.SetConfirmationIntentHash(v)
	return _u
}

// SetNillableConfirmationIntentHash sets the "confirmation_intent_hash" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdateOne) SetNillableConfirmationIntentHash(v *string) *ProductionPackagingConfirmationUpdateOne {
	if v != nil {
		_u.SetConfirmationIntentHash(*v)
	}
	return _u
}

// ClearConfirmationIntentHash clears the value of the "confirmation_intent_hash" field.
func (_u *ProductionPackagingConfirmationUpdateOne) ClearConfirmationIntentHash() *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.ClearConfirmationIntentHash()
	return _u
}

// SetNote sets the "note" field.
func (_u *ProductionPackagingConfirmationUpdateOne) SetNote(v string) *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdateOne) SetNillableNote(v *string) *ProductionPackagingConfirmationUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *ProductionPackagingConfirmationUpdateOne) ClearNote() *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProductionPackagingConfirmationUpdateOne) SetUpdatedAt(v time.Time) *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConfirmerID sets the "confirmer" edge to the AdminUser entity by ID.
func (_u *ProductionPackagingConfirmationUpdateOne) SetConfirmerID(id int) *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.SetConfirmerID(id)
	return _u
}

// SetNillableConfirmerID sets the "confirmer" edge to the AdminUser entity by ID if the given value is not nil.
func (_u *ProductionPackagingConfirmationUpdateOne) SetNillableConfirmerID(id *int) *ProductionPackagingConfirmationUpdateOne {
	if id != nil {
		_u = _u.SetConfirmerID(*id)
	}
	return _u
}

// SetConfirmer sets the "confirmer" edge to the AdminUser entity.
func (_u *ProductionPackagingConfirmationUpdateOne) SetConfirmer(v *AdminUser) *ProductionPackagingConfirmationUpdateOne {
	return _u.SetConfirmerID(v.ID)
}

// Mutation returns the ProductionPackagingConfirmationMutation object of the builder.
func (_u *ProductionPackagingConfirmationUpdateOne) Mutation() *ProductionPackagingConfirmationMutation {
	return _u.mutation
}

// ClearConfirmer clears the "confirmer" edge to the AdminUser entity.
func (_u *ProductionPackagingConfirmationUpdateOne) ClearConfirmer() *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.ClearConfirmer()
	return _u
}

// Where appends a list predicates to the ProductionPackagingConfirmationUpdate builder.
func (_u *ProductionPackagingConfirmationUpdateOne) Where(ps ...predicate.ProductionPackagingConfirmation) *ProductionPackagingConfirmationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProductionPackagingConfirmationUpdateOne) Select(field string, fields ...string) *ProductionPackagingConfirmationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProductionPackagingConfirmation entity.
func (_u *ProductionPackagingConfirmationUpdateOne) Save(ctx context.Context) (*ProductionPackagingConfirmation, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductionPackagingConfirmationUpdateOne) SaveX(ctx context.Context) *ProductionPackagingConfirmation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductionPackagingConfirmationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductionPackagingConfirmationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProductionPackagingConfirmationUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if productionpackagingconfirmation.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized productionpackagingconfirmation.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := productionpackagingconfirmation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductionPackagingConfirmationUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := productionpackagingconfirmation.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProductionPackagingConfirmation.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := productionpackagingconfirmation.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ProductionPackagingConfirmation.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PackagingVersionSnapshot(); ok {
		if err := productionpackagingconfirmation.PackagingVersionSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "packaging_version_snapshot", err: fmt.Errorf(`ent: validator failed for field "ProductionPackagingConfirmation.packaging_version_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfirmedBy(); ok {
		if err := productionpackagingconfirmation.ConfirmedByValidator(v); err != nil {
			return &ValidationError{Name: "confirmed_by", err: fmt.Errorf(`ent: validator failed for field "ProductionPackagingConfirmation.confirmed_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfirmationIdempotencyKey(); ok {
		if err := productionpackagingconfirmation.ConfirmationIdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "confirmation_idempotency_key", err: fmt.Errorf(`ent: validator failed for field "ProductionPackagingConfirmation.confirmation_idempotency_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfirmationIntentHash(); ok {
		if err := productionpackagingconfirmation.ConfirmationIntentHashValidator(v); err != nil {
			return &ValidationError{Name: "confirmation_intent_hash", err: fmt.Errorf(`ent: validator failed for field "ProductionPackagingConfirmation.confirmation_intent_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := productionpackagingconfirmation.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "ProductionPackagingConfirmation.note": %w`, err)}
		}
	}
	if _u.mutation.ProductionOrderCleared() && len(_u.mutation.ProductionOrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProductionPackagingConfirmation.production_order"`)
	}
	if _u.mutation.ProductionOrderItemCleared() && len(_u.mutation.ProductionOrderItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProductionPackagingConfirmation.production_order_item"`)
	}
	return nil
}

func (_u *ProductionPackagingConfirmationUpdateOne) sqlSave(ctx context.Context) (_node *ProductionPackagingConfirmation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productionpackagingconfirmation.Table, productionpackagingconfirmation.Columns, sqlgraph.NewFieldSpec(productionpackagingconfirmation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProductionPackagingConfirmation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productionpackagingconfirmation.FieldID)
		for _, f := range fields {
			if !productionpackagingconfirmation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != productionpackagingconfirmation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(productionpackagingconfirmation.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PackagingVersionSnapshot(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldPackagingVersionSnapshot, field.TypeString, value)
	}
	if _u.mutation.PackagingVersionSnapshotCleared() {
		_spec.ClearField(productionpackagingconfirmation.FieldPackagingVersionSnapshot, field.TypeString)
	}
	if value, ok := _u.mutation.ConfirmedAt(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmedAtCleared() {
		_spec.ClearField(productionpackagingconfirmation.FieldConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConfirmationIdempotencyKey(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldConfirmationIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.ConfirmationIdempotencyKeyCleared() {
		_spec.ClearField(productionpackagingconfirmation.FieldConfirmationIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.ConfirmationIntentHash(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldConfirmationIntentHash, field.TypeString, value)
	}
	if _u.mutation.ConfirmationIntentHashCleared() {
		_spec.ClearField(productionpackagingconfirmation.FieldConfirmationIntentHash, field.TypeString)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(productionpackagingconfirmation.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(productionpackagingconfirmation.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   productionpackagingconfirmation.ConfirmerTable,
			Columns: []string{productionpackagingconfirmation.ConfirmerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfirmerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   productionpackagingconfirmation.ConfirmerTable,
			Columns: []string{productionpackagingconfirmation.ConfirmerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProductionPackagingConfirmation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productionpackagingconfirmation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
