// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"server/internal/data/model/ent/inventorylot"
	"server/internal/data/model/ent/material"
	"server/internal/data/model/ent/predicate"
	"server/internal/data/model/ent/purchasereceiptitem"
	"server/internal/data/model/ent/purchasereturn"
	"server/internal/data/model/ent/purchasereturnitem"
	"server/internal/data/model/ent/unit"
	"server/internal/data/model/ent/warehouse"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PurchaseReturnItemQuery is the builder for querying PurchaseReturnItem entities.
type PurchaseReturnItemQuery struct {
	config
	ctx                     *QueryContext
	order                   []purchasereturnitem.OrderOption
	inters                  []Interceptor
	predicates              []predicate.PurchaseReturnItem
	withPurchaseReturn      *PurchaseReturnQuery
	withPurchaseReceiptItem *PurchaseReceiptItemQuery
	withMaterial            *MaterialQuery
	withWarehouse           *WarehouseQuery
	withUnit                *UnitQuery
	withInventoryLot        *InventoryLotQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PurchaseReturnItemQuery builder.
func (_q *PurchaseReturnItemQuery) Where(ps ...predicate.PurchaseReturnItem) *PurchaseReturnItemQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PurchaseReturnItemQuery) Limit(limit int) *PurchaseReturnItemQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PurchaseReturnItemQuery) Offset(offset int) *PurchaseReturnItemQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PurchaseReturnItemQuery) Unique(unique bool) *PurchaseReturnItemQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PurchaseReturnItemQuery) Order(o ...purchasereturnitem.OrderOption) *PurchaseReturnItemQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPurchaseReturn chains the current query on the "purchase_return" edge.
func (_q *PurchaseReturnItemQuery) QueryPurchaseReturn() *PurchaseReturnQuery {
	query := (&PurchaseReturnClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(purchasereturnitem.Table, purchasereturnitem.FieldID, selector),
			sqlgraph.To(purchasereturn.Table, purchasereturn.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, purchasereturnitem.PurchaseReturnTable, purchasereturnitem.PurchaseReturnColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPurchaseReceiptItem chains the current query on the "purchase_receipt_item" edge.
func (_q *PurchaseReturnItemQuery) QueryPurchaseReceiptItem() *PurchaseReceiptItemQuery {
	query := (&PurchaseReceiptItemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(purchasereturnitem.Table, purchasereturnitem.FieldID, selector),
			sqlgraph.To(purchasereceiptitem.Table, purchasereceiptitem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, purchasereturnitem.PurchaseReceiptItemTable, purchasereturnitem.PurchaseReceiptItemColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMaterial chains the current query on the "material" edge.
func (_q *PurchaseReturnItemQuery) QueryMaterial() *MaterialQuery {
	query := (&MaterialClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(purchasereturnitem.Table, purchasereturnitem.FieldID, selector),
			sqlgraph.To(material.Table, material.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, purchasereturnitem.MaterialTable, purchasereturnitem.MaterialColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWarehouse chains the current query on the "warehouse" edge.
func (_q *PurchaseReturnItemQuery) QueryWarehouse() *WarehouseQuery {
	query := (&WarehouseClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(purchasereturnitem.Table, purchasereturnitem.FieldID, selector),
			sqlgraph.To(warehouse.Table, warehouse.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, purchasereturnitem.WarehouseTable, purchasereturnitem.WarehouseColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUnit chains the current query on the "unit" edge.
func (_q *PurchaseReturnItemQuery) QueryUnit() *UnitQuery {
	query := (&UnitClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(purchasereturnitem.Table, purchasereturnitem.FieldID, selector),
			sqlgraph.To(unit.Table, unit.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, purchasereturnitem.UnitTable, purchasereturnitem.UnitColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryInventoryLot chains the current query on the "inventory_lot" edge.
func (_q *PurchaseReturnItemQuery) QueryInventoryLot() *InventoryLotQuery {
	query := (&InventoryLotClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(purchasereturnitem.Table, purchasereturnitem.FieldID, selector),
			sqlgraph.To(inventorylot.Table, inventorylot.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, purchasereturnitem.InventoryLotTable, purchasereturnitem.InventoryLotColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PurchaseReturnItem entity from the query.
// Returns a *NotFoundError when no PurchaseReturnItem was found.
func (_q *PurchaseReturnItemQuery) First(ctx context.Context) (*PurchaseReturnItem, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{purchasereturnitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PurchaseReturnItemQuery) FirstX(ctx context.Context) *PurchaseReturnItem {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PurchaseReturnItem ID from the query.
// Returns a *NotFoundError when no PurchaseReturnItem ID was found.
func (_q *PurchaseReturnItemQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{purchasereturnitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PurchaseReturnItemQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PurchaseReturnItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PurchaseReturnItem entity is found.
// Returns a *NotFoundError when no PurchaseReturnItem entities are found.
func (_q *PurchaseReturnItemQuery) Only(ctx context.Context) (*PurchaseReturnItem, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{purchasereturnitem.Label}
	default:
		return nil, &NotSingularError{purchasereturnitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PurchaseReturnItemQuery) OnlyX(ctx context.Context) *PurchaseReturnItem {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PurchaseReturnItem ID in the query.
// Returns a *NotSingularError when more than one PurchaseReturnItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PurchaseReturnItemQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{purchasereturnitem.Label}
	default:
		err = &NotSingularError{purchasereturnitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PurchaseReturnItemQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PurchaseReturnItems.
func (_q *PurchaseReturnItemQuery) All(ctx context.Context) ([]*PurchaseReturnItem, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PurchaseReturnItem, *PurchaseReturnItemQuery]()
	return withInterceptors[[]*PurchaseReturnItem](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PurchaseReturnItemQuery) AllX(ctx context.Context) []*PurchaseReturnItem {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PurchaseReturnItem IDs.
func (_q *PurchaseReturnItemQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(purchasereturnitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PurchaseReturnItemQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PurchaseReturnItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PurchaseReturnItemQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PurchaseReturnItemQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PurchaseReturnItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PurchaseReturnItemQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PurchaseReturnItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PurchaseReturnItemQuery) Clone() *PurchaseReturnItemQuery {
	if _q == nil {
		return nil
	}
	return &PurchaseReturnItemQuery{
		config:                  _q.config,
		ctx:                     _q.ctx.Clone(),
		order:                   append([]purchasereturnitem.OrderOption{}, _q.order...),
		inters:                  append([]Interceptor{}, _q.inters...),
		predicates:              append([]predicate.PurchaseReturnItem{}, _q.predicates...),
		withPurchaseReturn:      _q.withPurchaseReturn.Clone(),
		withPurchaseReceiptItem: _q.withPurchaseReceiptItem.Clone(),
		withMaterial:            _q.withMaterial.Clone(),
		withWarehouse:           _q.withWarehouse.Clone(),
		withUnit:                _q.withUnit.Clone(),
		withInventoryLot:        _q.withInventoryLot.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPurchaseReturn tells the query-builder to eager-load the nodes that are connected to
// the "purchase_return" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PurchaseReturnItemQuery) WithPurchaseReturn(opts ...func(*PurchaseReturnQuery)) *PurchaseReturnItemQuery {
	query := (&PurchaseReturnClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPurchaseReturn = query
	return _q
}

// WithPurchaseReceiptItem tells the query-builder to eager-load the nodes that are connected to
// the "purchase_receipt_item" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PurchaseReturnItemQuery) WithPurchaseReceiptItem(opts ...func(*PurchaseReceiptItemQuery)) *PurchaseReturnItemQuery {
	query := (&PurchaseReceiptItemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPurchaseReceiptItem = query
	return _q
}

// WithMaterial tells the query-builder to eager-load the nodes that are connected to
// the "material" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PurchaseReturnItemQuery) WithMaterial(opts ...func(*MaterialQuery)) *PurchaseReturnItemQuery {
	query := (&MaterialClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMaterial = query
	return _q
}

// WithWarehouse tells the query-builder to eager-load the nodes that are connected to
// the "warehouse" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PurchaseReturnItemQuery) WithWarehouse(opts ...func(*WarehouseQuery)) *PurchaseReturnItemQuery {
	query := (&WarehouseClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWarehouse = query
	return _q
}

// WithUnit tells the query-builder to eager-load the nodes that are connected to
// the "unit" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PurchaseReturnItemQuery) WithUnit(opts ...func(*UnitQuery)) *PurchaseReturnItemQuery {
	query := (&UnitClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUnit = query
	return _q
}

// WithInventoryLot tells the query-builder to eager-load the nodes that are connected to
// the "inventory_lot" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PurchaseReturnItemQuery) WithInventoryLot(opts ...func(*InventoryLotQuery)) *PurchaseReturnItemQuery {
	query := (&InventoryLotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInventoryLot = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ReturnID int `json:"return_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PurchaseReturnItem.Query().
//		GroupBy(purchasereturnitem.FieldReturnID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PurchaseReturnItemQuery) GroupBy(field string, fields ...string) *PurchaseReturnItemGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PurchaseReturnItemGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = purchasereturnitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ReturnID int `json:"return_id,omitempty"`
//	}
//
//	client.PurchaseReturnItem.Query().
//		Select(purchasereturnitem.FieldReturnID).
//		Scan(ctx, &v)
func (_q *PurchaseReturnItemQuery) Select(fields ...string) *PurchaseReturnItemSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PurchaseReturnItemSelect{PurchaseReturnItemQuery: _q}
	sbuild.label = purchasereturnitem.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PurchaseReturnItemSelect configured with the given aggregations.
func (_q *PurchaseReturnItemQuery) Aggregate(fns ...AggregateFunc) *PurchaseReturnItemSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PurchaseReturnItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !purchasereturnitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PurchaseReturnItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PurchaseReturnItem, error) {
	var (
		nodes       = []*PurchaseReturnItem{}
		_spec       = _q.querySpec()
		loadedTypes = [6]bool{
			_q.withPurchaseReturn != nil,
			_q.withPurchaseReceiptItem != nil,
			_q.withMaterial != nil,
			_q.withWarehouse != nil,
			_q.withUnit != nil,
			_q.withInventoryLot != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PurchaseReturnItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PurchaseReturnItem{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPurchaseReturn; query != nil {
		if err := _q.loadPurchaseReturn(ctx, query, nodes, nil,
			func(n *PurchaseReturnItem, e *PurchaseReturn) { n.Edges.PurchaseReturn = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPurchaseReceiptItem; query != nil {
		if err := _q.loadPurchaseReceiptItem(ctx, query, nodes, nil,
			func(n *PurchaseReturnItem, e *PurchaseReceiptItem) { n.Edges.PurchaseReceiptItem = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMaterial; query != nil {
		if err := _q.loadMaterial(ctx, query, nodes, nil,
			func(n *PurchaseReturnItem, e *Material) { n.Edges.Material = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWarehouse; query != nil {
		if err := _q.loadWarehouse(ctx, query, nodes, nil,
			func(n *PurchaseReturnItem, e *Warehouse) { n.Edges.Warehouse = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUnit; query != nil {
		if err := _q.loadUnit(ctx, query, nodes, nil,
			func(n *PurchaseReturnItem, e *Unit) { n.Edges.Unit = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withInventoryLot; query != nil {
		if err := _q.loadInventoryLot(ctx, query, nodes, nil,
			func(n *PurchaseReturnItem, e *InventoryLot) { n.Edges.InventoryLot = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PurchaseReturnItemQuery) loadPurchaseReturn(ctx context.Context, query *PurchaseReturnQuery, nodes []*PurchaseReturnItem, init func(*PurchaseReturnItem), assign func(*PurchaseReturnItem, *PurchaseReturn)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PurchaseReturnItem)
	for i := range nodes {
		fk := nodes[i].ReturnID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(purchasereturn.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "return_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PurchaseReturnItemQuery) loadPurchaseReceiptItem(ctx context.Context, query *PurchaseReceiptItemQuery, nodes []*PurchaseReturnItem, init func(*PurchaseReturnItem), assign func(*PurchaseReturnItem, *PurchaseReceiptItem)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PurchaseReturnItem)
	for i := range nodes {
		if nodes[i].PurchaseReceiptItemID == nil {
			continue
		}
		fk := *nodes[i].PurchaseReceiptItemID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(purchasereceiptitem.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "purchase_receipt_item_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PurchaseReturnItemQuery) loadMaterial(ctx context.Context, query *MaterialQuery, nodes []*PurchaseReturnItem, init func(*PurchaseReturnItem), assign func(*PurchaseReturnItem, *Material)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PurchaseReturnItem)
	for i := range nodes {
		fk := nodes[i].MaterialID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(material.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "material_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PurchaseReturnItemQuery) loadWarehouse(ctx context.Context, query *WarehouseQuery, nodes []*PurchaseReturnItem, init func(*PurchaseReturnItem), assign func(*PurchaseReturnItem, *Warehouse)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PurchaseReturnItem)
	for i := range nodes {
		fk := nodes[i].WarehouseID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(warehouse.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "warehouse_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PurchaseReturnItemQuery) loadUnit(ctx context.Context, query *UnitQuery, nodes []*PurchaseReturnItem, init func(*PurchaseReturnItem), assign func(*PurchaseReturnItem, *Unit)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PurchaseReturnItem)
	for i := range nodes {
		fk := nodes[i].UnitID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(unit.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "unit_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PurchaseReturnItemQuery) loadInventoryLot(ctx context.Context, query *InventoryLotQuery, nodes []*PurchaseReturnItem, init func(*PurchaseReturnItem), assign func(*PurchaseReturnItem, *InventoryLot)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*PurchaseReturnItem)
	for i := range nodes {
		if nodes[i].LotID == nil {
			continue
		}
		fk := *nodes[i].LotID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(inventorylot.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "lot_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PurchaseReturnItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PurchaseReturnItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(purchasereturnitem.Table, purchasereturnitem.Columns, sqlgraph.NewFieldSpec(purchasereturnitem.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, purchasereturnitem.FieldID)
		for i := range fields {
			if fields[i] != purchasereturnitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withPurchaseReturn != nil {
			_spec.Node.AddColumnOnce(purchasereturnitem.FieldReturnID)
		}
		if _q.withPurchaseReceiptItem != nil {
			_spec.Node.AddColumnOnce(purchasereturnitem.FieldPurchaseReceiptItemID)
		}
		if _q.withMaterial != nil {
			_spec.Node.AddColumnOnce(purchasereturnitem.FieldMaterialID)
		}
		if _q.withWarehouse != nil {
			_spec.Node.AddColumnOnce(purchasereturnitem.FieldWarehouseID)
		}
		if _q.withUnit != nil {
			_spec.Node.AddColumnOnce(purchasereturnitem.FieldUnitID)
		}
		if _q.withInventoryLot != nil {
			_spec.Node.AddColumnOnce(purchasereturnitem.FieldLotID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PurchaseReturnItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(purchasereturnitem.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = purchasereturnitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PurchaseReturnItemGroupBy is the group-by builder for PurchaseReturnItem entities.
type PurchaseReturnItemGroupBy struct {
	selector
	build *PurchaseReturnItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PurchaseReturnItemGroupBy) Aggregate(fns ...AggregateFunc) *PurchaseReturnItemGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PurchaseReturnItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PurchaseReturnItemQuery, *PurchaseReturnItemGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PurchaseReturnItemGroupBy) sqlScan(ctx context.Context, root *PurchaseReturnItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PurchaseReturnItemSelect is the builder for selecting fields of PurchaseReturnItem entities.
type PurchaseReturnItemSelect struct {
	*PurchaseReturnItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PurchaseReturnItemSelect) Aggregate(fns ...AggregateFunc) *PurchaseReturnItemSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PurchaseReturnItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PurchaseReturnItemQuery, *PurchaseReturnItemSelect](ctx, _s.PurchaseReturnItemQuery, _s, _s.inters, v)
}

func (_s *PurchaseReturnItemSelect) sqlScan(ctx context.Context, root *PurchaseReturnItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
