// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"server/internal/data/model/ent/purchaseorder"
	"server/internal/data/model/ent/supplier"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PurchaseOrder is the model entity for the PurchaseOrder schema.
type PurchaseOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PurchaseOrderNo holds the value of the "purchase_order_no" field.
	PurchaseOrderNo string `json:"purchase_order_no,omitempty"`
	// SupplierID holds the value of the "supplier_id" field.
	SupplierID int `json:"supplier_id,omitempty"`
	// SupplierPurchaseOrderNo holds the value of the "supplier_purchase_order_no" field.
	SupplierPurchaseOrderNo *string `json:"supplier_purchase_order_no,omitempty"`
	// SupplierSnapshot holds the value of the "supplier_snapshot" field.
	SupplierSnapshot map[string]interface{} `json:"supplier_snapshot,omitempty"`
	// ContractPartySnapshot holds the value of the "contract_party_snapshot" field.
	ContractPartySnapshot map[string]interface{} `json:"contract_party_snapshot,omitempty"`
	// PurchaseDate holds the value of the "purchase_date" field.
	PurchaseDate time.Time `json:"purchase_date,omitempty"`
	// ExpectedArrivalDate holds the value of the "expected_arrival_date" field.
	ExpectedArrivalDate *time.Time `json:"expected_arrival_date,omitempty"`
	// LifecycleStatus holds the value of the "lifecycle_status" field.
	LifecycleStatus string `json:"lifecycle_status,omitempty"`
	// Note holds the value of the "note" field.
	Note *string `json:"note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PurchaseOrderQuery when eager-loading is set.
	Edges        PurchaseOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PurchaseOrderEdges holds the relations/edges for other nodes in the graph.
type PurchaseOrderEdges struct {
	// Supplier holds the value of the supplier edge.
	Supplier *Supplier `json:"supplier,omitempty"`
	// Items holds the value of the items edge.
	Items []*PurchaseOrderItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SupplierOrErr returns the Supplier value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PurchaseOrderEdges) SupplierOrErr() (*Supplier, error) {
	if e.Supplier != nil {
		return e.Supplier, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: supplier.Label}
	}
	return nil, &NotLoadedError{edge: "supplier"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e PurchaseOrderEdges) ItemsOrErr() ([]*PurchaseOrderItem, error) {
	if e.loadedTypes[1] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PurchaseOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case purchaseorder.FieldSupplierSnapshot, purchaseorder.FieldContractPartySnapshot:
			values[i] = new([]byte)
		case purchaseorder.FieldID, purchaseorder.FieldSupplierID:
			values[i] = new(sql.NullInt64)
		case purchaseorder.FieldPurchaseOrderNo, purchaseorder.FieldSupplierPurchaseOrderNo, purchaseorder.FieldLifecycleStatus, purchaseorder.FieldNote:
			values[i] = new(sql.NullString)
		case purchaseorder.FieldPurchaseDate, purchaseorder.FieldExpectedArrivalDate, purchaseorder.FieldCreatedAt, purchaseorder.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PurchaseOrder fields.
func (_m *PurchaseOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case purchaseorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case purchaseorder.FieldPurchaseOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_order_no", values[i])
			} else if value.Valid {
				_m.PurchaseOrderNo = value.String
			}
		case purchaseorder.FieldSupplierID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field supplier_id", values[i])
			} else if value.Valid {
				_m.SupplierID = int(value.Int64)
			}
		case purchaseorder.FieldSupplierPurchaseOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field supplier_purchase_order_no", values[i])
			} else if value.Valid {
				_m.SupplierPurchaseOrderNo = new(string)
				*_m.SupplierPurchaseOrderNo = value.String
			}
		case purchaseorder.FieldSupplierSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field supplier_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SupplierSnapshot); err != nil {
					return fmt.Errorf("unmarshal field supplier_snapshot: %w", err)
				}
			}
		case purchaseorder.FieldContractPartySnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field contract_party_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ContractPartySnapshot); err != nil {
					return fmt.Errorf("unmarshal field contract_party_snapshot: %w", err)
				}
			}
		case purchaseorder.FieldPurchaseDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_date", values[i])
			} else if value.Valid {
				_m.PurchaseDate = value.Time
			}
		case purchaseorder.FieldExpectedArrivalDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expected_arrival_date", values[i])
			} else if value.Valid {
				_m.ExpectedArrivalDate = new(time.Time)
				*_m.ExpectedArrivalDate = value.Time
			}
		case purchaseorder.FieldLifecycleStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lifecycle_status", values[i])
			} else if value.Valid {
				_m.LifecycleStatus = value.String
			}
		case purchaseorder.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = new(string)
				*_m.Note = value.String
			}
		case purchaseorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case purchaseorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PurchaseOrder.
// This includes values selected through modifiers, order, etc.
func (_m *PurchaseOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySupplier queries the "supplier" edge of the PurchaseOrder entity.
func (_m *PurchaseOrder) QuerySupplier() *SupplierQuery {
	return NewPurchaseOrderClient(_m.config).QuerySupplier(_m)
}

// QueryItems queries the "items" edge of the PurchaseOrder entity.
func (_m *PurchaseOrder) QueryItems() *PurchaseOrderItemQuery {
	return NewPurchaseOrderClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this PurchaseOrder.
// Note that you need to call PurchaseOrder.Unwrap() before calling this method if this PurchaseOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PurchaseOrder) Update() *PurchaseOrderUpdateOne {
	return NewPurchaseOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PurchaseOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PurchaseOrder) Unwrap() *PurchaseOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PurchaseOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PurchaseOrder) String() string {
	var builder strings.Builder
	builder.WriteString("PurchaseOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("purchase_order_no=")
	builder.WriteString(_m.PurchaseOrderNo)
	builder.WriteString(", ")
	builder.WriteString("supplier_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupplierID))
	builder.WriteString(", ")
	if v := _m.SupplierPurchaseOrderNo; v != nil {
		builder.WriteString("supplier_purchase_order_no=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("supplier_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.SupplierSnapshot))
	builder.WriteString(", ")
	builder.WriteString("contract_party_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContractPartySnapshot))
	builder.WriteString(", ")
	builder.WriteString("purchase_date=")
	builder.WriteString(_m.PurchaseDate.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ExpectedArrivalDate; v != nil {
		builder.WriteString("expected_arrival_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("lifecycle_status=")
	builder.WriteString(_m.LifecycleStatus)
	builder.WriteString(", ")
	if v := _m.Note; v != nil {
		builder.WriteString("note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PurchaseOrders is a parsable slice of PurchaseOrder.
type PurchaseOrders []*PurchaseOrder
