// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/purchasereceipt"
	"server/internal/data/model/ent/purchaserejectiondisposition"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
)

// PurchaseRejectionDispositionCreate is the builder for creating a PurchaseRejectionDisposition entity.
type PurchaseRejectionDispositionCreate struct {
	config
	mutation *PurchaseRejectionDispositionMutation
	hooks    []Hook
}

// SetDispositionNo sets the "disposition_no" field.
func (_c *PurchaseRejectionDispositionCreate) SetDispositionNo(v string) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetDispositionNo(v)
	return _c
}

// SetQualityInspectionID sets the "quality_inspection_id" field.
func (_c *PurchaseRejectionDispositionCreate) SetQualityInspectionID(v int) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetQualityInspectionID(v)
	return _c
}

// SetPurchaseReceiptID sets the "purchase_receipt_id" field.
func (_c *PurchaseRejectionDispositionCreate) SetPurchaseReceiptID(v int) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetPurchaseReceiptID(v)
	return _c
}

// SetPurchaseReceiptItemID sets the "purchase_receipt_item_id" field.
func (_c *PurchaseRejectionDispositionCreate) SetPurchaseReceiptItemID(v int) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetPurchaseReceiptItemID(v)
	return _c
}

// SetReplacementReceiptID sets the "replacement_receipt_id" field.
func (_c *PurchaseRejectionDispositionCreate) SetReplacementReceiptID(v int) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetReplacementReceiptID(v)
	return _c
}

// SetNillableReplacementReceiptID sets the "replacement_receipt_id" field if the given value is not nil.
func (_c *PurchaseRejectionDispositionCreate) SetNillableReplacementReceiptID(v *int) *PurchaseRejectionDispositionCreate {
	if v != nil {
		_c.SetReplacementReceiptID(*v)
	}
	return _c
}

// SetDispositionType sets the "disposition_type" field.
func (_c *PurchaseRejectionDispositionCreate) SetDispositionType(v string) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetDispositionType(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PurchaseRejectionDispositionCreate) SetStatus(v string) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PurchaseRejectionDispositionCreate) SetNillableStatus(v *string) *PurchaseRejectionDispositionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *PurchaseRejectionDispositionCreate) SetQuantity(v decimal.Decimal) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetSupplierID sets the "supplier_id" field.
func (_c *PurchaseRejectionDispositionCreate) SetSupplierID(v int) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetSupplierID(v)
	return _c
}

// SetNillableSupplierID sets the "supplier_id" field if the given value is not nil.
func (_c *PurchaseRejectionDispositionCreate) SetNillableSupplierID(v *int) *PurchaseRejectionDispositionCreate {
	if v != nil {
		_c.SetSupplierID(*v)
	}
	return _c
}

// SetSupplierName sets the "supplier_name" field.
func (_c *PurchaseRejectionDispositionCreate) SetSupplierName(v string) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetSupplierName(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *PurchaseRejectionDispositionCreate) SetReason(v string) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *PurchaseRejectionDispositionCreate) SetIdempotencyKey(v string) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetIdempotencyPayloadHash sets the "idempotency_payload_hash" field.
func (_c *PurchaseRejectionDispositionCreate) SetIdempotencyPayloadHash(v string) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetIdempotencyPayloadHash(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *PurchaseRejectionDispositionCreate) SetVersion(v int) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *PurchaseRejectionDispositionCreate) SetNillableVersion(v *int) *PurchaseRejectionDispositionCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetPostedAt sets the "posted_at" field.
func (_c *PurchaseRejectionDispositionCreate) SetPostedAt(v time.Time) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetPostedAt(v)
	return _c
}

// SetNillablePostedAt sets the "posted_at" field if the given value is not nil.
func (_c *PurchaseRejectionDispositionCreate) SetNillablePostedAt(v *time.Time) *PurchaseRejectionDispositionCreate {
	if v != nil {
		_c.SetPostedAt(*v)
	}
	return _c
}

// SetPostedBy sets the "posted_by" field.
func (_c *PurchaseRejectionDispositionCreate) SetPostedBy(v int) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetPostedBy(v)
	return _c
}

// SetNillablePostedBy sets the "posted_by" field if the given value is not nil.
func (_c *PurchaseRejectionDispositionCreate) SetNillablePostedBy(v *int) *PurchaseRejectionDispositionCreate {
	if v != nil {
		_c.SetPostedBy(*v)
	}
	return _c
}

// SetCancelledAt sets the "cancelled_at" field.
func (_c *PurchaseRejectionDispositionCreate) SetCancelledAt(v time.Time) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetCancelledAt(v)
	return _c
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_c *PurchaseRejectionDispositionCreate) SetNillableCancelledAt(v *time.Time) *PurchaseRejectionDispositionCreate {
	if v != nil {
		_c.SetCancelledAt(*v)
	}
	return _c
}

// SetCancelledBy sets the "cancelled_by" field.
func (_c *PurchaseRejectionDispositionCreate) SetCancelledBy(v int) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetCancelledBy(v)
	return _c
}

// SetNillableCancelledBy sets the "cancelled_by" field if the given value is not nil.
func (_c *PurchaseRejectionDispositionCreate) SetNillableCancelledBy(v *int) *PurchaseRejectionDispositionCreate {
	if v != nil {
		_c.SetCancelledBy(*v)
	}
	return _c
}

// SetCancelReason sets the "cancel_reason" field.
func (_c *PurchaseRejectionDispositionCreate) SetCancelReason(v string) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetCancelReason(v)
	return _c
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_c *PurchaseRejectionDispositionCreate) SetNillableCancelReason(v *string) *PurchaseRejectionDispositionCreate {
	if v != nil {
		_c.SetCancelReason(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *PurchaseRejectionDispositionCreate) SetCreatedBy(v int) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PurchaseRejectionDispositionCreate) SetCreatedAt(v time.Time) *PurchaseRejectionDispositionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PurchaseRejectionDispositionCreate) SetNillableCreatedAt(v *time.Time) *PurchaseRejectionDispositionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetReplacementReceipt sets the "replacement_receipt" edge to the PurchaseReceipt entity.
func (_c *PurchaseRejectionDispositionCreate) SetReplacementReceipt(v *PurchaseReceipt) *PurchaseRejectionDispositionCreate {
	return _c.SetReplacementReceiptID(v.ID)
}

// Mutation returns the PurchaseRejectionDispositionMutation object of the builder.
func (_c *PurchaseRejectionDispositionCreate) Mutation() *PurchaseRejectionDispositionMutation {
	return _c.mutation
}

// Save creates the PurchaseRejectionDisposition in the database.
func (_c *PurchaseRejectionDispositionCreate) Save(ctx context.Context) (*PurchaseRejectionDisposition, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PurchaseRejectionDispositionCreate) SaveX(ctx context.Context) *PurchaseRejectionDisposition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PurchaseRejectionDispositionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PurchaseRejectionDispositionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PurchaseRejectionDispositionCreate) defaults() error {
	if _, ok := _c.mutation.Status(); !ok {
		v := purchaserejectiondisposition.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := purchaserejectiondisposition.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if purchaserejectiondisposition.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized purchaserejectiondisposition.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := purchaserejectiondisposition.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PurchaseRejectionDispositionCreate) check() error {
	if _, ok := _c.mutation.DispositionNo(); !ok {
		return &ValidationError{Name: "disposition_no", err: errors.New(`ent: missing required field "PurchaseRejectionDisposition.disposition_no"`)}
	}
	if v, ok := _c.mutation.DispositionNo(); ok {
		if err := purchaserejectiondisposition.DispositionNoValidator(v); err != nil {
			return &ValidationError{Name: "disposition_no", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.disposition_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QualityInspectionID(); !ok {
		return &ValidationError{Name: "quality_inspection_id", err: errors.New(`ent: missing required field "PurchaseRejectionDisposition.quality_inspection_id"`)}
	}
	if v, ok := _c.mutation.QualityInspectionID(); ok {
		if err := purchaserejectiondisposition.QualityInspectionIDValidator(v); err != nil {
			return &ValidationError{Name: "quality_inspection_id", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.quality_inspection_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PurchaseReceiptID(); !ok {
		return &ValidationError{Name: "purchase_receipt_id", err: errors.New(`ent: missing required field "PurchaseRejectionDisposition.purchase_receipt_id"`)}
	}
	if v, ok := _c.mutation.PurchaseReceiptID(); ok {
		if err := purchaserejectiondisposition.PurchaseReceiptIDValidator(v); err != nil {
			return &ValidationError{Name: "purchase_receipt_id", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.purchase_receipt_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PurchaseReceiptItemID(); !ok {
		return &ValidationError{Name: "purchase_receipt_item_id", err: errors.New(`ent: missing required field "PurchaseRejectionDisposition.purchase_receipt_item_id"`)}
	}
	if v, ok := _c.mutation.PurchaseReceiptItemID(); ok {
		if err := purchaserejectiondisposition.PurchaseReceiptItemIDValidator(v); err != nil {
			return &ValidationError{Name: "purchase_receipt_item_id", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.purchase_receipt_item_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ReplacementReceiptID(); ok {
		if err := purchaserejectiondisposition.ReplacementReceiptIDValidator(v); err != nil {
			return &ValidationError{Name: "replacement_receipt_id", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.replacement_receipt_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DispositionType(); !ok {
		return &ValidationError{Name: "disposition_type", err: errors.New(`ent: missing required field "PurchaseRejectionDisposition.disposition_type"`)}
	}
	if v, ok := _c.mutation.DispositionType(); ok {
		if err := purchaserejectiondisposition.DispositionTypeValidator(v); err != nil {
			return &ValidationError{Name: "disposition_type", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.disposition_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PurchaseRejectionDisposition.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := purchaserejectiondisposition.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "PurchaseRejectionDisposition.quantity"`)}
	}
	if v, ok := _c.mutation.SupplierID(); ok {
		if err := purchaserejectiondisposition.SupplierIDValidator(v); err != nil {
			return &ValidationError{Name: "supplier_id", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.supplier_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SupplierName(); !ok {
		return &ValidationError{Name: "supplier_name", err: errors.New(`ent: missing required field "PurchaseRejectionDisposition.supplier_name"`)}
	}
	if v, ok := _c.mutation.SupplierName(); ok {
		if err := purchaserejectiondisposition.SupplierNameValidator(v); err != nil {
			return &ValidationError{Name: "supplier_name", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.supplier_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "PurchaseRejectionDisposition.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := purchaserejectiondisposition.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "PurchaseRejectionDisposition.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := purchaserejectiondisposition.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdempotencyPayloadHash(); !ok {
		return &ValidationError{Name: "idempotency_payload_hash", err: errors.New(`ent: missing required field "PurchaseRejectionDisposition.idempotency_payload_hash"`)}
	}
	if v, ok := _c.mutation.IdempotencyPayloadHash(); ok {
		if err := purchaserejectiondisposition.IdempotencyPayloadHashValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_payload_hash", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.idempotency_payload_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "PurchaseRejectionDisposition.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := purchaserejectiondisposition.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.version": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PostedBy(); ok {
		if err := purchaserejectiondisposition.PostedByValidator(v); err != nil {
			return &ValidationError{Name: "posted_by", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.posted_by": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CancelledBy(); ok {
		if err := purchaserejectiondisposition.CancelledByValidator(v); err != nil {
			return &ValidationError{Name: "cancelled_by", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.cancelled_by": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CancelReason(); ok {
		if err := purchaserejectiondisposition.CancelReasonValidator(v); err != nil {
			return &ValidationError{Name: "cancel_reason", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.cancel_reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "PurchaseRejectionDisposition.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := purchaserejectiondisposition.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "PurchaseRejectionDisposition.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PurchaseRejectionDisposition.created_at"`)}
	}
	return nil
}

func (_c *PurchaseRejectionDispositionCreate) sqlSave(ctx context.Context) (*PurchaseRejectionDisposition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PurchaseRejectionDispositionCreate) createSpec() (*PurchaseRejectionDisposition, *sqlgraph.CreateSpec) {
	var (
		_node = &PurchaseRejectionDisposition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(purchaserejectiondisposition.Table, sqlgraph.NewFieldSpec(purchaserejectiondisposition.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DispositionNo(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldDispositionNo, field.TypeString, value)
		_node.DispositionNo = value
	}
	if value, ok := _c.mutation.QualityInspectionID(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldQualityInspectionID, field.TypeInt, value)
		_node.QualityInspectionID = value
	}
	if value, ok := _c.mutation.PurchaseReceiptID(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldPurchaseReceiptID, field.TypeInt, value)
		_node.PurchaseReceiptID = value
	}
	if value, ok := _c.mutation.PurchaseReceiptItemID(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldPurchaseReceiptItemID, field.TypeInt, value)
		_node.PurchaseReceiptItemID = value
	}
	if value, ok := _c.mutation.DispositionType(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldDispositionType, field.TypeString, value)
		_node.DispositionType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldQuantity, field.TypeOther, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.SupplierID(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldSupplierID, field.TypeInt, value)
		_node.SupplierID = &value
	}
	if value, ok := _c.mutation.SupplierName(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldSupplierName, field.TypeString, value)
		_node.SupplierName = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.IdempotencyPayloadHash(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldIdempotencyPayloadHash, field.TypeString, value)
		_node.IdempotencyPayloadHash = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.PostedAt(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldPostedAt, field.TypeTime, value)
		_node.PostedAt = &value
	}
	if value, ok := _c.mutation.PostedBy(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldPostedBy, field.TypeInt, value)
		_node.PostedBy = &value
	}
	if value, ok := _c.mutation.CancelledAt(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldCancelledAt, field.TypeTime, value)
		_node.CancelledAt = &value
	}
	if value, ok := _c.mutation.CancelledBy(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldCancelledBy, field.TypeInt, value)
		_node.CancelledBy = &value
	}
	if value, ok := _c.mutation.CancelReason(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldCancelReason, field.TypeString, value)
		_node.CancelReason = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldCreatedBy, field.TypeInt, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(purchaserejectiondisposition.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ReplacementReceiptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   purchaserejectiondisposition.ReplacementReceiptTable,
			Columns: []string{purchaserejectiondisposition.ReplacementReceiptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(purchasereceipt.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReplacementReceiptID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PurchaseRejectionDispositionCreateBulk is the builder for creating many PurchaseRejectionDisposition entities in bulk.
type PurchaseRejectionDispositionCreateBulk struct {
	config
	err      error
	builders []*PurchaseRejectionDispositionCreate
}

// Save creates the PurchaseRejectionDisposition entities in the database.
func (_c *PurchaseRejectionDispositionCreateBulk) Save(ctx context.Context) ([]*PurchaseRejectionDisposition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PurchaseRejectionDisposition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PurchaseRejectionDispositionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PurchaseRejectionDispositionCreateBulk) SaveX(ctx context.Context) []*PurchaseRejectionDisposition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PurchaseRejectionDispositionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PurchaseRejectionDispositionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
