// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/internal/data/model/ent/predicate"
	"server/internal/data/model/ent/workflowbusinessstate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkflowBusinessStateUpdate is the builder for updating WorkflowBusinessState entities.
type WorkflowBusinessStateUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowBusinessStateMutation
}

// Where appends a list predicates to the WorkflowBusinessStateUpdate builder.
func (_u *WorkflowBusinessStateUpdate) Where(ps ...predicate.WorkflowBusinessState) *WorkflowBusinessStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *WorkflowBusinessStateUpdate) SetSourceType(v string) *WorkflowBusinessStateUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdate) SetNillableSourceType(v *string) *WorkflowBusinessStateUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *WorkflowBusinessStateUpdate) SetSourceID(v int) *WorkflowBusinessStateUpdate {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdate) SetNillableSourceID(v *int) *WorkflowBusinessStateUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *WorkflowBusinessStateUpdate) AddSourceID(v int) *WorkflowBusinessStateUpdate {
	_u.mutation.AddSourceID(v)
	return _u
}

// SetSourceNo sets the "source_no" field.
func (_u *WorkflowBusinessStateUpdate) SetSourceNo(v string) *WorkflowBusinessStateUpdate {
	_u.mutation.SetSourceNo(v)
	return _u
}

// SetNillableSourceNo sets the "source_no" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdate) SetNillableSourceNo(v *string) *WorkflowBusinessStateUpdate {
	if v != nil {
		_u.SetSourceNo(*v)
	}
	return _u
}

// ClearSourceNo clears the value of the "source_no" field.
func (_u *WorkflowBusinessStateUpdate) ClearSourceNo() *WorkflowBusinessStateUpdate {
	_u.mutation.ClearSourceNo()
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *WorkflowBusinessStateUpdate) SetOrderID(v int) *WorkflowBusinessStateUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdate) SetNillableOrderID(v *int) *WorkflowBusinessStateUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *WorkflowBusinessStateUpdate) AddOrderID(v int) *WorkflowBusinessStateUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *WorkflowBusinessStateUpdate) ClearOrderID() *WorkflowBusinessStateUpdate {
	_u.mutation.ClearOrderID()
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *WorkflowBusinessStateUpdate) SetBatchID(v int) *WorkflowBusinessStateUpdate {
	_u.mutation.ResetBatchID()
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdate) SetNillableBatchID(v *int) *WorkflowBusinessStateUpdate {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// AddBatchID adds value to the "batch_id" field.
func (_u *WorkflowBusinessStateUpdate) AddBatchID(v int) *WorkflowBusinessStateUpdate {
	_u.mutation.AddBatchID(v)
	return _u
}

// ClearBatchID clears the value of the "batch_id" field.
func (_u *WorkflowBusinessStateUpdate) ClearBatchID() *WorkflowBusinessStateUpdate {
	_u.mutation.ClearBatchID()
	return _u
}

// SetBusinessStatusKey sets the "business_status_key" field.
func (_u *WorkflowBusinessStateUpdate) SetBusinessStatusKey(v string) *WorkflowBusinessStateUpdate {
	_u.mutation.SetBusinessStatusKey(v)
	return _u
}

// SetNillableBusinessStatusKey sets the "business_status_key" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdate) SetNillableBusinessStatusKey(v *string) *WorkflowBusinessStateUpdate {
	if v != nil {
		_u.SetBusinessStatusKey(*v)
	}
	return _u
}

// SetOwnerRoleKey sets the "owner_role_key" field.
func (_u *WorkflowBusinessStateUpdate) SetOwnerRoleKey(v string) *WorkflowBusinessStateUpdate {
	_u.mutation.SetOwnerRoleKey(v)
	return _u
}

// SetNillableOwnerRoleKey sets the "owner_role_key" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdate) SetNillableOwnerRoleKey(v *string) *WorkflowBusinessStateUpdate {
	if v != nil {
		_u.SetOwnerRoleKey(*v)
	}
	return _u
}

// ClearOwnerRoleKey clears the value of the "owner_role_key" field.
func (_u *WorkflowBusinessStateUpdate) ClearOwnerRoleKey() *WorkflowBusinessStateUpdate {
	_u.mutation.ClearOwnerRoleKey()
	return _u
}

// SetBlockedReason sets the "blocked_reason" field.
func (_u *WorkflowBusinessStateUpdate) SetBlockedReason(v string) *WorkflowBusinessStateUpdate {
	_u.mutation.SetBlockedReason(v)
	return _u
}

// SetNillableBlockedReason sets the "blocked_reason" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdate) SetNillableBlockedReason(v *string) *WorkflowBusinessStateUpdate {
	if v != nil {
		_u.SetBlockedReason(*v)
	}
	return _u
}

// ClearBlockedReason clears the value of the "blocked_reason" field.
func (_u *WorkflowBusinessStateUpdate) ClearBlockedReason() *WorkflowBusinessStateUpdate {
	_u.mutation.ClearBlockedReason()
	return _u
}

// SetStatusChangedAt sets the "status_changed_at" field.
func (_u *WorkflowBusinessStateUpdate) SetStatusChangedAt(v time.Time) *WorkflowBusinessStateUpdate {
	_u.mutation.SetStatusChangedAt(v)
	return _u
}

// SetNillableStatusChangedAt sets the "status_changed_at" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdate) SetNillableStatusChangedAt(v *time.Time) *WorkflowBusinessStateUpdate {
	if v != nil {
		_u.SetStatusChangedAt(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *WorkflowBusinessStateUpdate) SetPayload(v map[string]interface{}) *WorkflowBusinessStateUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *WorkflowBusinessStateUpdate) ClearPayload() *WorkflowBusinessStateUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkflowBusinessStateUpdate) SetUpdatedAt(v time.Time) *WorkflowBusinessStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WorkflowBusinessStateMutation object of the builder.
func (_u *WorkflowBusinessStateUpdate) Mutation() *WorkflowBusinessStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkflowBusinessStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowBusinessStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkflowBusinessStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowBusinessStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkflowBusinessStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workflowbusinessstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowBusinessStateUpdate) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := workflowbusinessstate.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceID(); ok {
		if err := workflowbusinessstate.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.source_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceNo(); ok {
		if err := workflowbusinessstate.SourceNoValidator(v); err != nil {
			return &ValidationError{Name: "source_no", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.source_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrderID(); ok {
		if err := workflowbusinessstate.OrderIDValidator(v); err != nil {
			return &ValidationError{Name: "order_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BatchID(); ok {
		if err := workflowbusinessstate.BatchIDValidator(v); err != nil {
			return &ValidationError{Name: "batch_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.batch_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BusinessStatusKey(); ok {
		if err := workflowbusinessstate.BusinessStatusKeyValidator(v); err != nil {
			return &ValidationError{Name: "business_status_key", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.business_status_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerRoleKey(); ok {
		if err := workflowbusinessstate.OwnerRoleKeyValidator(v); err != nil {
			return &ValidationError{Name: "owner_role_key", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.owner_role_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BlockedReason(); ok {
		if err := workflowbusinessstate.BlockedReasonValidator(v); err != nil {
			return &ValidationError{Name: "blocked_reason", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.blocked_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkflowBusinessStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowbusinessstate.Table, workflowbusinessstate.Columns, sqlgraph.NewFieldSpec(workflowbusinessstate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(workflowbusinessstate.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(workflowbusinessstate.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(workflowbusinessstate.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceNo(); ok {
		_spec.SetField(workflowbusinessstate.FieldSourceNo, field.TypeString, value)
	}
	if _u.mutation.SourceNoCleared() {
		_spec.ClearField(workflowbusinessstate.FieldSourceNo, field.TypeString)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(workflowbusinessstate.FieldOrderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(workflowbusinessstate.FieldOrderID, field.TypeInt, value)
	}
	if _u.mutation.OrderIDCleared() {
		_spec.ClearField(workflowbusinessstate.FieldOrderID, field.TypeInt)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(workflowbusinessstate.FieldBatchID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBatchID(); ok {
		_spec.AddField(workflowbusinessstate.FieldBatchID, field.TypeInt, value)
	}
	if _u.mutation.BatchIDCleared() {
		_spec.ClearField(workflowbusinessstate.FieldBatchID, field.TypeInt)
	}
	if value, ok := _u.mutation.BusinessStatusKey(); ok {
		_spec.SetField(workflowbusinessstate.FieldBusinessStatusKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerRoleKey(); ok {
		_spec.SetField(workflowbusinessstate.FieldOwnerRoleKey, field.TypeString, value)
	}
	if _u.mutation.OwnerRoleKeyCleared() {
		_spec.ClearField(workflowbusinessstate.FieldOwnerRoleKey, field.TypeString)
	}
	if value, ok := _u.mutation.BlockedReason(); ok {
		_spec.SetField(workflowbusinessstate.FieldBlockedReason, field.TypeString, value)
	}
	if _u.mutation.BlockedReasonCleared() {
		_spec.ClearField(workflowbusinessstate.FieldBlockedReason, field.TypeString)
	}
	if value, ok := _u.mutation.StatusChangedAt(); ok {
		_spec.SetField(workflowbusinessstate.FieldStatusChangedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(workflowbusinessstate.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(workflowbusinessstate.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workflowbusinessstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowbusinessstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkflowBusinessStateUpdateOne is the builder for updating a single WorkflowBusinessState entity.
type WorkflowBusinessStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowBusinessStateMutation
}

// SetSourceType sets the "source_type" field.
func (_u *WorkflowBusinessStateUpdateOne) SetSourceType(v string) *WorkflowBusinessStateUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdateOne) SetNillableSourceType(v *string) *WorkflowBusinessStateUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *WorkflowBusinessStateUpdateOne) SetSourceID(v int) *WorkflowBusinessStateUpdateOne {
	_u.mutation.ResetSourceID()
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdateOne) SetNillableSourceID(v *int) *WorkflowBusinessStateUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// AddSourceID adds value to the "source_id" field.
func (_u *WorkflowBusinessStateUpdateOne) AddSourceID(v int) *WorkflowBusinessStateUpdateOne {
	_u.mutation.AddSourceID(v)
	return _u
}

// SetSourceNo sets the "source_no" field.
func (_u *WorkflowBusinessStateUpdateOne) SetSourceNo(v string) *WorkflowBusinessStateUpdateOne {
	_u.mutation.SetSourceNo(v)
	return _u
}

// SetNillableSourceNo sets the "source_no" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdateOne) SetNillableSourceNo(v *string) *WorkflowBusinessStateUpdateOne {
	if v != nil {
		_u.SetSourceNo(*v)
	}
	return _u
}

// ClearSourceNo clears the value of the "source_no" field.
func (_u *WorkflowBusinessStateUpdateOne) ClearSourceNo() *WorkflowBusinessStateUpdateOne {
	_u.mutation.ClearSourceNo()
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *WorkflowBusinessStateUpdateOne) SetOrderID(v int) *WorkflowBusinessStateUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdateOne) SetNillableOrderID(v *int) *WorkflowBusinessStateUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *WorkflowBusinessStateUpdateOne) AddOrderID(v int) *WorkflowBusinessStateUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// ClearOrderID clears the value of the "order_id" field.
func (_u *WorkflowBusinessStateUpdateOne) ClearOrderID() *WorkflowBusinessStateUpdateOne {
	_u.mutation.ClearOrderID()
	return _u
}

// SetBatchID sets the "batch_id" field.
func (_u *WorkflowBusinessStateUpdateOne) SetBatchID(v int) *WorkflowBusinessStateUpdateOne {
	_u.mutation.ResetBatchID()
	_u.mutation.SetBatchID(v)
	return _u
}

// SetNillableBatchID sets the "batch_id" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdateOne) SetNillableBatchID(v *int) *WorkflowBusinessStateUpdateOne {
	if v != nil {
		_u.SetBatchID(*v)
	}
	return _u
}

// AddBatchID adds value to the "batch_id" field.
func (_u *WorkflowBusinessStateUpdateOne) AddBatchID(v int) *WorkflowBusinessStateUpdateOne {
	_u.mutation.AddBatchID(v)
	return _u
}

// ClearBatchID clears the value of the "batch_id" field.
func (_u *WorkflowBusinessStateUpdateOne) ClearBatchID() *WorkflowBusinessStateUpdateOne {
	_u.mutation.ClearBatchID()
	return _u
}

// SetBusinessStatusKey sets the "business_status_key" field.
func (_u *WorkflowBusinessStateUpdateOne) SetBusinessStatusKey(v string) *WorkflowBusinessStateUpdateOne {
	_u.mutation.SetBusinessStatusKey(v)
	return _u
}

// SetNillableBusinessStatusKey sets the "business_status_key" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdateOne) SetNillableBusinessStatusKey(v *string) *WorkflowBusinessStateUpdateOne {
	if v != nil {
		_u.SetBusinessStatusKey(*v)
	}
	return _u
}

// SetOwnerRoleKey sets the "owner_role_key" field.
func (_u *WorkflowBusinessStateUpdateOne) SetOwnerRoleKey(v string) *WorkflowBusinessStateUpdateOne {
	_u.mutation.SetOwnerRoleKey(v)
	return _u
}

// SetNillableOwnerRoleKey sets the "owner_role_key" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdateOne) SetNillableOwnerRoleKey(v *string) *WorkflowBusinessStateUpdateOne {
	if v != nil {
		_u.SetOwnerRoleKey(*v)
	}
	return _u
}

// ClearOwnerRoleKey clears the value of the "owner_role_key" field.
func (_u *WorkflowBusinessStateUpdateOne) ClearOwnerRoleKey() *WorkflowBusinessStateUpdateOne {
	_u.mutation.ClearOwnerRoleKey()
	return _u
}

// SetBlockedReason sets the "blocked_reason" field.
func (_u *WorkflowBusinessStateUpdateOne) SetBlockedReason(v string) *WorkflowBusinessStateUpdateOne {
	_u.mutation.SetBlockedReason(v)
	return _u
}

// SetNillableBlockedReason sets the "blocked_reason" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdateOne) SetNillableBlockedReason(v *string) *WorkflowBusinessStateUpdateOne {
	if v != nil {
		_u.SetBlockedReason(*v)
	}
	return _u
}

// ClearBlockedReason clears the value of the "blocked_reason" field.
func (_u *WorkflowBusinessStateUpdateOne) ClearBlockedReason() *WorkflowBusinessStateUpdateOne {
	_u.mutation.ClearBlockedReason()
	return _u
}

// SetStatusChangedAt sets the "status_changed_at" field.
func (_u *WorkflowBusinessStateUpdateOne) SetStatusChangedAt(v time.Time) *WorkflowBusinessStateUpdateOne {
	_u.mutation.SetStatusChangedAt(v)
	return _u
}

// SetNillableStatusChangedAt sets the "status_changed_at" field if the given value is not nil.
func (_u *WorkflowBusinessStateUpdateOne) SetNillableStatusChangedAt(v *time.Time) *WorkflowBusinessStateUpdateOne {
	if v != nil {
		_u.SetStatusChangedAt(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *WorkflowBusinessStateUpdateOne) SetPayload(v map[string]interface{}) *WorkflowBusinessStateUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *WorkflowBusinessStateUpdateOne) ClearPayload() *WorkflowBusinessStateUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkflowBusinessStateUpdateOne) SetUpdatedAt(v time.Time) *WorkflowBusinessStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the WorkflowBusinessStateMutation object of the builder.
func (_u *WorkflowBusinessStateUpdateOne) Mutation() *WorkflowBusinessStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the WorkflowBusinessStateUpdate builder.
func (_u *WorkflowBusinessStateUpdateOne) Where(ps ...predicate.WorkflowBusinessState) *WorkflowBusinessStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkflowBusinessStateUpdateOne) Select(field string, fields ...string) *WorkflowBusinessStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkflowBusinessState entity.
func (_u *WorkflowBusinessStateUpdateOne) Save(ctx context.Context) (*WorkflowBusinessState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkflowBusinessStateUpdateOne) SaveX(ctx context.Context) *WorkflowBusinessState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkflowBusinessStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkflowBusinessStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkflowBusinessStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workflowbusinessstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkflowBusinessStateUpdateOne) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := workflowbusinessstate.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceID(); ok {
		if err := workflowbusinessstate.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.source_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceNo(); ok {
		if err := workflowbusinessstate.SourceNoValidator(v); err != nil {
			return &ValidationError{Name: "source_no", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.source_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrderID(); ok {
		if err := workflowbusinessstate.OrderIDValidator(v); err != nil {
			return &ValidationError{Name: "order_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.order_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BatchID(); ok {
		if err := workflowbusinessstate.BatchIDValidator(v); err != nil {
			return &ValidationError{Name: "batch_id", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.batch_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BusinessStatusKey(); ok {
		if err := workflowbusinessstate.BusinessStatusKeyValidator(v); err != nil {
			return &ValidationError{Name: "business_status_key", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.business_status_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerRoleKey(); ok {
		if err := workflowbusinessstate.OwnerRoleKeyValidator(v); err != nil {
			return &ValidationError{Name: "owner_role_key", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.owner_role_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BlockedReason(); ok {
		if err := workflowbusinessstate.BlockedReasonValidator(v); err != nil {
			return &ValidationError{Name: "blocked_reason", err: fmt.Errorf(`ent: validator failed for field "WorkflowBusinessState.blocked_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkflowBusinessStateUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowBusinessState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowbusinessstate.Table, workflowbusinessstate.Columns, sqlgraph.NewFieldSpec(workflowbusinessstate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkflowBusinessState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowbusinessstate.FieldID)
		for _, f := range fields {
			if !workflowbusinessstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflowbusinessstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(workflowbusinessstate.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(workflowbusinessstate.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSourceID(); ok {
		_spec.AddField(workflowbusinessstate.FieldSourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceNo(); ok {
		_spec.SetField(workflowbusinessstate.FieldSourceNo, field.TypeString, value)
	}
	if _u.mutation.SourceNoCleared() {
		_spec.ClearField(workflowbusinessstate.FieldSourceNo, field.TypeString)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(workflowbusinessstate.FieldOrderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(workflowbusinessstate.FieldOrderID, field.TypeInt, value)
	}
	if _u.mutation.OrderIDCleared() {
		_spec.ClearField(workflowbusinessstate.FieldOrderID, field.TypeInt)
	}
	if value, ok := _u.mutation.BatchID(); ok {
		_spec.SetField(workflowbusinessstate.FieldBatchID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBatchID(); ok {
		_spec.AddField(workflowbusinessstate.FieldBatchID, field.TypeInt, value)
	}
	if _u.mutation.BatchIDCleared() {
		_spec.ClearField(workflowbusinessstate.FieldBatchID, field.TypeInt)
	}
	if value, ok := _u.mutation.BusinessStatusKey(); ok {
		_spec.SetField(workflowbusinessstate.FieldBusinessStatusKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerRoleKey(); ok {
		_spec.SetField(workflowbusinessstate.FieldOwnerRoleKey, field.TypeString, value)
	}
	if _u.mutation.OwnerRoleKeyCleared() {
		_spec.ClearField(workflowbusinessstate.FieldOwnerRoleKey, field.TypeString)
	}
	if value, ok := _u.mutation.BlockedReason(); ok {
		_spec.SetField(workflowbusinessstate.FieldBlockedReason, field.TypeString, value)
	}
	if _u.mutation.BlockedReasonCleared() {
		_spec.ClearField(workflowbusinessstate.FieldBlockedReason, field.TypeString)
	}
	if value, ok := _u.mutation.StatusChangedAt(); ok {
		_spec.SetField(workflowbusinessstate.FieldStatusChangedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(workflowbusinessstate.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(workflowbusinessstate.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workflowbusinessstate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &WorkflowBusinessState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowbusinessstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
